### ISSUE TITLE
error

### ISSUE THREAD

**Issue by palashmandokhot** [OneSignal/OneSignal-Android-SDK#183] opened 2017-03-01 12:51 UTC
how to solve Error:java.lang.RuntimeException: Manifest merger failed with multiple errors, and in androidmanifest.xml merged text shows some error in this pictures.and in androidmanifest merged text this activity repeat two times---
        <activity android:name=".MainActivity" />
        <activity android:name=".MainActivity" />
![20170301_180153_resized b](https://cloud.githubusercontent.com/assets/26090315/23460483/a22e1690-feab-11e6-84b0-fe47b0d026b9.jpg)

**Comment by jkasten2** [comment] 2017-03-01 19:19
Duplicate of #182

**Closed by jkasten2** 2017-03-01 19:19 UTC
Labels: duplicate
