### ISSUE TITLE
[Bug]: 5.0.5 ModelStore.onChanged ANR triggered by a deadlock involving the main thread

### ISSUE THREAD

**Issue by albertoderodrigo** [OneSignal/OneSignal-Android-SDK#1943] opened 2023-12-14 09:32 UTC
### What happened?

After updating to the 5.0.5 version we have begun to see the arn "ANR triggered by a deadlock involving the main thread" for "com.onesignal.common.modeling.ModelStore.onChanged" on crashlytics.

**Devices**

<img width="567" alt="Screenshot 2023-12-14 at 10 34 27" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/18699142/f68ed554-5ac6-4cb4-bf0b-d5d34208d520">

**Log**

<img width="1269" alt="Screenshot 2023-12-14 at 10 31 47" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/18699142/54b31fa9-24a8-4d93-ad0d-45c5e83ad359">

[io.socialgamesonline.slotcom_issue_0a25eecebaa0dea15ea950f622cdf0c6_ANR_session_6579C321005E0001360A51B3870BC5DA_DNE_0_v2_stacktrace.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/13671392/io.socialgamesonline.slotcom_issue_0a25eecebaa0dea15ea950f622cdf0c6_ANR_session_6579C321005E0001360A51B3870BC5DA_DNE_0_v2_stacktrace.txt)

### Steps to reproduce?

```Markdown
we are not able to reproduce it we simply see the traces
```

### What did you expect to happen?

No errors

### OneSignal Android SDK version

5.0.5

### Android version

13, 12, 11

### Specific Android models

```Markdown
It's not specific
```

### Relevant log output

```Shell
Log attached on description
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment] 2023-12-15 20:27
@albertoderodrigo thank you for reaching out! We're investigating this and will get back to you as soon as possible.

**Comment by emawby** [comment] 2023-12-19 22:49
Thank you for reporting. This is a duplicate of other ANR reports we have received. I am closing and redirecting to #1918

**Closed by emawby** 2023-12-19 22:49 UTC

**Comment by albertoderodrigo** [comment] 2023-12-20 07:06
Hi, before opening this ticket I checked the other one and the traces did not match, are you sure it is a duplicate? Without going too deep, it looks like a deadlock in another part of the code.
