### ISSUE TITLE
[BUG] ANR on certain devices

### ISSUE THREAD

**Issue by Soft-Buddy** [OneSignal/OneSignal-Android-SDK#1945] opened 2023-12-17 12:58 UTC
### How can we help?

```
main (blocked):tid=1 systid=15790 | waiting to lock <0x05b915db> (java.util.Collections$SynchronizedMap) held by thread 43
       at com.onesignal.common.modeling.Model.getOptAnyProperty(Model.kt:639)
       at com.onesignal.common.modeling.Model.getOptStringProperty(Model.kt:558)
       at com.onesignal.common.modeling.Model.getStringProperty(Model.kt:484)
       at com.onesignal.common.modeling.Model.getStringProperty$default(Model.kt:481)
       at com.onesignal.common.modeling.Model.getId(Model.kt:60)
       at com.onesignal.common.modeling.ModelStore.get(ModelStore.kt:73)
       at com.onesignal.common.modeling.SingletonModelStore.getModel(SingletonModelStore.kt:24)
       at com.onesignal.session.internal.influence.impl.InfluenceDataRepository.getNotificationIndirectAttributionWindow(InfluenceDataRepository.kt:138)
       at com.onesignal.session.internal.influence.impl.NotificationTracker.getIndirectAttributionWindow(NotificationTracker.kt:36)
       at com.onesignal.session.internal.influence.impl.ChannelTracker.getLastReceivedIds(ChannelTracker.kt:81)
       at com.onesignal.session.internal.influence.impl.InfluenceManager.attemptSessionUpgrade(InfluenceManager.kt:240)
       at com.onesignal.session.internal.influence.impl.InfluenceManager.attemptSessionUpgrade$default(InfluenceManager.kt:203)
       at com.onesignal.session.internal.influence.impl.InfluenceManager.onSessionActive(InfluenceManager.kt:61)
       at com.onesignal.session.internal.session.impl.SessionService$onFocus$2.invoke(SessionService.kt:85)
       at com.onesignal.session.internal.session.impl.SessionService$onFocus$2.invoke(SessionService.kt:85)
       at com.onesignal.common.events.EventProducer.fire(EventProducer.kt:50)
       at com.onesignal.session.internal.session.impl.SessionService.onFocus(SessionService.kt:85)
       at com.onesignal.core.internal.application.impl.ApplicationService$handleFocus$1.invoke(ApplicationService.kt:369)
       at com.onesignal.core.internal.application.impl.ApplicationService$handleFocus$1.invoke(ApplicationService.kt:369)
       at com.onesignal.common.events.EventProducer.fire(EventProducer.kt:50)
       at com.onesignal.core.internal.application.impl.ApplicationService.handleFocus(ApplicationService.kt:369)
       at com.onesignal.core.internal.application.impl.ApplicationService.onActivityStarted(ApplicationService.kt:154)
       at android.app.Application.dispatchActivityStarted(Application.java:423)
       at android.app.Activity.dispatchActivityStarted(Activity.java:1429)
       at android.app.Activity.onStart(Activity.java:1926)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:496)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1485)
       at android.app.Activity.performStart(Activity.java:8143)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3766)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8192)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

Devices on which this occurred :
![image](https://github.com/OneSignal/OneSignal-Android-SDK/assets/149814863/6e5b2bfb-b1d0-489e-94e5-6df799b7b972)
![image](https://github.com/OneSignal/OneSignal-Android-SDK/assets/149814863/ab0d641e-90c2-46ba-89f9-684b75a43856)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment] 2023-12-19 22:48
Thank you for reporting! This is a duplicate of other ANR reports we have gotten so I am closing and redirecting to #1918

**Closed by emawby** 2023-12-19 22:48 UTC
Labels: Duplicate
