### ISSUE TITLE
java.lang.ClassNotFoundException Didn't find class "android.app.job.JobServiceEngine"

### ISSUE THREAD

**Issue by KirilaMenski** [OneSignal/OneSignal-Android-SDK#441] opened 2018-02-19 08:21 UTC
Hello.
When I send notification at first time I get this error:
```Java
Rejecting re-init on previously-failed class java.lang.Class<com.onesignal.JobIntentService$JobServiceEngineImpl>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/job/JobServiceEngine;
Rejecting re-init on previously-failed class java.lang.Class<com.onesignal.JobIntentService$JobServiceEngineImpl>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/job/JobServiceEngine;
Rejecting re-init on previously-failed class java.lang.Class<com.onesignal.JobIntentService$JobServiceEngineImpl>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/job/JobServiceEngine;
Rejecting re-init on previously-failed class java.lang.Class<com.onesignal.JobIntentService$JobServiceEngineImpl>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/job/JobServiceEngine;
Rejecting re-init on previously-failed class java.lang.Class<com.onesignal.JobIntentService$JobServiceEngineImpl>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/job/JobServiceEngine;
at void com.onesignal.GcmBroadcastReceiver.onReceive(android.content.Context, android.content.Intent) (GcmBroadcastReceiver.java:67)
        at void android.app.ActivityThread.handleReceiver(android.app.ActivityThread$ReceiverData) (ActivityThread.java:3306)
        at void android.app.ActivityThread.-wrap20(android.app.ActivityThread, android.app.ActivityThread$ReceiverData) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1719)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
        at void android.os.Looper.loop() (Looper.java:154)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6692)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1468)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1358)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.job.JobServiceEngine" on path: DexPathList[[zip file "/data/app/com.***.***.dev-1/base.apk", zip file "/data/app/com.***.***.dev-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.***.***.dev-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.***.***.dev-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.***.***.dev-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.***.***.dev-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.***.***.dev-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.***.***.dev-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.***.***.dev-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.***.***.dev-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.***.***.dev-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at android.content.Intent com.onesignal.NotificationExtenderService.getIntent(android.content.Context) (NotificationExtenderService.java:208)
        at boolean com.onesignal.NotificationBundleProcessor.startExtenderService(android.content.Context, android.os.Bundle, com.onesignal.NotificationBundleProcessor$ProcessedBundleResult) (NotificationBundleProcessor.java:460)
        at com.onesignal.NotificationBundleProcessor$ProcessedBundleResult com.onesignal.NotificationBundleProcessor.processBundleFromReceiver(android.content.Context, android.os.Bundle) (NotificationBundleProcessor.java:434)
```

I think this is due to the lack of `android.permission.BIND_JOB_SERVICE` which has not been set in android manifest. I was trying to create my custom NotificationService which was implement from com.onesignal.NotificationExtenderService but it not helped.

I will be really appreciate if someone can help me.
Thanks advance

**Comment by jkasten2** [comment] 2018-02-20 01:44
@KirilaMenski What versions of Android are you seeing the error on? Could you let us know OneSignal SDK version you are using as well.

`android.permission.BIND_JOB_SERVICE` is required on the `NotificationExtenderService` but if this was an issue the stack trace would be different as noted in issue #424.

**Comment by KirilaMenski** [comment] 2018-02-20 06:19
@jkasten2 Thank for reply. I am using last version of OneSignal SDK 3.8.0 and tested on phones with the version of android 7.0 and above

**Comment by jkasten2** [comment] 2018-02-28 01:20
@KirilaMenski Is this causing a crash or are you just noticing these entries in the logcat after sending a push? Are you consistently getting this error on your test devices each time you send a notification?

Do you get the same results with our example project?
https://github.com/OneSignal/OneSignal-Android-SDK/tree/master/Examples/AndroidStudio

**Comment by KirilaMenski** [comment] 2018-02-28 06:28
@jkasten2 It is not a crash. Actually, I did not notice that this somehow affected the work of the program. It is just a message, but I am getting this only for the first notification when app is started. It is weird. 

No, I don't have same result with your example.
I initialize OneSignal by the follow:
```OneSignal.init(Context, googleProjectNumber, oneSignalAppId, notificationOpenHandler(), notificationReceivedHandler())
        OneSignal.enableSound(false)
        OneSignal.enableVibrate(false)
        OneSignal.setInFocusDisplaying(OneSignal.OSInFocusDisplayOption.None)```

**Comment by jkasten2** [comment] 2018-02-28 20:00
@KirilaMenski Thanks for checking. I believe the cause of it is due to the device trying to resolve all the inherited classes. `android.app.job.JobServiceEngine` noted in the error as it is only on Android 8.0 device, however since there is a guard around the code to detect the Android version this won't result in a crash or broken behavior.

Since this is only a logcat message and I don't believe it is possible to prevent I am going to close this issue. However feel free to reply if I missed something and I'll reopen this issue.

**Closed by jkasten2** 2018-02-28 20:00 UTC

**Comment by TaifRaoof** [comment] 2018-04-14 11:26
java.lang.ClassNotFoundException Didn't find class "android.app.job.JobServiceEngine" also appear again in android v7.0

i used the code in example project
https://github.com/OneSignal/OneSignal-Android-SDK/tree/master/Examples/AndroidStudio

**Comment by NVentimiglia** [comment] 2019-07-24 03:49
@jkasten2 I was searching for a crash log, and came across this post.

Please confirm this is expected behavior and not a real crash.

Android SDK 3.30
