### ISSUE TITLE
Android 12 - Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS

### ISSUE THREAD

**Issue by mariofelesdossantosjunior** [OneSignal/OneSignal-Android-SDK#1570] opened 2022-04-19 12:53 UTC
Android 12 failure in open notification\

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.useblu/com.onesignal.NotificationOpenedReceiver}: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.useblu (pid=5553, uid=10390) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.

Caused by java.lang.SecurityException
Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.useblu (pid=5553, uid=10390) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
```

**Description:**
```
Caused by java.lang.SecurityException
Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.useblu (pid=5553, uid=10390) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
```

(your description here)

**Environment**
Android SDK 31
OneSignal version [4.0.0, 4.99.99]

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment] 2022-04-19 18:08
@mariofelesdossantosjunior Thanks for reporting, this is already fixed in latest [4.7.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.7.1) update.

Reference: Duplicate of issue #1543

**Closed by jkasten2** 2022-04-19 18:08 UTC
