### ISSUE TITLE
Fatal Exception: OneSignalDbHelper

### ISSUE THREAD

**Issue by josinaldobarbosa** [OneSignal/OneSignal-Android-SDK#240] opened 2017-06-02 01:22 UTC
Version: 3.4.4

Device: Xperia\xe2\x84\xa2 M4 Aqua
Android: 6.0.1

`OneSignalDbHelper.java` line 102

```Java
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
       at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:234)
       at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
       at com.onesignal.OneSignalDbHelper.getReadableDbWithRetries(OneSignalDbHelper.java:102)
       at com.onesignal.GenerateNotification.createSummaryNotification(GenerateNotification.java:404)
       at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:333)
       at com.onesignal.GenerateNotification.fromJsonPayload(GenerateNotification.java:107)
       at com.onesignal.NotificationBundleProcessor.Process(NotificationBundleProcessor.java:85)
       at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(NotificationBundleProcessor.java:75)
       at com.onesignal.GcmIntentService.onHandleIntent(GcmIntentService.java:60)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by jkasten2** [comment] 2017-06-02 01:31
@josinaldobarbosa This is most likely an issue with the device out of space or some kind of other I/O disk error causing this to fail. The SDK does retry but it even hit this limit. Are you able to reproduce the issue? Did you get this on the first receive of a notification or after?

**Comment by josinaldobarbosa** [comment] 2017-06-02 01:34
@jkasten2 
By the fabric, so it checks was on the same days that notification was sent

**Comment by jkasten2** [comment] 2017-06-02 01:36
@josinaldobarbosa Was their more than one occurrence? If so could you share the fabric link here or with OneSignal support?

**Comment by josinaldobarbosa** [comment] 2017-06-02 01:39
http://crashes.to/s/0f478f6b912

**Comment by jkasten2** [comment] 2017-06-03 01:05
@josinaldobarbosa Thanks, looks to be just that one device. We will see what can be done to handle this but due to the rarity of it this will be a lower priority.

**Comment by jkasten2** [comment] 2018-03-06 01:32
@josinaldobarbosa Closing this issue as we haven't seen any other reports of this issue or any other recent SQL errors. If you see any future errors make sure make sure the device is runner a newer version of your app that would have the OneSignal SDK 3.4.4 or newer.

**Closed by jkasten2** 2018-03-06 01:32 UTC
Labels: non-reproducible
