### ISSUE TITLE
Missing permission to insert badges on Motorola phone

### ISSUE THREAD

**Issue by asfdfdfd** [OneSignal/OneSignal-Android-SDK#543] opened 2018-05-17 19:08 UTC
**Description:**

Crash while receiving push on Motorola Moto X Play because of missing permission to insert badges.

**Environment**

OneSignal 3.8.4

**Anything else:**

http://crashes.to/s/1e3488638e3

**Comment by jkasten2** [comment] 2018-05-17 21:36
@asfdfdfd Thanks for the log. Is this an issue you can reproduce on your test device? It looks like the crash only happened once on one device.

**Comment by asfdfdfd** [comment] 2018-05-18 11:49
> Is this an issue you can reproduce on your test device?

No. 

This is crash from the unknown user remote device.

> It looks like the crash only happened once on one device.

Yes.

I've looked through OneSignal Android SDK source code and it has not any permissions related to the Motorola phones. So i thought that it may be useful to highlight this issue and probably add permission.

**Comment by jkasten2** [comment] 2018-06-15 09:22
@asfdfdfd I don't believe the Android launch on Motorola devices supports badges. This user may have installed a custom launcher which does support badges however.

OneSignal includes the Android library [ShortcutBadger]( https://github.com/leolin310148/ShortcutBadger) of version 1.1.16 which might have a bug in it as well. I do see this crash in one of their closed issues but I was closed and fixed in an update before this.
https://github.com/leolin310148/ShortcutBadger/issues/110

It possible the user side-loaded an old version for your app so hard to say.

Since it looks like you haven't seen the crash again of the one instance from looking at your link again I am going to mark this issue as resolved.

**Closed by jkasten2** 2018-06-15 09:22 UTC
Labels: Bug, Bug:To_Confirmation, Bug:VeryRare
