### ISSUE TITLE
Play services dialog messages

### ISSUE THREAD

**Issue by keklikhasan** [OneSignal/OneSignal-Android-SDK#75] opened 2016-07-12 09:03 UTC
![screenshot from 2016-07-12 12-01-45](https://cloud.githubusercontent.com/assets/924755/16761355/722c3998-4828-11e6-9742-ffec65b0f370.png)

this message shows to update google play services. but it doesn't support other languages can you add other languages or somehow let us change text or disable the dialog options ?

**Comment by jkasten2** [comment] 2016-07-17 01:34
Closing, duplicate of #74

**Closed by jkasten2** 2016-07-17 01:34 UTC
