### ISSUE TITLE
[Bug]: WorkManager crash on OneSignal 4.8.9

### ISSUE THREAD

**Issue by bundleberk** [OneSignal/OneSignal-Android-SDK#2078] opened 2024-05-07 20:19 UTC
### What happened?

I am using onesignal 4.8.9 and workmanager 2.8.1. I'm disabling workmanager initializer in my manifest because im using a custom workmanager configuration for setting the hilt worker factory. I am not initializing workmanager myself. I am seeing this crash in crashlytics and it is not rare, happens a lot. 

We cannot upgrade to onesignal 5.x.x because of a bug that causes unresponsive notifications on xiaomi devices. So we are kind of stuck here.

`Fatal Exception: java.lang.IllegalStateException: WorkManager is already initialized.  Did you try to initialize it manually without disabling WorkManagerInitializer? See WorkManager#initialize(Context, Configuration) or the class level Javadoc for more information.
       at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:200)
       at androidx.work.WorkManager.initialize(WorkManager.java:210)
       at com.onesignal.OSWorkManagerHelper.getInstance(OSWorkManagerHelper.kt:62)
       at com.onesignal.OSNotificationWorkManager.beginEnqueueingWork(OSNotificationWorkManager.java:66)
       at com.onesignal.NotificationBundleProcessor$3.onResult(NotificationBundleProcessor.java:423)
       at com.onesignal.OSNotificationDataController$5.run(OSNotificationDataController.java:242)
       at java.lang.Thread.run(Thread.java:923)`

Any solutions?

### Steps to reproduce?

```Markdown
Cannot reproduce
```

### What did you expect to happen?

I expect no crashes

### OneSignal Android SDK version

Release 4.8.9

### Android version

13, 12, 11, 10, 9, 8, 7.1, 7.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment] 2024-05-07 20:55
@bundleberk I believe this is due [a workaround ](https://github.com/OneSignal/OneSignal-Android-SDK/pull/1721) for the ["WorkManager is not initialized properly" bug with WorkManager](https://issuetracker.google.com/issues/258176803) we added in [4.8.5](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.5). In summary, since Google's WorkManager doesn't initialize sometimes (reason is unknown) the SDK OneSignal detects this and then initializes it. However if your app is also initializing WorkManager it can race with OneSignal initializing it, which results in the "WorkManager is already initialized" crash.
* Do you also have "WorkManager is already initialized" being thrown from your code initializing WorkManager? Or are you catching that?
* I wouldn't expect the crash to be common, as the race condition comes down to a a single if check. What percentage of crashes do you see? Could you share the crash report from the Google Console with OneSignal? See [Google's guide on how to share SDK crashes](https://support.google.com/googleplay/android-developer/answer/9859174).

In 5.x.x the "WorkManager is already initialized" should never throw from OneSignal code.

>We cannot upgrade to onesignal 5.x.x because of a bug that causes unresponsive notifications on xiaomi devices. So we are kind of stuck here.

Thanks for the feedback, this signal means we can try get more priority on fixing that issue.

**Comment by bundleberk** [comment] 2024-05-07 21:33
I am not initializing workmanager manually, I am only using a custom configuration to set hiltworkerfactory.

according to [https://developer.android.com/develop/background-work/background-tasks/persistent/configuration/custom-configuration](this) document to be able to use custom configurations, the default workmanager initializer must be removed by adding a provider to manifest and initializing workmanager is not necessary.

do you think it would make a difference if I initialize workmanager manually just before I call onesignal.init()? 

<img width="1258" alt="Screenshot 2024-05-08 at 00 32 02" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/145975488/ba2778ec-80ff-4780-8e4c-43da05cf9206">

it is seen as the most common crash on crashlytics.

**Comment by bundleberk** [comment] 2024-05-14 23:55
Any updates on this? @jkasten2

**Comment by emawby** [comment] 2024-05-16 21:41
This looks like a duplicate of #1748. OneSignal is actively investigating solutions, but I will close this one to continue discussion in the other thread.

**Closed by emawby** 2024-05-16 21:41 UTC
Labels: Duplicate
