### ISSUE TITLE
Cant launch an Activity after Killing the app.

### ISSUE THREAD

**Issue by cirogg** [OneSignal/OneSignal-Android-SDK#779] opened 2019-06-14 15:40 UTC
**Description:**

Im trying to launch one specific  activity when i tap on a notification. I just did it in my way and in the way that is here in the example. If i DONT kill the app, it works perfectly. I have my method setNotificationOpenedHandler() where i only have an intent and a startActivity(intent) to launch the activity. It does it's job if the app is opened or running on the background.

BUT if i KILL the app, when i tap on the notification (Yes, i get the notification), nothing happens. I dont know what to do anymore. I have everything like the example here.

**Environment**

I tried this in mi s9+, in a xiaomi mi a1 (both android pie), tried too in two diferents Motorola with android 6. 

**Steps to Reproduce Issue:**

1. Kill the app
2. Send Notification
3. Tap on notification
4. Nothing happens.

**Comment by AlbertVilaCalvo** [comment] 2019-06-17 10:36
This happens to me too with a OnePlus 5T. To reproduce it, I have to go to the developer settings and set the "Limit background processes" to "No background processes". With this, if I send a notification to my phone and I open it while the app is closed, the activity is not opened. It just does nothing. The notification does disappear on click, but nothing happens.

**Comment by AlbertVilaCalvo** [comment] 2019-06-17 11:00
To fix this you can setup a `NotificationExtenderService` as explained in https://documentation.onesignal.com/docs/service-extensions

This works for me:

```
<service
    android:name=".push.OneSignalNotificationExtenderService"
    android:permission="android.permission.BIND_JOB_SERVICE"
    android:exported="false">
    <intent-filter>
        <action android:name="com.onesignal.NotificationExtender" />
    </intent-filter>
</service>
```

```
class OneSignalNotificationExtenderService : NotificationExtenderService() {

    override fun onNotificationProcessing(result: OSNotificationReceivedResult): Boolean {
        showNotification(result)
        // Return true to stop the notification from displaying.
        return true
    }

    private fun showNotification(result: OSNotificationReceivedResult) {
        val intent = Intent(this, MainActivity::class.java).apply {
            flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
        }

        val pendingIntent: PendingIntent = PendingIntent.getActivity(this, 0, intent, 0)

        val builder = NotificationCompat.Builder(this, "OS_996e9015-a984-4c93-880d-0e3fd55aa0bd")
            .setSmallIcon(R.drawable.ic_stat_onesignal_default)
            .setContentTitle(result.payload.title)
            .setContentText(result.payload.body)
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
            // Set the intent that will fire when the user taps the notification
            .setContentIntent(pendingIntent)
            .setAutoCancel(true)

        with(NotificationManagerCompat.from(this)) {
            // notificationId is a unique int for each notification that you must define
            notify(22, builder.build())
        }
    }

}
```

**Comment by AlbertVilaCalvo** [comment] 2019-06-17 12:08
BTW you can grab the channel ID from the JSON payload like this:

```
val payload = JSONObject(result.payload.rawPayload)
val channelPayload = payload.getString("chnl")
val channelId = JSONObject(channelPayload).getString("id")
```

**Comment by rgomezp** [comment] 2019-06-17 23:30
Thanks @AlbertVilaCalvo for your response. I was not aware this was a problem for some devices. @cirogg I would just say to add to Albert's response that you should make sure you are using the on opened handler and not the on received handler accidentally.

**Comment by cirogg** [comment] 2019-06-18 13:44
Hi! Yes, im using the .setNotificationOpenedHandler in my MainActivity where i have this inside:

`Intent intent = new Intent(getApplicationContext(), MagMyMessageActivity.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT | Intent.FLAG_ACTIVITY_NEW_TASK);
        startActivity(intent);`

That piece of code get executed perfectly when the app is running or just minimized in the background. But when i kill the app it never get executed.

The notifications are showed perfectly with the app killed too. It just that i tap on them and nothing happens if the app is killed.

Maybe im not understanding what i should write here in the NotificationExtendedService. 

`public class NotificationExtenderServiceC extends NotificationExtenderService {
    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
        
        //I should write something here???
        
        return false;
    }
}
`

I just need to launch one specifiy activity when i tap the notification and the app is killed like when the app is NOT killed.

**Comment by rgomezp** [comment] 2019-06-18 17:37
Take a look at our [documentation](https://documentation.onesignal.com/docs/service-extensions#section-getting-a-payload-from-a-notification) on getting a payload from a notification in the service extension. You can specify which activity should be opened in the notification payload `additionalData` parameter. From there, you simply tell your app to navigate to that activity.

**Comment by cirogg** [comment] 2019-06-19 13:01
Thanks for the anaswer. 
Talking about that "payload" aditionalData. In the example `String additionalData = receivedResult.payload.additionalData;` they are saving in a String something that comes from that payload. Where i should set that aditionalData? I mean, if i understood right, i have to set there my Intent to launch my own activity

**Comment by cirogg** [comment] 2019-06-19 16:00
Edit of last post: I talk to my team and now i understand how to send aditionalData from ONeSignal Dashboard.

But everything inside of the NotificationExtendedService got executed when the notification arrives.

So, i need to execute some StartActivity(MyOwnActivity) when i tap on the notification. That is inside of .setNotificationOpenHanlder in my activity. So, i dont know what to do anymore.

**Comment by rgomezp** [comment] 2019-06-21 01:35
If the notification is a regular notification, do it from your activity (not the NES) and get the payload through the [normal process](https://documentation.onesignal.com/docs/android-native-sdk#section--notificationopenedhandler-)

**Comment by cirogg** [comment] 2019-06-24 13:04
I will drop here some parts of my code. Maybe im doing something wrong. And i will repeat this. Everything in the setNotificationOpenedHandler() works perfectly when the app is open or in the background. But i need to execute that when the app is KILLED. I did the service thing, i added it to the manifest whit the <service> tags and disabled the default behavior.



On my MainActivity:

`OneSignal.startInit(MagHomeActivity.this)
                .setNotificationReceivedHandler(new ExampleNotificationReceivedHandler())
                .setNotificationOpenedHandler(new ExampleNotificationOpenedHandler())
                .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
                .unsubscribeWhenNotificationsAreDisabled(true)
                .init();`

Here my ExampleNotificationReceivedHandler and my ExampleNotificationOpenedHandler.


```
private class ExampleNotificationOpenedHandler implements OneSignal.NotificationOpenedHandler {
        // This fires when a notification is opened by tapping on it.
        @Override
        public void notificationOpened(OSNotificationOpenResult result) {

            Intent intent = new Intent(getApplicationContext(), MagMyMessageActivity.class);
            intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT | Intent.FLAG_ACTIVITY_NEW_TASK);
            startActivity(intent);

        }
    }

    private class ExampleNotificationReceivedHandler implements OneSignal.NotificationReceivedHandler {
        @Override
        public void notificationReceived(OSNotification notification) {
            final String notificationID = notification.payload.notificationID;
            JSONObject tags = new JSONObject();
            try {
                MagServices service = MagApplication.getRetrofitAuth(MagHomeActivity.this).create(MagServices.class);
                Call<ResponseBody> magazines = service.registerNotification(notificationID);
                magazines.enqueue(new Callback<ResponseBody>() {
                    @Override
                    public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {

                    }

                    @Override
                    public void onFailure(Call<ResponseBody> call, Throwable t) {

                    }

                });

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

```

```
And here my NotificationExtendedService: (I tested some things here and i understand that this got executed when the notification arrives. No when i tap on it.)

public class NotificationExtenderServiceC extends NotificationExtenderService {
    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {

        //I should write something here???

        //Test
        Intent intent = new Intent(getApplicationContext(),MagMyMessageActivity.class);
        PendingIntent pi = PendingIntent.getActivity(this,0,intent,0);

        OverrideSettings overrideSettings = new OverrideSettings();
        overrideSettings.extender = new NotificationCompat.Extender() {
            @Override
            public NotificationCompat.Builder extend(NotificationCompat.Builder builder) {
                //builder.setContentIntent(pi);
                return builder.setContentIntent(pi);
            }
        };

        //Test

        JSONObject s =  receivedResult.payload.additionalData;
        try {
            String actividad = s.getString("intent");
        } catch (JSONException e) {
            e.printStackTrace();
        }

        Intent intent1 = new Intent(this,MagMyMessageActivity.class);
        startActivity(intent1);


        return false;
    }
}
```

**Comment by rgomezp** [comment] 2019-06-25 20:17
It sounds like the problem is with the 'opened' handler as you claim the issue is that nothing happens when the notification is tapped. 

The NES is not useful for the use case you are aiming for. It should only be used for one of the following:
- Receive data in the background with or without displaying a notification (note: different than "on opened" event)
- Override specific notification settings depending on client side app logic such as custom accent color, vibration pattern, or other any other NotificationCompat options available. See Android's documentation on the NotificationCompat options.

Can you check if the handler code is even being executed? Try using our [logging method](https://documentation.onesignal.com/docs/android-native-sdk#section--setloglevel-)

**Comment by cirogg** [comment] 2019-06-27 15:50
I will try logging it and see what happens. But, when i debug my code, the method get executed perfectly but it doesnt get executed when te app is killed.

**Comment by rgomezp** [comment] 2019-07-08 23:28
@cirogg ,
Do you have any new insights?

**Comment by cirogg** [comment] 2019-07-10 12:12
Nope. We have on pause this Task of the project because we are stucked. We are on other tasks now. I will try again in a few days but we did everything that is in the documentation and its not working :(. I will let you know when i on the task again.

**Comment by rgomezp** [comment] 2019-07-18 20:30
Howdy @cirogg ,
I'm going to go ahead and close this issue for now and will reopen if you request it when you get around to testing. Thanks!

**Closed by rgomezp** 2019-07-18 20:30 UTC
Labels: Help Wanted, Possible Bug

**Comment by crushy26** [comment] 2020-05-24 22:29
Hi @rgomezp, this issue seems to persist. I am on Oneplus3 device and using channels as well. 

This issue usually apps when the device is idle or in standby for a longer time and then you unlock the device and click on the notification, the notification disappears and the activity doesn't open.

The foreground and background works completely fine.

As @AlbertVilaCalvo explained. I tried to produce the issue through developer options and also implemented his solution. Unfortunately, It didn't work and seems like a critical issue.

PS: My app is in react native, but this shouldn't matter since on Oneplus Android 9 & above the issue will persist.

**Comment by AlbertVilaCalvo** [comment] 2020-05-25 18:47
Note that OnePlus is very aggressive with background things - see https://dontkillmyapp.com/oneplus

There is a screen in the Settings -> Battery -> Battery optimization in which you can relax the background "optimizations" for specific apps.

**Comment by crushy26** [comment] 2020-05-26 20:08
Hi @AlbertVilaCalvo I am aware about this, but does this means, I will have to get it non-optimized from user? 

Because I am able to receive notification, it's just after idle time of device if notification is present and I try to click it doesn't work

**Comment by AlbertVilaCalvo** [comment] 2020-05-26 20:17
@crushy26 take a look at the code I put on https://github.com/OneSignal/OneSignal-Android-SDK/issues/781

**Comment by crushy26** [comment] 2020-05-26 21:05
Hi @AlbertVilaCalvo I followed your code from [here](https://github.com/OneSignal/OneSignal-Android-SDK/issues/779#issuecomment-502636328), is this not the latest one you commented there? or should I follow #781 that you mentioned now?

**Comment by AlbertVilaCalvo** [comment] 2020-05-28 17:07
@crushy26 `LET_ONESIGNAL_SHOW_NOTIFICATION` was a boolean flag to switch between the 2 ways of showing the notification

**Comment by abdullah-al-shafi** [comment] 2020-09-20 16:49
This example demonstrate about How to open an activity after receiving a PUSH notification in Android

Step 1 − Create a new project in Android Studio, go to File ⇒ New Project and fill all required details to create a new project.

Step 2 − Add the following code to src/MyFirebaseMessagingService.java

`package app.shafi.sbf.com.notifyme ;
import android.app.NotificationChannel ;
import android.app.NotificationManager ;
import android.app.PendingIntent ;
import android.content.Context ;
import android.content.Intent ;
import android.support.v4.app.NotificationCompat ;
import com.google.firebase.messaging.FirebaseMessagingService ;
import com.google.firebase.messaging.RemoteMessage ;
public class MyFirebaseMessagingService extends FirebaseMessagingService {
   public static final String NOTIFICATION_CHANNEL_ID = "10001" ;
   private final static String default_notification_channel_id = "default" ;
   @Override
   public void onNewToken (String s) {
      super .onNewToken(s) ;
   }
   @Override
   public void onMessageReceived (RemoteMessage remoteMessage) {
      super .onMessageReceived(remoteMessage) ;
      Intent notificationIntent = new Intent(getApplicationContext() , MainActivity. class ) ;
      notificationIntent.putExtra( "NotificationMessage" , "I am from Notification" ) ;
      notificationIntent.addCategory(Intent. CATEGORY_LAUNCHER ) ;
      notificationIntent.setAction(Intent. ACTION_MAIN ) ;
      notificationIntent.setFlags(Intent. FLAG_ACTIVITY_CLEAR_TOP | Intent. FLAG_ACTIVITY_SINGLE_TOP ) ;
      PendingIntent resultIntent = PendingIntent. getActivity (getApplicationContext() , 0 , notificationIntent , 0 ) ; 
      NotificationCompat.Builder mBuilder = new NotificationCompat.Builder(getApplicationContext() , 
         default_notification_channel_id )
         .setSmallIcon(R.drawable. ic_launcher_foreground )
         .setContentTitle( "Test" )
         .setContentText( "Hello! This is my first push notification" )
         .setContentIntent(resultIntent) ;
      NotificationManager mNotificationManager = (NotificationManager) getSystemService(Context. NOTIFICATION_SERVICE ) ;
      if (android.os.Build.VERSION. SDK_INT >= android.os.Build.VERSION_CODES. O ) {
         int importance = NotificationManager. IMPORTANCE_HIGH ;
         NotificationChannel notificationChannel = new
         NotificationChannel( NOTIFICATION_CHANNEL_ID , "NOTIFICATION_CHANNEL_NAME" , importance) ;
         mBuilder.setChannelId( NOTIFICATION_CHANNEL_ID ) ;
         assert mNotificationManager != null;
         mNotificationManager.createNotificationChannel(notificationChannel) ;
      }
      assert mNotificationManager != null;
      mNotificationManager.notify(( int ) System. currentTimeMillis () ,
      mBuilder.build()) ;
   }
}`

**Comment by abdelhakpro** [comment] 2021-02-01 16:18
Hi,
iam facing same issue like cirogg! i tried everything, no solutions! any updates ?

**Comment by abdelhakpro** [comment] 2021-02-01 16:20
Im trying to launch one specific activity when i tap on a notification.
If i DONT kill the app, it works perfectly. I have my method setNotificationOpenedHandler() where i only have an intent and a startActivity(intent) to launch the activity. It does it's job if the app is opened or running on the background.

BUT if i KILL the app, when i tap on the notification (Yes, i get the notification), nothing happens. I dont know what to do anymore.

**Comment by furkanbzkurt** [comment] 2021-04-25 14:27
Still no solutions for this?

**Comment by KKChong** [comment] 2022-03-02 14:32
Same here. Any solutions?
