### ISSUE TITLE
Crash with 3.14.0 version

### ISSUE THREAD

**Issue by pedrofurtado** [OneSignal/OneSignal-Android-SDK#1039] opened 2020-06-02 01:50 UTC
Stacktrace:

```
android.database.sqlite.SQLiteException: 
  at android.database.sqlite.SQLiteConnection.nativePrepareStatement (Native Method)
  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement (SQLiteConnection.java:890)
  at android.database.sqlite.SQLiteConnection.prepare (SQLiteConnection.java:501)
  at android.database.sqlite.SQLiteSession.prepare (SQLiteSession.java:588)
  at android.database.sqlite.SQLiteProgram.<init> (SQLiteProgram.java:58)
  at android.database.sqlite.SQLiteStatement.<init> (SQLiteStatement.java:31)
  at android.database.sqlite.SQLiteDatabase.delete (SQLiteDatabase.java:1573)
  at com.onesignal.OneSignalCacheCleaner.cleanCachedUniqueOutcomeEventNotifications (OneSignalCacheCleaner.java:167)   <------ this line causes the crash, according to Google Play Console
  at com.onesignal.OneSignalCacheCleaner.access$100 (OneSignalCacheCleaner.java:18)
  at com.onesignal.OneSignalCacheCleaner$1.run (OneSignalCacheCleaner.java:51)
  at java.lang.Thread.run (Thread.java:764)
```

**Comment by pedrofurtado** [comment] 2020-06-02 01:52
![Capturar](https://user-images.githubusercontent.com/10530520/83471242-90b4c780-a45a-11ea-84b0-ee4b1f5f4dce.PNG)

**Comment by rgomezp** [comment] 2020-06-08 21:57
Duplicate of #1033

**Closed by rgomezp** 2020-06-08 21:57 UTC

**Comment by jkasten2** [comment] 2020-06-11 03:49
This is actually a duplicate of #988, not 1033

**Comment by danieldz7** [comment] 2020-06-15 09:35
Hello, in my application, they are happening on a Samsung Galaxy J2 Prime device (grandpplte), 1536MB RAM, Android 6.0, with the following message:

java.lang.NullPointerException:
at com.onesignal.OneSignalCacheCleaner$2.run (OneSignalCacheCleaner.java:116)
at java.lang.Thread.run (Thread.java:818)

I am using the following version of OneSignal for the implementation in Gradle:
dependencies {
classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.7'
}
.....
dependencies {
.....
implementation 'com.onesignal:OneSignal:3.14.0'
.....
}

**Comment by rgomezp** [comment] 2020-06-15 23:59
Hello,
this has been resolved in the newest version. Please upgrade
