### ISSUE TITLE
[Bug]: Adding Tag On User Not Reflecting Immediately

### ISSUE THREAD

**Issue by rahat14** [OneSignal/OneSignal-Android-SDK#1951] opened 2023-12-28 15:36 UTC
### What happened?

i am using latest release of one signal , now i am trying to send notification using filter  from postman ,  so the system add a tag named  "id" when a new user login to my app. then when i try to send notification by using filter the app do not receive any notification.

 `"filters": [
        {
            "field": "tag",
            "key": "id",
            "relation": "=",
            "value": "rahatshovo.dev@gmail.com"
        }
    ], ` 

But if i  restart the app , same filter works  , i recieve notifications.  i am setting tag by using `  OneSignal.getUser().addTag("id"  , "rahatshovo.dev@gmail.com");`****

### Steps to reproduce?

```Markdown
1. install com.onesignal:OneSignal:[5.0.0, 5.99.99]
2. create a tag for a user, 
3. try to send a notification by using the filter for that tag  it will not receive any notification 
4. But restarting the app everything becomes normal
```

### What did you expect to happen?

i expect that when adding a tag to the user it should reflect Immediately. So, users do not need to restart app to get any tag value filtered notification.

### OneSignal Android SDK version

com.onesignal:OneSignal:[5.0.0, 5.99.99]

### Android version

13

### Specific Android models

```Markdown
Pixel 6 
Redmi k20 pro 
Andorid Emulator.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment] 2023-12-28 21:41
Hi @rahat14 thanks for reaching out. It sounds like perhaps the tag request is not successfully being sent in the same session. Would you be able to send over a [log](https://documentation.onesignal.com/docs/capturing-a-debug-log) reproducing this issue so we can take a closer look? Thanks!

**Comment by rahat14** [comment] 2023-12-31 09:57
Found The issue but could not  understand here is the attached log Image 
![Screenshot 2023-12-31 155540](https://github.com/OneSignal/OneSignal-Android-SDK/assets/27925309/16cfd979-d7b4-4273-82f0-111c2d5c1596)

**Comment by emawby** [comment] 2024-01-11 18:45
@rahat14 It appears the user has already reached their tag limit. If you believe that to be an error please reach out to our support team.

**Comment by jennantilla** [comment] 2024-01-17 17:49
Closing this issue since this appears to be related to entitlements. Please let us know if there are any additional questions or concerns!

**Closed by jennantilla** 2024-01-17 17:49 UTC
