### ISSUE TITLE
My server crashed everytime i use onesignal in my wordpress website

### ISSUE THREAD

**Issue by mTny** [OneSignal/OneSignal-Android-SDK#314] opened 2017-09-28 11:40 UTC
Hello, I would like to understand the main reason that make my server crash
I using onesignal with my wordpress site
After publish notification to my people my server reach 100% RAM and 100% CPU , :-O!
I using this settings:

`
Action Buttons | [{"id": "id1", "text": "Settings", "icon": "ic_menu_manage"}, {"id": "id2", "text": "Share", "icon": "ic_menu_share"}]
Additional Data | {"postid":5151,"sharelink":"http://MY_SERVER_URL/POST_ID"}
URL to launch | N/A
Sound | default
Small Icon | App Icon
Large Icon | https://OTHER_SERVER_URL/drawable_xxxhdpi_icon.png
Big Picture | http://MY_SERVER_URL/NOTICE.png
LED color |  
Accent color |  
Lock Screen Visibility | Public
Group Key |  
Group Message | null
Background Data
`
i have about 1400 users,
Is using "Big Picture" as a photo from my server can cause crash? 
What can i do to avoid it?
Best regards

**Comment by gdeglin** [comment] 2017-09-28 15:59
Yes, your guess is probably correct. When you send a notification with a big picture, every device that receives the notification will download the picture to display it. Make sure to host pictures on a server that can handle a very large amount of traffic in a short amount of time.

Closing this for now since it's not a bug. Feel free to reach out to our support team at support@onesignal.com if you need any more help with this.

**Closed by gdeglin** 2017-09-28 15:59 UTC
