### ISSUE TITLE
[Bug]: EventProducer.fire

### ISSUE THREAD

**Issue by ayushi-sk** [OneSignal/OneSignal-Android-SDK#1858] opened 2023-10-03 07:30 UTC
### What happened?

java.util.ConcurrentModificationException

### Steps to reproduce?

```Markdown
Sometimes on app start, sometimes on notification receive
```

### What did you expect to happen?

Not crash the app

### OneSignal Android SDK version

5.0.2

### Android version

13

### Relevant log output

```Shell
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.onesignal.common.events.EventProducer.fire(EventProducer.kt:43)
       at com.onesignal.core.internal.application.impl.ApplicationService.setCurrent(ApplicationService.kt:50)
       at com.onesignal.core.internal.application.impl.ApplicationService.onActivityStarted(ApplicationService.kt:145)
       at android.app.Application.dispatchActivityStarted(Application.java:413)
       at android.app.Activity.dispatchActivityStarted(Activity.java:1483)
       at android.app.Activity.onStart(Activity.java:2017)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1566)
       at android.app.Activity.performStart(Activity.java:8572)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3934)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8410)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arthurgeron-work** [comment] 2023-10-06 15:06
Getting the same error here, seems like it's trying to modify a collection using an iterator, which generates a crash.

**Comment by jennantilla** [comment] 2023-10-06 20:19
Thanks for the reports! We're looking into this.

**Comment by nan-li** [comment] 2023-10-12 18:38
Hi all, I apologize for any delay,

We have identified the cause and are working on the fix for all the methods this crash is reported.

**Comment by ayushi-sk** [comment] 2023-10-16 05:47
Hi,
Any update on when you are going to release the fixes?

**Comment by arthurgeron-work** [comment] 2023-10-18 20:10
I've found a way to reproduce this error consistently, with a temporary fix: https://github.com/OneSignal/OneSignal-Android-SDK/issues/1857#issuecomment-1769244894

**Comment by jennantilla** [comment] 2023-11-07 18:43
Hello everyone! Thank you for your patience here. We have introduced a fix for this crash in our latest release, [5.0.4](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.4). Please update your SDK and let us know if you are still having any issues.

**Comment by jennantilla** [comment] 2023-11-14 20:39
Closing this issue; please let us know if you see any further occurrences of this exception. Thanks!

**Closed by jennantilla** 2023-11-14 20:39 UTC
Labels: Bug

**Comment by tobus2012** [comment] 2024-04-04 22:53
Ok and for those who use OneSignalSDK.DotNet 5.0.2 version in Xamarin.Form how do we fix this bug??

**Comment by jkasten2** [comment] 2024-04-04 23:02
@tobus2012 You will need to update to [OneSignalSDK.DotNet 5.1.0](https://github.com/OneSignal/OneSignal-DotNet-SDK/releases/tag/5.1.0) or newer to get this fix. Please follow up on the [OneSignal-DotNet-SDK](https://github.com/OneSignal/OneSignal-DotNet-SDK) repo if you have issues, since this repo is only for Android native issues.

**Comment by tobus2012** [comment] 2024-04-04 23:25
@jkasten2  Note on Xamarin Forms

Xamarin Forms is no longer supported beyond version [5.0.2](https://github.com/OneSignal/OneSignal-DotNet-SDK/releases/tag/5.0.2) of our .NET SDK. Microsoft has guides on migrating to Maui [here](https://learn.microsoft.com/en-us/dotnet/maui/migration/?view=net-maui-8.0), if needed.

version 5.1.0 works with xamarin.form? because 5.1.1 does not work
