### ISSUE TITLE
One signal ANR FCMBroadcastReceiver

### ISSUE THREAD

**Issue by roubertedgar-hotmart** [OneSignal/OneSignal-Android-SDK#1418] opened 2021-08-19 20:49 UTC
Description:
Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000010 pkg=com.mypackage cmp=com.mypackage/com.onesignal.FCMBroadcastReceiver (has extras) }

Environment:

minSdk = 23
compileSdk = 30
targetSdk = 30

One signal version =  4.4.2
One signal plugin version =  0.13.4

**Comment by shahabrauf18** [comment] 2022-01-18 10:36
@jkasten2 No stacktrace available
![image](https://user-images.githubusercontent.com/5953527/149921031-41c737fd-a5fe-43d9-a84f-16a4e61c272f.png)
![image](https://user-images.githubusercontent.com/5953527/149921111-d61f9a67-2a60-4e36-92b2-2c936478a944.png)

**Comment by jkasten2** [comment] 2022-01-18 19:12
@shahabrauf18 Thanks for the screenshot. Could you try removing the filter on the specific device as I see Motorola Droid Turbo, this might provide a stack trace. If not can you try selecting a few other devices to see if Google will provide a stack trace for you. Without a stack trace or steps to reproduce we don't have the required information to investigate the issue.

**Comment by nan-li** [comment] 2022-03-01 22:38
Hi @shahabrauf18, @roubertedgar-hotmart,

Do you have any updates on this issue, particularly if you're able to get a stack trace?

> Without a stack trace or steps to reproduce we don't have the required information to investigate the issue.

**Comment by aqeelzoobi** [comment] 2022-05-09 06:25
Did you resolved this ANR ??
I am facing the same ANR in my app.
Kindly inform about the solution if u resolved

**Comment by jkasten2** [comment] 2022-05-09 07:27
@aqeelzoobi It is unclear OneSignal is the cause of the ANRs listed here. ANRs reports begin with the `Intent` that starts the app process but that doesn't not indicate the code that caused the ANR.

I recommend checking to make sure you are not doing too much work on the main thread in your `Application.onCreate`.

Please provide a full stack trace of all threads from the ANR so we can attempt to find the root cause.

**Comment by aqeelzoobi** [comment] 2022-05-09 10:19
In the Application.onCreate i am init only the onesingal instance .

**Comment by jkasten2** [comment] 2022-05-16 23:13
@aqeelzoobi Can you share the stack trace from the ANR or provide the steps to reproduce? We will need one of these to investigate if the is OneSignal and what the root cause is.

**Comment by nan-li** [comment] 2022-06-16 22:50
Without a stack trace or steps to reproduce, there isn't enough information for us to investigate this, or to figure out if it is OneSignal-related. The Broadcast of Intent ANR shows how the app's process is started but not the root cause of what is blocking the main thread.

See https://github.com/OneSignal/OneSignal-Android-SDK/issues/1542#issuecomment-1157958839 for an example of a similar ANR and the root cause is something else in the main thread.

Closing this issue. If more information/stack traces become available, we can re-open and investigate then.

**Closed by nan-li** 2022-06-16 22:50 UTC
Labels: Needs More Information
