### ISSUE TITLE
Gradle build fail with Proguard activated on latest release

### ISSUE THREAD

**Issue by Tweener** [OneSignal/OneSignal-Android-SDK#217] opened 2017-04-28 15:44 UTC
My build (./gradlew clean build) started to fail du to the latest release (v3.5.0) of OneSignal SDK with Proguard activated.
This is the error:

`Unexpected error while performing partial evaluation:
  Class       = [com/onesignal/OneSignalChromeTab]
  Method      = [setup(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V]
  Exception   = [java.lang.IllegalArgumentException] (Can't find common super class of [java/lang/NoClassDefFoundError] (with 5 known super classes) and [com/onesignal/OneSignalChromeTab$OneSignalCustomTabsServiceConnection] (with 1 known super classes))
Warning: Exception while processing task java.io.IOException: java.lang.IllegalArgumentException: Can't find common super class of [java/lang/NoClassDefFoundError] (with 5 known super classes) and [com/onesignal/OneSignalChromeTab$OneSignalCustomTabsServiceConnection] (with 1 known super classes)`

I'm using a previous version of the SDK for the time being, until it gets fixed.

**Comment by jkasten2** [comment] 2017-04-28 19:45
@Tweener Thanks for the report, I am looking in to it.

**Comment by jkasten2** [comment] 2017-04-28 21:48
@Tweener I am not able to reproduce this. Can you attach your `build.gradle` files?

**Comment by jkasten2** [comment] 2017-04-29 00:00
@Tweener Fixed in commit 39df04841e8f2a1afceffbc1b40713af919ee0d3. It will be included in the next release. Feel free to still post the details I requested above and I can ensure there isn't' another issue.

**Closed by jkasten2** 2017-04-29 00:00 UTC

**Comment by Tweener** [comment] 2017-04-29 13:04
Hi @jkasten2,
Sorry for the late reply, I just saw your messages.

Indeed, I didn't add the property `-dontpreverify` in my proguard config. This is what I have:
`-dontwarn com.onesignal.**
-keep class com.onesignal.** { *; }`.
I don't remember where I found it, could be in your SDK documentation or on a sample in the github repo.

Do I need to change/add anything after it has been released?

Also, according to your documentation, the Gradle dependency for this SDK is the following:
`compile 'com.onesignal:OneSignal:3.+@aar'`. It is not recommended, because that means we don't have the control over which version we are using, and a build could fail during the continuous integration process, without even changing anything (that's what happened to me actually).
I'm now using a specific version for the time being (ie: `compile 'com.onesignal:OneSignal:3.4.3'`).

Thanks again for fixing that problem quickly! 👍

**Comment by jkasten2** [comment] 2017-05-03 20:16
@Tweener We aim to follow the semantic versioning where defaults and required changes aren't part of minor and patch releases.

This issue specifically was rare as most projects contain the following line
```
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
```
It includes the following, which without them can create compile errors with our SDK and most Android code.

```
# Optimization is turned off by default. Dex does not like code run
# through the ProGuard optimize and preverify steps (and performs some
# of these optimizations on its own).
-dontoptimize
-dontpreverify
```

Also if `proguardFiles` is omitted completely from your 'build.gradle` `proguard-android.txt` will still be used.

I have however changed our SDK dev app to build without the `-dontpreverify` flag in commit 1f79a22a360a09bce1f57de9cc58ccb4aac97be8 so we don't have a regression issue on this.

Thanks.

**Comment by caipivara** [comment] 2017-09-05 13:41
@jkasten2 it will be cool if you can add `consumerProguardFiles` inside of the api like:

```
android {
  defaultConfig {
       consumerProguardFiles 'rules.pro'
   }
```

and then every client will use your defaults without any setup.
