### ISSUE TITLE
crash when com.onesignal.OneSignal.getGcmPreferences

### ISSUE THREAD

**Issue by JustinLim0318** [OneSignal/OneSignal-Android-SDK#271] opened 2017-07-19 08:32 UTC
Hello,

I have encountered a crash and below is the snapshot of it : 
```
Fatal Exception: java.lang.IllegalArgumentException: position=536954052 length=8825140
       at com.android.dex.Dex.open(Dex.java:188)
       at com.android.dex.Dex$StringTable.get(Dex.java:893)
       at com.android.dex.Dex$TypeIndexToDescriptorTable.get(Dex.java:914)
       at com.android.dex.Dex$TypeIndexToDescriptorTable.get(Dex.java:913)
       at libcore.reflect.AnnotationAccess.getAnnotationReader(AnnotationAccess.java:542)
       at libcore.reflect.AnnotationAccess.isAnonymousClass(AnnotationAccess.java:506)
       at java.lang.Class.isAnonymousClass(Class.java:1236)
       at java.lang.Class.getSimpleName(Class.java:1081)
       at com.onesignal.OneSignal.getGcmPreferences(OneSignal.java:1369)
       at com.onesignal.OneSignalStateSynchronizer$UserState.persistState
(OneSignalStateSynchronizer.java:355)
       at com.onesignal.OneSignalStateSynchronizer$UserState.persistStateAfterSync
(OneSignalStateSynchronizer.java:403)
       at com.onesignal.OneSignalStateSynchronizer$UserState.access$800
(OneSignalStateSynchronizer.java:215)
       at com.onesignal.OneSignalStateSynchronizer.syncUserState
(OneSignalStateSynchronizer.java:516)
       at com.onesignal.OneSignalStateSynchronizer$NetworkHandlerThread$1.run
(OneSignalStateSynchronizer.java:472)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```
Thanks and best Regards,
Justin

**Comment by jkasten2** [comment] 2017-07-21 23:03
@JustinLim0318 The crash seems to be happening when the dex file in your APK is being loaded and parsed. Its like you may be using multi-dex?

Are their any other logcat entries related before or after this one? Are you able to reproduce the issue? Please include all device models and Android versions you have tested on.

Thanks.

**Comment by JustinLim0318** [comment] 2017-07-24 06:53
@jkasten2 Yes I'm using multi-dex for my project and i couldn't reproduce the issue.
The Fabric crash log: 
Device: alps EP1
OS : 6.1

**Comment by jkasten2** [comment] 2017-07-24 22:48
@JustinLim0318 Is the issue only isolated to this model of device? If so the issue is most likely due to a bug in the ROM on the device.

**Comment by JustinLim0318** [comment] 2017-07-25 07:02
@jkasten2 yes only happened in this device.

**Comment by jkasten2** [comment] 2017-07-25 21:50
@JustinLim0318 Thanks for confirming, closing this issue as it isn't an issue with the SDK.

**Closed by jkasten2** 2017-07-25 21:50 UTC
Labels: non-reproducible, wontfix

**Comment by JustinLim0318** [comment] 2017-07-26 03:53
@jkasten2 thanks for the fast response too. closing this issue from my side as well
