### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION: OS_REST_SUCCESS_CALLBACK

### ISSUE THREAD

**Issue by hanling0** [OneSignal/OneSignal-Android-SDK#1523] opened 2022-01-24 08:42 UTC
**Description:**
When I add the implementation 'com.amazon.device:amazon-appstore-sdk:3.+', it will report an error 

**Environment**
 compileSdkVersion = 29
    targetSdkVersion = 29
    minSdkVersion = 23
    buildToolsVersion = '29.0.2'

dependencies {
        classpath "com.android.tools.build:gradle:3.6.4"
        classpath 'com.blankj:bus-gradle-plugin:2.6'
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.14.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

implementation 'com.onesignal:OneSignal:4.6.3'

D/OneSignal: OneSignal saveInfluenceParams: InfluenceParams{indirectNotificationAttributionWindow=60, notificationLimit=10, indirectIAMAttributionWindow=1440, iamLimit=10, directEnabled=false, indirectEnabled=false, unattributedEnabled=false}
 D/OneSignal: reassignDelayedInitParams with appContext: com.eagleheart.amanvpn.AQApplication@5984804
 V/OneSignal: setAppId called with id: b361fa1c-8ce0-4c25-bff4-93aee1f79e00 changing id from: null
 V/OneSignal: Starting OneSignal initialization!
 V/OneSignal: No class found, not setting up OSRemoteNotificationReceivedHandler
 D/OneSignal: OneSignal handleActivityLifecycleHandler inForeground: false
 D/OneSignal: App id set for first time:  b361fa1c-8ce0-4c25-bff4-93aee1f79e00
 E/AndroidRuntime: FATAL EXCEPTION: OS_REST_SUCCESS_CALLBACK
    Process: com.eagleheart.amanvpn, PID: 20674
    java.lang.NullPointerException: null receiver
        at java.lang.reflect.Method.invoke(Native Method)
        at com.onesignal.TrackAmazonPurchase.<init>(TrackAmazonPurchase.java:68)
        at com.onesignal.OneSignal.handleAmazonPurchase(OneSignal.java:940)
        at com.onesignal.OneSignal.init(OneSignal.java:817)
        at com.onesignal.OneSignal.setAppId(OneSignal.java:692)
        at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1136)
        at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:844)
        at com.onesignal.OneSignal$6.complete(OneSignal.java:1077)
        at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
        at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
        at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
        at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:283)
        at java.lang.Thread.run(Thread.java:923)
 D/OOMEventManagerFK: checkEventAndDumpForJE: 0
 I/Process: Sending signal. PID: 20674 SIG: 9

**Comment by nan-li** [comment] 2022-01-24 21:57
Thanks for reporting @hanling0

I am going to close this as a duplicate of issue #1516, and a PR has been submitted by a helpful user (https://github.com/OneSignal/OneSignal-Android-SDK/pull/1519) so the fix will be available in the next release.

**Closed by nan-li** 2022-01-24 21:57 UTC
