### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException at GenerateNotification.java line 656

### ISSUE THREAD

**Issue by DimaKoz** [OneSignal/OneSignal-Android-SDK#43] opened 2016-04-27 19:38 UTC
I got a crashlog related to the OneSignal-Android-SDK
2.3.0, that I can't reproduce. You can see it in [log.txt](https://github.com/one-signal/OneSignal-Android-SDK/files/239267/log.txt).
About device:
<img width="952" alt="screen shot 2016-04-27 at 22 37 23" src="https://cloud.githubusercontent.com/assets/3092276/14865742/23d3d8ec-0cd1-11e6-8428-df2936288e51.png">

**Comment by jkasten2** [comment] 2016-04-28 20:15
@DimaKoz Thanks for reporting this as well.

It seems that `getResources()` on the `IntentService` `context` is returning `null`. From a quick search I haven't been able to determine a cause for this. Is this the only report you have for this crash?

`IntentService` is part of the Android Support Library v4, can you let us know what version you are using in your app?
Any additional information you can provide on this will be helpful.

Thanks.

**Comment by DimaKoz** [comment] 2016-04-28 21:23
@jkasten2 Sure.

```groovy
ext {
    //...
    supportLibVersion = '23.2.1'  // variable that can be referenced to keep support libs consistent
    googleLibVersion = '8.4.0'  // variable that can be referenced to keep google libs consistent
    //...
}

//....
dependencies {
    //....
    compile "com.android.support:appcompat-v7:${supportLibVersion}"
    compile "com.android.support:support-v4:${supportLibVersion}"
    compile "com.android.support:design:${supportLibVersion}"
    compile "com.google.android.gms:play-services-gcm:${googleLibVersion}"
    compile "com.google.android.gms:play-services-analytics:${googleLibVersion}"
    compile "com.google.android.gms:play-services-location:${googleLibVersion}"
    compile 'com.onesignal:OneSignal:2.3.0@aar'
   //...
    }
```

**Comment by jkasten2** [comment] 2016-04-28 22:47
@DimaKoz Thanks, the versions of these all look good.

My mistake on the `IntentService` class, it is part of the Android OS so this issue might be Android version specific or even device specific due to manufacturer customizations.

Is there only one crash report for this device? Do you see any other devices with this crash or are you able to reproduce this?

**Comment by jkasten2** [comment] 2016-06-21 03:13
@DimaKoz Have you seen any further reports of this error?

**Comment by DimaKoz** [comment] 2016-06-22 06:39
Hi.
No, I didn't see this exception in the latest version.

Thank you.

2016-06-21 6:13 GMT+03:00 Josh Kasten <notifications@github.com>:

**Comment by jkasten2** [comment] 2016-06-22 08:14
Closing the issue then, feel free to reopen it if you see it again.

**Closed by jkasten2** 2016-06-22 08:14 UTC
