### ISSUE TITLE
[Onesignal SDK: 3.10.2] ANR seen at com.onesignal.OneSignal.onAppFocus (OneSignal.java:1155)

### ISSUE THREAD

**Issue by mitonline** [OneSignal/OneSignal-Android-SDK#650] opened 2018-10-13 23:49 UTC
**Description:**

Hi,
I see that the above issue is fixed in 3.10.1. But I still see this issue in my app when using 3.10.2. I tried to recreate this problem but can't. I see quiet a few ANRs with this error on the developer console. 
I am attaching the complete stack trace.

**Environment**

Android SDK: 27
OneginalSDK: 3.10.2
Integrated Onesignal sdk using build.gradle (android studio)

**Steps to Reproduce Issue:**

Have tried recreating this but can't. I do see these on developer console

**Anything else:**
Complete stack trace attached
[stacktrace.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/2475961/stacktrace.txt)

**Comment by jkasten2** [comment] 2018-10-15 20:19
@mitonline Thanks for reporting along with the full stack trace. We will take a look and get back to you

**Comment by mitonline** [comment] 2018-10-20 07:18
Hi Team,
I see this in other places with a different heading on the console but same backtrace. Attached the stacktrace.  We are trying to recreate this. Will keep this thread updated if we recreate this. 
Do you need any additional information from us that will help you identify the problem ?

**_Input dispatching timed out (Waiting because no window has focus but there is a focused application that may eventually add a window when it finishes starting up.)_**

com.x.y.z.MainActivity
[stacktrace_new.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/2497901/stacktrace_new.txt)

**Comment by cashwalk-ryan** [comment] 2019-02-07 08:34
Hi, 
I have same issue.

OneginalSDK: 3.10.2

**Comment by tbt-hasan** [comment] 2019-02-22 10:45
As I saw, it mostly happens when the device internet connection is not very good and the HTTP requests are gonna time out.

**Environment**
OneginalSDK: 3.10.6

**Comment by jkasten2** [comment] 2019-05-23 21:12
There are some possible race conditions due to some events that can fire at the same time in the OneSignal SDK, such as the app going out of focus while a location update is firing. They are normally extremely rare as the timing has to be very precise to reproduce the problem.

Instead of trying to tackle each rare ANR / concurrent modification bug case by case with these race conditions we are evaluating our threading strategy on the SDK as a whole. As we migrate to the new threading model these ANRs will be fixed with the new implementation. If there is a reproducible large spread issue however we will definitely address those before this still.

**Comment by tbt-hasan** [comment] 2019-06-01 06:15
FYI, I fixed this issue in [ this commit in my cloned repo](https://github.com/Daal/OneSignal-Android-SDK/commit/685b7f9caddc5069fce50bc59967c4d63dfa1a4b).

**Comment by rgomezp** [comment] 2019-06-05 22:51
I will go ahead and close this issue as we review your commit @tbt-hasan internally. Thanks for contributing. If anyone has issues with his fork, I can reopen this issue. Thanks

**Closed** 2020-01-30 22:20 UTC
Labels: Bug: Low Priority
