### ISSUE TITLE
Process crashes with DeadObjectException

### ISSUE THREAD

**Issue by pedrofsn** [OneSignal/OneSignal-Android-SDK#1426] opened 2021-08-30 21:32 UTC
**Description:**
```
2021-08-30 18:22:51.000 1928-1928/? W/ActivityManager: Exception when unbinding service xx.xxx.xxx.xx.xx/com.onesignal.SyncJobService
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1127)
        at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1100)
        at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:2894)
        at com.android.server.am.ActiveServices.unbindServiceLocked(ActiveServices.java:1758)
        at com.android.server.am.ActivityManagerService.unbindService(ActivityManagerService.java:20524)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1695)
        at com.android.server.job.JobServiceContext.closeAndCleanupJobLocked(JobServiceContext.java:783)
        at com.android.server.job.JobServiceContext.onServiceDisconnected(JobServiceContext.java:452)
        at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1749)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1764)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at com.android.server.SystemServer.run(SystemServer.java:454)
        at com.android.server.SystemServer.main(SystemServer.java:294)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:838)
```

**Environment**
Android API 28 | Android 9.0
OneSignal SDK 4.5.1

**Steps to Reproduce Issue:**
Open app, navigate for a few seconds (or do nothing) and process crash

**Comment by emawby** [comment] 2021-08-31 17:28
@pedrofsn Thank you for reporting. This appears to be a duplicate of #1013 so I am going to close this one

**Closed by emawby** 2021-08-31 17:28 UTC
Labels: Duplicate
