### ISSUE TITLE
OneSignal does not process FCM Pushes

### ISSUE THREAD

**Issue by thefex** [OneSignal/OneSignal-Android-SDK#732] opened 2019-04-04 11:52 UTC
**Description:**
OneSignal does not support FCM. 
None of code has inherited from FirebaseMessagingService (*so as far as I know it is not possible that OneSignal has FCM Push support) , only GCM notifications are processed (they are sent to device though, with custom FirebaseMessagingService I can process notification data manually).

(your description here)

**Environment**
All APIs, master branch / production release of OneSignal.

**Steps to Reproduce Issue:**
1. Remove GCM library from project. Keep only Firebase Messaging library.
2. App stops showing notifications.

**Anything else:**

**Comment by jkasten2** [comment] 2019-04-05 21:54
@thefex OneSignal can use either the GCM or FCM library for registering the device for push and to get a valid token. It will use FCM over GCM if both libraries happen to be built into the app. Our dependencies should be setup to automatically pull in FCM though.

For processing a push received by the device, this directly goes to the [`GcmBroadcastReceiver`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/GcmBroadcastReceiver.java#L46-L48) in this SDK. It has GCM in the name but it works with FCM pushes as well. It handles the `Intent` [directly](https://github.com/OneSignal/OneSignal-Android-SDK/blob/c33b7a943fb8e08e174ecae8d0a63c67c0a5140c/OneSignalSDK/onesignal/src/release/AndroidManifest.xml#L12-L21) so we actually don't use GCM or FCM client library for processing pushes.

What is the exact FCM library and version you are using in your project? It should be `com.google.firebase:firebase-messaging` just to confirm you have the correct one.

**Comment by thefex** [comment] 2019-04-06 09:34
Look at manifest, there is no declaration of " <action android:name="com.google.firebase.MESSAGING_EVENT"/>" anywhere.
Besides.. looking at GcmBroadcastReceiver it ignores everything if isGcmMessage message method returns false.
Can you try a sample with GCM library removed?

I managed to still use OneSignal though I have implemented FirebaseMessagingService and parsing of PUSH on my own.

**Comment by jkasten2** [comment] 2019-04-09 23:06
@thefex Sorry for the delay. The `com.google.firebase.MESSAGING_EVENT` Intent action is a rebroadcast of the `com.google.android.c2dm.intent.RECEIVE` Intent action by the Firebase client library that gets build into apps. The Firebase library handles the same `com.google.android.c2dm.intent.RECEIVE` action, OneSignal is just handling it directly instead of the relying on the Firebase client library for this.

I haven't checked in a few releases to confirm the that `message_type` type is still "gcm" but I don't believe this as changed.I believe they have left this so this doesn't cause any compatibility issues.  I'll double check though to confirm.

Our example project only uses FCM today.
See the [example project defined gradle dependencies](https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/Examples/AndroidStudio/app/build.gradle#L42-L51) as well as the [SDK source gradle dependency on FCM](https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/build.gradle#L34). Note, GCM is there as `compileOnly` for backwards compatibility, however it won't cause it to become dependency when adding OneSignal to your project's gradle.

Can you let us know the following with your setup?
1. SDK target version in your build.gradle
2. The Android versions you are able to reproduce the issue on.
3. The version of the "Google Play services" app installed on the devices.

We plan to drop all backwards compatibility code on GCM in a major (4.0.0) release, but currently both library will register and receive notifications today.

**Comment by rgomezp** [comment] 2019-04-23 19:01
Closing due to no response

**Closed by rgomezp** 2019-04-23 19:01 UTC
Labels: Needs More Details
