### ISSUE TITLE
Error Required by OneSignal - PlayServices

### ISSUE THREAD

**Issue by lucazin** [OneSignal/OneSignal-Android-SDK#860] opened 2019-10-08 15:41 UTC
**Description:**
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.google.android.gms:play-services-location:[10.2.1, 12.1.0).
Required by:
    project :br.com.oneplace > com.onesignal:OneSignal:3.10.3
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Failed to list versions for com.google.android.gms:play-services-location.
Caused by: org.gradle.api.resources.ResourceException: Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/com/google/android/gms/play-services-location/maven-metadata.xml.

When i build i get this error here.
How can i fix that ?

**Environment**
1. What version of the Android SDK are you using?  - 9.0

2. How did you add the SDK to your project (eg. maven) 

With this
 implementation 'com.onesignal:OneSignal:3.10.3'
 -->

**Steps to Reproduce Issue:**
Trying to build

**Comment by rgomezp** [comment] 2019-10-09 22:44
Duplicate of #858

**Closed by rgomezp** 2019-10-09 22:44 UTC
Labels: Help Wanted
