### ISSUE TITLE
java.lang.IllegalArgumentException: No such service ComponentInfo{in.my.app/com.onesignal.RestoreKickoffJobService}

### ISSUE THREAD

**Issue by rameshvoltella** [OneSignal/OneSignal-Android-SDK#815] opened 2019-07-30 06:18 UTC
Hi,
i updated onesignal to 3.11.1 and updated my app yesterday when i check my bug list i saw a crash
**java.lang.IllegalArgumentException: No such service ComponentInfo{in.my.app/com.onesignal.RestoreKickoffJobService}**

Full stack trace

 

>    android.os.Parcel.readException Parcel.java:2009
>     android.os.Parcel.readException Parcel.java:1951
>     android.app.job.IJobScheduler$Stub$Proxy.schedule IJobScheduler.java:180
>     android.app.JobSchedulerImpl.schedule JobSchedulerImpl.java:44
>     com.onesignal.Y.c
>     com.onesignal.UpgradeReceiver.onReceive
>     android.app.ActivityThread.handleReceiver ActivityThread.java:3236
>     android.app.ActivityThread.-wrap17
>     android.app.ActivityThread$H.handleMessage ActivityThread.java:1696
>     android.os.Handler.dispatchMessage Handler.java:106
>     android.os.Looper.loop Looper.java:164
>     android.app.ActivityThread.main ActivityThread.java:6545
>     java.lang.reflect.Method.invoke Method.java
>     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:438
>     com.android.internal.os.ZygoteInit.main ZygoteInit.java:857

 Device found - Lava Z61
 SDK - Android 8.1 (SDK 27)
Crash only seen in lava device
The lava device is making a major crash for onesignal sdk, please look this more seriously or add restriction for lava users. i had done a restriction for lava users based on issue #753 but still this issue comes for lava users.

i use the following method when there was bug in oppo device #487 until u guys found a fix [oppo fix](https://github.com/OneSignal/OneSignal-Android-SDK/issues/487#issuecomment-378800887)

 ```
 if (!(Build.MANUFACTURER.equalsIgnoreCase("LAVA"))||!   ("lava".equalsIgnoreCase(manufacturer))||!(manufacturer.toLowerCase().contains("lava"))) {
Log.d("log","not a lava user excecute onesignal");
}
else
{
Log.d("log",
```"this is lava users");
}

Can you tell me whats wrong with the above code,i am restricting lava users to minimize crash using above code still i am seeing bugs in onesignal from lava users.

**Comment by rgomezp** [comment] 2019-07-30 20:48
Duplicate of #814

**Closed by rgomezp** 2019-07-30 20:48 UTC
