### ISSUE TITLE
Couldn't expand RemoteViews for: StatusBarNotification on Android 7.1

### ISSUE THREAD

**Issue by lyc12345** [OneSignal/OneSignal-Android-SDK#712] opened 2019-02-20 04:36 UTC
**Description:**
Hi,
It looks like same issue as #263 , but I see this issue on Android 7.1 too.

```
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package mb32u.music.player.free.download: Couldn't expand RemoteViews for: StatusBarNotification(pkg=mb32u.music.player.free.download user=UserHandle{0} id=-1798508724 tag=null key=0|mb32u.music.player.free.download|-1798508724|null|10259: Notification(pri=0 contentView=mb32u.music.player.free.download/0x7f0c00c6 vibrate=null sound=null defaults=0x0 flags=0x18 color=0x00000000 backgroundColor=0x00000000 vis=PUBLIC))
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6351)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
```

**Environment**
Android SDK: 28
OneginalSDK: 3.10.3
Integrated Onesignal sdk using build.gradle (android studio)

**Anything else:**

Crashlytics links:

http://crashes.to/s/ebe27bc7ad4
http://crashes.to/s/e75a18da2c8
It is not only happened on LGE and motorola. 
Crashlytics divide this into many issues.

**Comment by janbolat** [comment] 2019-03-08 02:49
Same here.
Seems updating to OneSignal 3.10.3 doesn't help.
Support library: 28.0.0
Details: https://github.com/OneSignal/OneSignal-Android-SDK/issues/263#issuecomment-470618788

**Comment by janbolat** [comment] 2019-03-08 11:40
@jkasten2 android 7 is crashing on latest release. Any ideas?

**Comment by jkasten2** [comment] 2019-03-08 23:54
@lyc12345 Thanks for sharing the stack traces. You noted that crashlytics is splitting up the issues up, overall how my crashes are you seeing with this error? What percentage of your users? Are you only seeing Android 7.1 and 7.0 crashes?

@janbolat We haven't see a large number of "Bad notification posted" since the OneSignal SDK 3.9.1 release. The issue is related to a bug in Android 7.0 and seems Google mostly fixed in 7.1, based on crash reports we have seen in issue #263.

To work around bug in Android 7.0 we omitted restoring notifications back to the shade when the app is upgraded since the crash reports where spiking when an app was updated. This is the PR of the work around for details>
https://github.com/OneSignal/OneSignal-Android-SDK/pull/544

I also have a write up in this comment with more technical details;
https://github.com/OneSignal/OneSignal-Android-SDK/issues/263#issuecomment-348664720

@janbolat Could you verify that you don't have any other plugin or code in your app that is creating notifications? Since the "Bad notification posted" is thrown from the system process instead of the app it isn't possible to know what Notification API call throw the error.
If you have the stack trace and full error however this will still give us some more details on properties set so please share those if you can.

Lastly the key thing here is we have never been able to reproduce this crash with our SDK on our devices. If you can provide exact steps on reproducing I am sure we can find a way to prevent this error.

**Comment by janbolat** [comment] 2019-03-10 01:12
@jkasten2 
No other plugins. It crashes as soon as I send a message from OneSignal web interface.
Steps to reproduce:
Target SDK: 26
Support Library: 28.0.0
implementation 'com.google.firebase:firebase-messaging:17.3.4'
implementation 'com.google.firebase:firebase-core:16.0.7'
implementation 'com.onesignal:OneSignal:3.10.6'
Device: Android Emulator x86 Android 7.1.1 (API 25) (Pixel with Google Play). It is the latest release of Android emulator 7.1.1 (downloaded yesterday).
Message body: 
`<html><head> <meta charset='utf-8'> <meta http-equiv='Content-Type' content='text/html; charset=utf-8' /> <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" /></head><body> <div style='margin:0 auto;text-align:center;font-family:Arial,Tahoma,sans-serif;font-size:14px;'> <div> <a href='https://www.instagram.com/p/Butk41pFlEI/'> <img style='max-width: 100%; width:auto; height: auto;' src='https://pp.userapi.com/c850536/v850536645/d080a/nbveysuqD2A.jpg' /> </a> </div> <div style="text-align: center; max-width: 640px; margin: 0 auto;padding:0 20px;"> <p>test</p> </div> <div style='margin:25px 10px 0px;color:#777;font-size:12px;'>Поделиться:</div></div></body></html>`

The only log is:
`2019-03-10 06:26:15.092 10757-10757/mypackage E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mypackage, PID: 10757
    android.app.RemoteServiceException: Bad notification posted from package mypackage: Couldn't expand RemoteViews for: StatusBarNotification(pkg=package user=UserHandle{0} id=1850385390 tag=null key=0|mypackage|1850385390|null|10085: Notification(pri=2 contentView=null vibrate=default sound=default tick defaults=0x7 flags=0x11 color=0xff20a476 category=msg vis=PUBLIC))
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`
Then it keeps crashing when you start the app again and again.

I used to send HTML messages without any problems (but target SDK was 22), now I updated to 26.

**Comment by jkasten2** [comment] 2019-03-10 01:57
@janbolat I tried your message body on the same Android 7.1.1 emulator setup as you had without any issues. Can you confirm this is the exact HTML snip-it you are entering in the "Message" field on the OneSignal dashboard? Also were any other notification options set?
It might be something else in your project that it a missing key piece. Could you reproduce the issue in a new project and share it?

Is there a specific reason your using HTML in the body? Android won't parse it, it will just display as is on a device. Do you have something else processing a notification before it is displayed? Such as the `NotificationExtenderService`.

**Comment by janbolat** [comment] 2019-03-10 02:08
@jkasten2 That is the exact message I send. 
I have an extender service:
`
package com.raimbekov.android.sajde;

import android.os.Build;
import android.support.v4.app.NotificationCompat;
import android.support.v4.content.ContextCompat;
import android.text.Html;
import android.util.Log;
import com.onesignal.NotificationExtenderService;
import com.onesignal.OSNotificationDisplayedResult;
import com.onesignal.OSNotificationPayload;
import com.onesignal.OSNotificationReceivedResult;
import com.raimbekov.android.sajde.models.HijriDate;
import org.json.JSONException;

public class GcmNotificationExtenderService extends NotificationExtenderService
{
    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult)
    {
        final OSNotificationPayload payload = receivedResult.payload;

        if (payload.additionalData != null)
        {
            if (payload.additionalData.has("getNewHijriDate"))
            {
                try {
                    if (payload.additionalData.getString("getNewHijriDate").equals("1"))
                    {
                        Log.d(App.TAG, "push received, get new hijri date");
                        HijriDate._deleteHijriDate();
                        return true;
                    }
                } catch (JSONException e)
                {}
            }
        }

        OverrideSettings overrideSettings = new OverrideSettings();
        overrideSettings.extender = new NotificationCompat.Extender() {
            @Override
            public NotificationCompat.Builder extend(NotificationCompat.Builder builder)
            {
                String title = payload.title;
                String text = payload.body;

                title = title.replace("<br>", " ").replace("<br/>", " ");
                text = text.replace("<br>", " ").replace("<br/>", " ").replaceAll("(?i)<img.*?>", "");

                CharSequence contextTitle = Html.fromHtml(title);
                CharSequence contextText = Html.fromHtml(text);

                // https://developer.android.com/training/notify-user/expanded.html
                NotificationCompat.BigTextStyle style = new NotificationCompat.BigTextStyle();
                style.setBigContentTitle(contextTitle).bigText(contextText);

                return builder
                        .setChannelId(AlarmNotification.CHANNEL_MESSAGES_ID)
                        .setColor(ContextCompat.getColor(App.getAppContext(), R.color.logo_color)) // Sets the background notification color to on Android 5.0+ devices.
                        .setSmallIcon(R.drawable.ic_stat_logo) // notification bar'dagy icon (ex: message icon)
                        .setBadgeIconType(NotificationCompat.BADGE_ICON_SMALL)
                        .setContentText(contextText)   // OneSignal content
                        .setStyle(style)
                        .setTicker(contextText)         // ustinde notification kelgende jugirip turatyn text
                        .setContentTitle(contextTitle) // OneSignal title
                        .setVisibility(NotificationCompat.VISIBILITY_PUBLIC) // > API 21
                        .setPriority(NotificationCompat.PRIORITY_MAX)
                        .setCategory(NotificationCompat.CATEGORY_MESSAGE);
            }
        };
        OSNotificationDisplayedResult displayedResult = displayNotification(overrideSettings);
        return false;
    }
}
`

**Comment by jkasten2** [comment] 2019-03-10 02:26
@janbolat I tested with your message body but I am getting a `null` error with your code on this line.
```java
title = title.replace("<br>", " ").replace("<br/>", " ");
```

```
2019-03-09 18:20:52.162 9216-9581/com.example.testonesignal W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference
2019-03-09 18:20:52.162 9216-9581/com.example.testonesignal W/System.err:     at com.example.testonesignal.GcmNotificationExtenderService$1.extend(GcmNotificationExtenderService.java:40)
```

The issue however is most likely in your `R.drawable.ic_stat_logo` or `R.color.logo_color` not being valid. Any resource you add to the notifications can throw the `Bad notification` error if isn't isn't valid.

**Comment by janbolat** [comment] 2019-03-10 02:33
@jkasten2 
I commented out `setColor` and `setSmallIcon`, but no luck. The problem is in `setContextText`.
I think I will add a code for 7.0 and 7.1 that won't display the text as html.

**Comment by jkasten2** [comment] 2019-03-10 03:40
@janbolat I was able to reproduce the crash with your `NotificationExtenderService` code with just the following HTML.
```html
<p style="text-align: center;">test</p>
```
It works fine by creating a normal
```java
Spannable spannableText = new SpannableString("test");
spannableText .setSpan(new AlignmentSpan.Standard(Layout.Alignment.ALIGN_CENTER), 0, 0, 0);
```

Seems something that `Html.fromHtml(...)` is doing that isn't generating the same settings.

**Comment by janbolat** [comment] 2019-03-10 06:42
@jkasten2 Thank you. I will check it

**Comment by jkasten2** [comment] 2019-03-19 20:07
@lyc12345 Closing due to inactivity. Please provide the details I noted in [my comment](#issuecomment-471239178) above as we can look into the issue.

**Closed by jkasten2** 2019-03-19 20:07 UTC
Labels: Needs More Details
