### ISSUE TITLE
[Bug]:  Fatal Exception: java.lang.NoSuchMethodError: No static method

### ISSUE THREAD

**Issue by RK-AndroidDev** [OneSignal/OneSignal-Android-SDK#2173] opened 2024-08-10 02:57 UTC
### What happened?

Application crashed
Here is the stack trace
```
Fatal Exception: java.lang.NoSuchMethodError: No static method post$default(Lcom/onesignal/core/internal/http/IHttpClient;Ljava/lang/String;Lorg/json/JSONObject;Ljava/lang/String;Lkotlin/coroutines/Continuation;ILjava/lang/Object;)Ljava/lang/Object; in class Lcom/onesignal/core/internal/http/IHttpClient$a; or its super classes (declaration of 'com.onesignal.core.internal.http.IHttpClient$a' appears in /data/app/~~X9n0-S_j2dInKUqnbUXMIA==/-s0hsn5miYp_gWr3CsXrazg==/base.apk!classes2.dex)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsBackendService.sendOutcomeEvent(OutcomeEventsBackendService.kt:49)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsController.requestMeasureOutcomeEvent(OutcomeEventsController.kt:319)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsController.sendSavedOutcomeEvent(OutcomeEventsController.kt:74)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsController.sendSavedOutcomes(OutcomeEventsController.kt:68)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsController.access$requestMeasureOutcomeEvent(OutcomeEventsController.kt:22)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsController.access$sendSavedOutcomes(OutcomeEventsController.kt:22)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsController$sendSavedOutcomes$1.invokeSuspend(OutcomeEventsController.kt:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:85)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__Builders.kt:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(Builders.kt:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__Builders.kt:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(Builders.kt:1)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:69)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:67)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)``
```
### Steps to reproduce?

```Markdown
This crash event happened in the first second of the user's session.
```

### What did you expect to happen?

Application should not crash.

### OneSignal Android SDK version

5.1.19

### Android version

14, 13, 12, 11, 10, 9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment] 2024-08-10 04:46
Hi @RK-AndroidDev thank you for reporting this.

Is this a reproducible crash happening 100% of the time?

This looks to be a code shrinking, obfuscation, and optimisation issue, did you make any changes to your Proguard or R8 configuration?

**Comment by PrakashGelani** [comment] 2024-08-10 07:18
@nan-li @RK-AndroidDev This is the Same issue with our project also we got 1000+ crashes from yesterday so please solve the issue ASAP from your side

> Fatal Exception: java.lang.NoSuchMethodError: No static method post$default(Lcom/onesignal/core/internal/http/IHttpClient;Ljava/lang/String;Lorg/json/JSONObject;Ljava/lang/String;Lkotlin/coroutines/Continuation;ILjava/lang/Object;)Ljava/lang/Object; in class LX9/b; or its super classes (declaration of 'X9.b' appears in base.apk)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsBackendService.sendOutcomeEvent(OutcomeEventsBackendService.kt:49)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsController.requestMeasureOutcomeEvent(OutcomeEventsController.kt:319)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsController.sendSavedOutcomeEvent(OutcomeEventsController.kt:74)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsController.sendSavedOutcomes(OutcomeEventsController.kt:68)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsController.access$requestMeasureOutcomeEvent(OutcomeEventsController.kt:22)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsController.access$sendSavedOutcomes(OutcomeEventsController.kt:22)
       at com.onesignal.session.internal.outcomes.impl.OutcomeEventsController$sendSavedOutcomes$1.invokeSuspend(OutcomeEventsController.kt:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:95)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__Builders.kt:69)
       at kotlinx.coroutines.BuildersKt.runBlocking(Builders.kt:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__Builders.kt:48)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(Builders.kt:1)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:69)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:67)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by Hiren879** [comment] 2024-08-10 07:37
We're facing the exact same issue, 1000+ crash since yesterday. Happening in less than 1 second.but issue is not happening in older versions.

**Comment by nan-li** [comment] 2024-08-10 08:06
I recommend you downgrade the SDK to 5.1.18.

Do you use code shrinking, obfuscation, and optimisation through R8 / Proguard etc?

**Comment by PrakashGelani** [comment] 2024-08-10 08:42
Used below gradle which provided in one signal document
`implementation 'com.onesignal:OneSignal:[5.0.0, 5.99.99]'`

And as I know 4 day ago some issue fixed from one signal and updated the SDK version.
Also we released our app new version 2 days ago so might issue when we generate build with your new fixes version.
Right @nan-li ?

**Comment by RK-AndroidDev** [comment] 2024-08-10 10:45
> Hi @RK-AndroidDev thank you for reporting this.
> 
> Is this a reproducible crash happening 100% of the time?
> 
> This looks to be a code shrinking, obfuscation, and optimisation issue, did you make any changes to your Proguard or R8 configuration?

I am unsure whether this can be reproducible since we got these crash details from Crashlytics and the count has reached more than 700+ crash events.

And we didn't make any changes to Proguard recently.

**Comment by nan-li** [comment] 2024-08-10 15:02
We are looking into this, in the meantime, the quickest fix is to roll back your OneSignal SDK to 5.1.18.

**Comment by RK-AndroidDev** [comment] 2024-08-12 07:21
@nan-li  any update on the fix ?

**Comment by michael-winkler** [comment] 2024-08-12 18:19
Since v5 there is on each new release a new bug.
Version 4 was much more stable..

I really loved OneSignal but a rollback after each time is not good.

**Comment by jinliu9508** [comment] 2024-08-13 00:03
@RK-AndroidDev @Hiren879 @PrakashGelani 
A [fix]((https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.20)) has now been released. We recommend upgrading to the latest SDK version or applying the following configuration: implementation 'com.onesignal:OneSignal:[5.0.0, 5.99.99]'.

We apologize for any inconvenience this may have caused and appreciate your continued feedback. Rest assured, we are committed to addressing any issues you encounter. Thank you for your support.

**Closed by jinliu9508** 2024-08-13 00:03 UTC
