### ISSUE TITLE
Crash on start my application.

### ISSUE THREAD

**Issue by e16din** [OneSignal/OneSignal-Android-SDK#257] opened 2017-06-27 07:11 UTC
HTC Desire 326G (Android 4.4.2) with Google Play.

Exception:
```
E/OneSignal: Could not register with GCM due to an error with the AndroidManifest.xml file or with 'Google Play services'.
                                                                       java.lang.RuntimeException: Package manager has died
                                                                           at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:81)
                                                                           at com.onesignal.PushRegistratorGPS.isGMSInstalledAndEnabled(PushRegistratorGPS.java:96)
                                                                           at com.onesignal.PushRegistratorGPS.internalRegisterForPush(PushRegistratorGPS.java:70)
                                                                           at com.onesignal.PushRegistratorGPS.registerForPush(PushRegistratorGPS.java:65)
                                                                           at com.onesignal.OneSignal.registerForPushToken(OneSignal.java:458)
                                                                           at com.onesignal.OneSignal.access$1600(OneSignal.java:67)
                                                                           at com.onesignal.OneSignal$3.onSuccess(OneSignal.java:527)
                                                                           at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:204)
                                                                           at java.lang.Thread.run(Thread.java:841)
```

**Comment by jkasten2** [comment] 2017-06-27 18:27
@e16din This looks to be a very rare exception due to either the version of the Google Play services library in your app, the Google Play services app on the device, the version of Android, or a number of plugin initializing with your app that are making IPC calls to other apps.

Are you able to reproduce this issue on your devices?

Please report which version of the Google Play services library (gms) is in your app and the "Google Play services" app on the device. Share your `build.gradle` if you can.

This is the same exception noted in issue #224.

**Comment by jkasten2** [comment] 2017-12-12 01:30
Closing to merge with issue #224

**Closed by jkasten2** 2017-12-12 01:30 UTC
Labels: duplicate, non-reproducible
