### ISSUE TITLE
SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode at NotificationOpenedProcessor.java line 69

### ISSUE THREAD

**Issue by DimaKoz** [OneSignal/OneSignal-Android-SDK#90] opened 2016-08-16 21:44 UTC
I got this [crashlog](https://github.com/OneSignal/OneSignal-Android-SDK/files/421328/log2.txt)
build.gradle:
```groovy
compile 'com.onesignal:OneSignal:2.6.2@aar'
```
Devices info:
<img width="1122" alt="screen shot 2016-08-17 at 0 43 44" src="https://cloud.githubusercontent.com/assets/3092276/17716936/16a2f764-641c-11e6-8e44-33e71caae5d4.png">

**Comment by jkasten2** [comment] 2016-08-16 22:03
@DimaKoz Duplicate of #45.

**Closed by jkasten2** 2016-08-16 22:03 UTC
