### ISSUE TITLE
Fatal Exception: java.util.concurrent.TimeoutException android.content.res.AssetManager$AssetInputStream.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by xabixa** [OneSignal/OneSignal-Android-SDK#662] opened 2018-11-08 09:26 UTC
**Description:**
Hi, I am trying to debug this crash that I get on my app. 
I cannot find a way to reproduce the crash consistently.
The crash may be caused by an opened stream.
After looking at the source code, I noticed that in the class
```com.onesignal.GenerateNotification.java``` (line 825) ,
an inputstream is opened by ```currentContext.getAssets().open(bitmapStr)``` but never closed
Could that be the root issue of the crash?
What do you think? 

```java
private static Bitmap getBitmapFromAssetsOrResourceName(String bitmapStr) {
      try {
         Bitmap bitmap = null;

         try {
            // HERE
            bitmap = BitmapFactory.decodeStream(currentContext.getAssets().open(bitmapStr));
         } catch (Throwable t) {}

         if (bitmap != null)
            return bitmap;

         final List<String> image_extensions = Arrays.asList(".png", ".webp", ".jpg", ".gif", ".bmp");
         for (String extension : image_extensions) {
            try {
               // AND HERE
               bitmap = BitmapFactory.decodeStream(currentContext.getAssets().open(bitmapStr + extension));
            } catch (Throwable t) {}
            if (bitmap != null)
               return bitmap;
         }

         int bitmapId = getResourceIcon(bitmapStr);
         if (bitmapId != 0)
            return BitmapFactory.decodeResource(contextResources, bitmapId);
      } catch (Throwable t) {}

      return null
}
```

**Environment**
implementation 'com.onesignal:OneSignal:[3.7.1, 3.99.99]'

**Anything else:**

> https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java

Crash report:
`Fatal Exception: java.util.concurrent.TimeoutException: android.content.res.AssetManager$AssetInputStream.finalize() timed out after 10 seconds
       at android.content.res.AssetManager$AssetInputStream.close(AssetManager.java:622)
       at android.content.res.AssetManager$AssetInputStream.finalize(AssetManager.java:655)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:217)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:200)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by jkasten2** [comment] 2018-11-09 01:36
@xabixa Thanks for the stack trace. It looks like Android is trying to close any opened assets automatically with it's own background daemon thread. We have received any other reports of this crash so the only case I could see this maybe being an issue is sending notifications with large images.

Can you provide a step-by-step of reproducing the issue? Even if it is inconsistent for you.

Let us know which versions of Android and device models you are seeing the issue on.

**Comment by xabixa** [comment] 2018-11-09 05:37
I'm not able to reproduce the crash unfortunately. From the crash reports, it looks like it happens only for samsung device running Android 6.
Example: Galaxy J7 running Android 6.0.1

Again, it's hard to say from the stack trace where the crash comes from.
I still think it's a good idea to close the Input streams after decoding anyway.

From the source code of BitmapFactory.java [https://android.googlesource.com/platform/frameworks/base/+/master/graphics/java/android/graphics/BitmapFactory.java](url) , I can see that the input stream is closed after being decoded. I suggest to close the inputstreams in a similar way inside com.onesignal.GenerateNotification.java
```java
    public static Bitmap decodeFile(String pathName, Options opts) {
        validate(opts);
        Bitmap bm = null;
        InputStream stream = null;
        try {
            stream = new FileInputStream(pathName);
            bm = decodeStream(stream, null, opts);
        } catch (Exception e) {
            /*  do nothing.
                If the exception happened on open, bm will be null.
            */
            Log.e("BitmapFactory", "Unable to decode stream: " + e);
        } finally {
            if (stream != null) {
                try {
                    stream.close();
                } catch (IOException e) {
                    // do nothing here
                }
            }
        }
        return bm;
    }
```

**Comment by j2emanue** [comment] 2018-11-09 07:19
can you guys just close the stream ?

**Comment by rgomezp** [comment] 2019-04-03 00:26
Closing issue. Note: request still under consideration

**Closed by rgomezp** 2019-04-03 00:26 UTC
Labels: Improvement
