### ISSUE TITLE
NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by janbolat** [OneSignal/OneSignal-Android-SDK#1121] opened 2020-08-21 06:24 UTC
* OneSignal:3.15.2
* firebase-messaging:20.2.4
* play-services-location:17.0.0

Very rare crash not related to OneSignal library, but it would be better to handle it (try/catch maybe).

**Android 8.1, Xiaomi Redmi Go**

```
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at java.util.Formatter$FormatSpecifier.addZeros(Formatter.java:3505)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:3401)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:3332)
       at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2893)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:2844)
       at java.util.Formatter.format(Formatter.java:2523)
       at java.util.Formatter.format(Formatter.java:2458)
       at java.lang.String.format(String.java:2770)
       at android.location.Location.toString(Location.java:1032)
       at java.lang.String.valueOf(String.java:2827)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at com.onesignal.GMSLocationController$GoogleApiClientListener.onConnected(GMSLocationController.java:132)
       at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionSuccess(GmsClientEventManager.java:33)
       at com.google.android.gms.common.api.internal.zaaw.zab(zaaw.java:292)
       at com.google.android.gms.common.api.internal.zaak.zaaq(zaak.java:125)
       at com.google.android.gms.common.api.internal.zaak.onConnected(zaak.java:105)
       at com.google.android.gms.common.api.internal.zabe.onConnected(zabe.java:101)
       at com.google.android.gms.common.api.internal.zaq.onConnected(zaq.java:6)
       at com.google.android.gms.common.internal.zaf.onConnected(zaf.java:2)
       at com.google.android.gms.common.internal.BaseGmsClient$zzf.zzm(BaseGmsClient.java:24)
       at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(BaseGmsClient.java:12)
       at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(BaseGmsClient.java:11)
       at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(BaseGmsClient.java:49)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at com.google.android.gms.internal.common.zze.dispatchMessage(zze.java:8)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by Jeasmine** [comment] 2020-10-06 17:43
Hey @janbolat thanks for the feedback, how often are you seeing this error? how many users are being affected? We will add some logs for better catching under this.

**Comment by janbolat** [comment] 2020-10-13 03:26
![image](https://user-images.githubusercontent.com/6511056/95811851-f339a080-0d35-11eb-9eb3-40a3d504377e.png)
Not so much:
96% Android 8
4% Android 4

Thanks

**Comment by jkasten2** [comment] 2021-03-12 07:22
@janbolat Based on the stacktrace this looks like a bug with Android itself trying to format the location with `android.location.Location.toString`. It possible `play-services-location` could be creating a location instance that is initialized with bad data. I checked Google's release notes but don't see anything in version 17.1.0 or 18.0.0 noting this:
https://developers.google.com/android/guides/releases

I agree with you @janbolat that the best next steps is for this SDK to add a try-catch around all instances where `location.toString()` would be called. Possibly creating an internal helper method such as `safeLocationToString` with a note to this issue.

**Comment by chokokatana** [comment] 2021-06-21 08:24
Got one crash from a Galaxy Note9 user with Android 8.1.0, app using `[4.4.0, 4.99.99]`:
```
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at java.util.Formatter$FormatSpecifier.addZeros(Formatter.java:3505)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:3401)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:3332)
       at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2893)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:2844)
       at java.util.Formatter.format(Formatter.java:2523)
       at java.util.Formatter.format(Formatter.java:2458)
       at java.lang.String.format(String.java:2770)
       at android.location.Location.toString(Location.java:1032)
       at java.lang.String.valueOf(String.java:2827)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at com.onesignal.GMSLocationController$GoogleApiClientListener.onConnected(GMSLocationController.java:136)
       at com.google.android.gms.common.internal.zah.zaa(zah.java:30)
       at com.google.android.gms.common.api.internal.zaar.zaa(zaar.java:295)
       at com.google.android.gms.common.api.internal.zaaf.zaf(zaaf.java:130)
       at com.google.android.gms.common.api.internal.zaaf.zaa(zaaf.java:108)
       at com.google.android.gms.common.api.internal.zaaz.onConnected(zaaz.java:105)
       at com.google.android.gms.common.api.internal.zaq.onConnected(zaq.java:5)
       at com.google.android.gms.common.internal.zag.onConnected(zag.java:2)
       at com.google.android.gms.common.internal.BaseGmsClient$zzf.zza(BaseGmsClient.java:24)
       at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(BaseGmsClient.java:12)
       at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzc(BaseGmsClient.java:11)
       at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(BaseGmsClient.java:49)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by nan-li** [comment] 2022-02-01 18:49
Hi @janbolat, are you still seeing this issue?

Hi @chokokatana, can you give details about how many devices and which versions are experiencing this issue, other than the one device you mentioned? Can you reproduce?

**Comment by chokokatana** [comment] 2022-02-02 08:10
> Hi @chokokatana, can you give details about how many devices and which versions are experiencing this issue, other than the one device you mentioned? Can you reproduce?

No currently active crashes, reproduction impossible.

**Comment by nan-li** [comment] 2022-02-23 00:31
Since this is a rare crash, and we're not seeing more reports of it, I will close this issue.

If anything changes, we can re-open the issue in the future.

**Closed by nan-li** 2022-02-23 00:31 UTC
Labels: Improvement

**Comment by rekire** [comment] 2022-07-26 06:54
FYI: Not fully related, but I see that exception sometimes in my own app. I just found this by googeling the stacktrace
