### ISSUE TITLE
[Bug]: java.util.concurrent.RejectedExecutionException 

### ISSUE THREAD

**Issue by rw-exxeta** [OneSignal/OneSignal-Android-SDK#1738] opened 2023-02-23 08:50 UTC
### What happened?

We received two crash reports regarding this exception. I see you already fixed a crash related to this exception, however this might be another place where the crash can happen, but it's pretty rare, but worth to have a look. 
[https://github.com/OneSignal/OneSignal-Android-SDK/issues/669](https://github.com/OneSignal/OneSignal-Android-SDK/issues/669)

### Steps to reproduce?

```Markdown
we received the crash report, sadly we couldn't reproduce it.
```

### What did you expect to happen?

the app doesn't crash

### OneSignal Android SDK version

Release 4.8.4

### Android version

13

### Specific Android models

```Markdown
* Samsung Galaxy Note20 Ultra 5G (SM-N986B)
* Samsung Galaxy S20 (SM-G980F)
```

### Relevant log output

```Shell
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@f6db105[Not completed] rejected from java.util.concurrent.ThreadPoolExecutor@c82155a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
	 at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2072)
	 at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:834)
	 at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1364)
	 at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	 at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:671)
	 at com.onesignal.OSTaskController.startPendingTasks(OSTaskController.java:65)
	 at com.onesignal.OneSignal.init(OneSignal.java:164)
	 at com.onesignal.OneSignal.setAppId(OneSignal.java:87)
	 at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:61)
	 at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:0)
	 at com.onesignal.OneSignal$7.complete(OneSignal.java:29)
	 at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:10)
	 at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:0)
	 at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:2)
	 at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:4)
	 at java.lang.Thread.run(Thread.java:1012)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment] 2023-02-23 15:57
Looks like this line [here](https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.8.4/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSTaskController.java#L92).

Note this is not an issue in [v5.0.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.0-beta2) which is currently in beta.  Marking as a bug and to determine whether to fix in 4.x releases.

**Comment by mrRedSun** [comment] 2023-07-18 11:01
I received the same issue in Crashlytics, but haven't been able to reproduce it.

**Closed** 2024-10-24 20:52 UTC
Labels: Bug, Player Model
