### ISSUE TITLE
App is Crashing on Firebase ID issue

### ISSUE THREAD

**Issue by vinitmobile** [OneSignal/OneSignal-Android-SDK#552] opened 2018-05-23 07:38 UTC
**Description:**

My App with oneSignal was working fine.  Just 4 days ago my app is started crashing on building from android studio on Launch whereas it is working perfectly fine on play store.

Here is the crash I am getting -
```java
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
        at com.google.firebase.iid.FirebaseInstanceIdService.zza(Unknown Source)
        at com.google.firebase.iid.FirebaseInstanceIdService.handleIntent(Unknown Source)
```
**Environment**
1. Android SDK 7.0
2. Onesignal dependency in app
com.onesignal:OneSignal:3.+@aar
3. Google Play Services Version
com.google.android.gms:play-services:10.2.6
4.Android Support lib
com.android.support:appcompat-v7:25.2.0

**Comment by black-8** [comment] 2018-05-23 14:26
I just updated oneSignal and getting the same error only in the very first launch

play services 15.0.2
OneSignal:[3.9.1, 3.99.99)'

**Comment by jkasten2** [comment] 2018-05-25 07:58
@vinitmobile @black-8 Looks like this happening due to this Firebase class only using the default Firebase app configured. OneSignal initializes it's own FirebaseApp so this won't interfere with a possible existing FirebaseApp already configured as so the senderId can be used from OneSignal's setting instead of requiring or pull it from your project's `google-services.json`.

We will be looking into what OneSignal can do to fix this error in the next update. In the mean time however adding the `google-services.json` from your [Firebase console](https://console.firebase.google.com/) to your project will fix this crash. This can be do from Project Settings > General. You will need to add an Android app here if you don't have one already.
![image](https://user-images.githubusercontent.com/645861/40533097-7ab58cf2-5fb6-11e8-8db1-19fb274a32d0.png)

Then follow their step by step guide of where to place the `google-services.json` file.

**Comment by juliancorrea** [comment] 2018-06-30 12:14
This didn't  worked for me.

Stack trace:

`06-30 09:11:23.334 29748-30190/br.com.jcs.torktransportes.torkapp E/AndroidRuntime: FATAL EXCEPTION: pool-7-thread-1
                                                                                    Process: br.com.jcs.torktransportes.torkapp, PID: 29748
                                                                                    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process br.com.jcs.torktransportes.torkapp. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                        at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
                                                                                        at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
                                                                                        at com.google.firebase.iid.FirebaseInstanceIdService.zza(Unknown Source)
                                                                                        at com.google.firebase.iid.FirebaseInstanceIdService.handleIntent(Unknown Source)
                                                                                        at com.google.firebase.iid.zzb$1.run(Unknown Source)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                        at java.lang.Thread.run(Thread.java:761)
06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: Rejecting re-init on previously-failed class java.lang.Class<com.onesignal.OneSignalChromeTab$OneSignalCustomTabsServiceConnection>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsServiceConnection;
06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art:     at void com.onesignal.OneSignalChromeTab.setup(android.content.Context, java.lang.String, java.lang.String, java.lang.String) (OneSignalChromeTab.java:46)
06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art:     at void com.onesignal.OneSignal$7.run() (OneSignal.java:1164)
06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art:     at void java.lang.Thread.run() (Thread.java:761)
06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.customtabs.CustomTabsServiceConnection" on path: DexPathList[[zip file "/data/app/br.com.jcs.torktransportes.torkapp-1/base.apk"],nativeLibraryDirectories=[/data/app/br.com.jcs.torktransportes.torkapp-1/lib/arm, /data/app/br.com.jcs.torktransportes.torkapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art:     at void com.onesignal.OneSignalChromeTab.setup(android.content.Context, java.lang.String, java.lang.String, java.lang.String) (OneSignalChromeTab.java:46)
06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art:     at void com.onesignal.OneSignal$7.run() (OneSignal.java:1164)
06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art:     at void java.lang.Thread.run() (Thread.java:761)`

**Comment by juliancorrea** [comment] 2018-06-30 12:15
This didn't worked for me.

Stack trace:

06-30 09:11:23.334 29748-30190/br.com.jcs.torktransportes.torkapp E/AndroidRuntime: FATAL EXCEPTION: pool-7-thread-1 Process: br.com.jcs........, PID: 29748 java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process br.com.jcs.torktransportes.torkapp. Make sure to call FirebaseApp.initializeApp(Context) first. at com.google.firebase.FirebaseApp.getInstance(Unknown Source) at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source) at com.google.firebase.iid.FirebaseInstanceIdService.zza(Unknown Source) at com.google.firebase.iid.FirebaseInstanceIdService.handleIntent(Unknown Source) at com.google.firebase.iid.zzb$1.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) at java.lang.Thread.run(Thread.java:761) 06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: Rejecting re-init on previously-failed class java.lang.Class<com.onesignal.OneSignalChromeTab$OneSignalCustomTabsServiceConnection>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsServiceConnection; 06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: at void com.onesignal.OneSignalChromeTab.setup(android.content.Context, java.lang.String, java.lang.String, java.lang.String) (OneSignalChromeTab.java:46) 06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: at void com.onesignal.OneSignal$7.run() (OneSignal.java:1164) 06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: at void java.lang.Thread.run() (Thread.java:761) 06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.customtabs.CustomTabsServiceConnection" on path: DexPathList[[zip file "/data/app/br.com.jcs.torktransportes.torkapp-1/base.apk"],nativeLibraryDirectories=[/data/app/br.com.jcs.torktransportes.torkapp-1/lib/arm, /data/app/br.com.jcs.torktransportes.torkapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]] 06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56) 06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380) 06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312) 06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: at void com.onesignal.OneSignalChromeTab.setup(android.content.Context, java.lang.String, java.lang.String, java.lang.String) (OneSignalChromeTab.java:46) 06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: at void com.onesignal.OneSignal$7.run() (OneSignal.java:1164) 06-30 09:11:23.516 29748-30189/br.com.jcs.torktransportes.torkapp I/art: at void java.lang.Thread.run() (Thread.java:761)

**Comment by black-8** [comment] 2018-06-30 12:42
@juliancorrea Me neither 
@jkasten2  One month past and I'm still waiting for the next update :/
ps 3.9.2 didn't fix this

**Comment by jkasten2** [comment] 2018-06-30 17:46
@juliancorrea @black-8 I missed that the next step after adding the `google-services.json` file is important. Adding the Google Play service Gradle plugin noted below.

![image](https://user-images.githubusercontent.com/645861/42127680-e9fad290-7c51-11e8-9d6e-03d48c5e031a.png)
**Project-level build.gradle (<project>/build.gradle):**
```
buildscript {
  dependencies {
    // Add this line
    classpath 'com.google.gms:google-services:4.0.0'
  }
}
```

**App-level build.gradle (<project>/<app-module>/build.gradle):**
```
// Add to the bottom of the file
apply plugin: 'com.google.gms.google-services'
```


We will still be working on a fix so these steps won't be required in the future

**Comment by juliancorrea** [comment] 2018-07-01 01:37
Thks @jkasten2 but now I'm facing this:

`Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/geektime/rnonesignalandroid/BuildConfig;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/geektime/rnonesignalandroid/BuildConfig;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:506)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:336)
        at com.android.dx.command.dexer.Main.runDx(Main.java:291)
        at com.android.dx.command.dexer.Main.main(Main.java:247)
        at com.android.dx.command.Main.main(Main.java:94)`

Can u help me? Have u seen this?

**Comment by black-8** [comment] 2018-07-01 11:20
@jkasten2 tnx for follow up
I missed the apply plugin: 'com.google.gms.google-services' part :/

**Closed** 2018-07-03 00:31 UTC
Labels: Compatibility

**Comment by jkasten2** [comment] 2018-07-03 00:32
Removed this requirement in the PR above, this will be included in the next release
