### ISSUE TITLE
[Bug]: Crash ModelStore.persist java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by chokokatana** [OneSignal/OneSignal-Android-SDK#1894] opened 2023-11-03 08:48 UTC
### What happened?

Received a crashes after upgrading to 5.0.3.

### Steps to reproduce?

```Markdown
Upgrade to 5.0.3 from 4.8.6.
```

### What did you expect to happen?

No crashes.

### OneSignal Android SDK version

5.0.3

### Android version

10

### Specific Android models

```Markdown
* Galaxy S9 Android 10.
```

### Relevant log output

```Shell
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.onesignal.common.modeling.ModelStore.persist(ModelStore.kt:140)
       at com.onesignal.common.modeling.ModelStore.addItem(ModelStore.kt:108)
       at com.onesignal.common.modeling.ModelStore.addItem$default(ModelStore.kt:98)
       at com.onesignal.common.modeling.ModelStore.add(ModelStore.kt:46)
       at com.onesignal.common.modeling.IModelStore$DefaultImpls.add$default(IModelStore.kt:37)
       at com.onesignal.core.internal.operations.impl.OperationRepo.internalEnqueue(OperationRepo.kt:76)
       at com.onesignal.core.internal.operations.impl.OperationRepo.enqueueAndWait(OperationRepo.kt:68)
       at com.onesignal.internal.OneSignalImp$login$2.invokeSuspend(OneSignalImp.kt:299)
       at com.onesignal.internal.OneSignalImp$login$2.invoke(OneSignalImp.kt:1)
       at com.onesignal.internal.OneSignalImp$login$2.invoke(OneSignalImp.kt:2)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1$1.invokeSuspend(ThreadUtils.kt:61)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:85)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__Builders.kt:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(Builders.kt:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__Builders.kt:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(Builders.kt:1)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:60)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:59)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Threads.kt:30)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment] 2023-11-03 21:08
Thank you for reporting I apologize for the inconvenience. I am closing this as a duplicate of #1857 . There is a PR with a fix for this that will be available with the next release!

**Closed by emawby** 2023-11-03 21:08 UTC
Labels: Duplicate
