### ISSUE TITLE
Crash : com.onesignal.OneSignalCacheCleaner$2.run (OneSignalCacheCleaner.java:116)

### ISSUE THREAD

**Issue by mahmoudElfeel67** [OneSignal/OneSignal-Android-SDK#1046] opened 2020-06-07 05:46 UTC
**Description:**
2 Crashes with version 3.14.0 and also the previous version

(your description here)

**Environment**

**Steps to Reproduce Issue:**

i dont know how to reproduce

**Anything else:**

`
```

Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'boolean android.database.Cursor.isClosed()' on a null object reference
com.onesignal.OneSignalCacheCleaner$2.run (OneSignalCacheCleaner.java:116)

```

`
Fatal Exception: android.database.sqlite.SQLiteException
no such table: cached_unique_outcome (code 1 SQLITE_ERROR[1]): , while compiling: DELETE FROM cached_unique_outcome WHERE NOT EXISTS(SELECT NULL FROM notification n WHERE n.notification_id = channel_influence_id AND channel_type = "notification")
android.database.sqlite.SQLiteConnection.nativePrepareStatement (SQLiteConnection.java)
android.database.sqlite.SQLiteDatabase.delete (SQLiteDatabase.java:2047)
com.onesignal.OneSignalCacheCleaner.cleanCachedUniqueOutcomeEventNotifications (OneSignalCacheCleaner.java:167)
`

**Comment by rgomezp** [comment] 2020-06-08 21:58
Duplicate of #1040

**Closed by rgomezp** 2020-06-08 21:58 UTC
