### ISSUE TITLE
java.lang.NullPointerException:    at com.onesignal.aw.V (OneSignal.java:1286)   at com.onesignal.aw.A (OneSignal.java:77)   at com.onesignal.aw$14.run (OneSignal.java:1254)   at java.lang.Thread.run (Thread.java:764)

### ISSUE THREAD

**Issue by annamalaicoderays** [OneSignal/OneSignal-Android-SDK#810] opened 2019-07-22 10:37 UTC
I am getting this error only on production build. i can't able to reproduce in development environment.
```
java.lang.NullPointerException: 
  at com.onesignal.aw.V (OneSignal.java:1286)
  at com.onesignal.aw.A (OneSignal.java:77)
  at com.onesignal.aw$14.run (OneSignal.java:1254)
  at java.lang.Thread.run (Thread.java:764)

```
app level build.gradle
```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.2, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28

    defaultConfig {
        applicationId "com.example.app"
        minSdkVersion 17
        targetSdkVersion 28
        manifestPlaceholders = [manifestApplicationId: "${applicationId}",
                             
                                onesignal_google_project_number: "REMOTE"]

        multiDexEnabled true
        resConfigs "en"
    }

    buildTypes {

        debug{
            debuggable true
            minifyEnabled false
            resValue("string", "PORT_NUMBER", "8081")
        }
        release {
            debuggable false
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
        }
    }
    dexOptions {
        javaMaxHeapSize "4g"
            jumboMode = true

    }


    repositories {
        google()
        jcenter()
        maven { url "https://s3.amazonaws.com/moat-sdk-builds" }
        maven { url 'https://maven.google.com' }

        maven { url 'https://jitpack.io' }

        mavenCentral()
    }

    useLibrary  'org.apache.http.legacy'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

dependencies {


    implementation fileTree(dir: 'libs', include: ['*.jar'])

  
    compileOnly 'org.jbundle.util.osgi.wrapped:org.jbundle.util.osgi.wrapped.org.apache.http.client:4.1.2'

    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:preference-v7:28.0.0'
    implementation 'com.android.support:customtabs:28.0.0'
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    implementation 'com.android.volley:volley:1.1.1'
    implementation 'com.onesignal:OneSignal:[3.10.9, 3.99.99]'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.android.exoplayer:exoplayer:2.6.1'
    implementation 'com.google.firebase:firebase-messaging:18.0.0'
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.google.firebase:firebase-auth:17.0.0'
    implementation 'com.google.firebase:firebase-database:17.0.0'
    implementation 'com.google.android.libraries.places:places:1.1.0'
    implementation 'com.google.android.gms:play-services-location:16.0.0'
    implementation 'com.google.android.gms:play-services-basement:16.2.0'
    implementation 'com.google.android.gms:play-services-auth:16.0.1'
    implementation 'com.google.android.ads.consent:consent-library:1.0.7'
    implementation 'com.android.billingclient:billing:1.1'
    implementation 'com.google.android:flexbox:0.3.2'

}
apply plugin: 'com.google.gms.google-services'
```

project level build.gradle

```
buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.google.com' }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.1.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.google.com' }
    }
}
```

**Comment by rgomezp** [comment] 2019-07-22 22:03
Howdy,
What version of the SDK are you using?

**Comment by annamalaicoderays** [comment] 2019-07-23 04:37
@rgomezp 
i am using onesignal version 3.10.9
implementation 'com.onesignal:OneSignal:[3.10.9, 3.99.99]'

**Comment by jkasten2** [comment] 2019-07-23 05:24
@annamalaicoderays Thanks for checking, it seems the line numbers in your stack trace don't line up with that version either. Can you confirm the crash isn't from an older version of your app where you may have had an other version of the OneSignal SDK?

If not you may need to use retrace to provide a more complete stack trace.
https://www.guardsquare.com/en/products/proguard/manual/retrace

**Comment by rgomezp** [comment] 2019-07-23 18:41
Duplicate of #800 

Please continue discussion in that thread

**Closed** 2019-07-23 18:41 UTC
Labels: Possible Bug
