### ISSUE TITLE
[Bug]: canRequestPermission function always returns true

### ISSUE THREAD

**Issue by ngoni** [OneSignal/OneSignal-Android-SDK#1792] opened 2023-08-02 14:10 UTC
### What happened?

When calling the below function on v5.0.0-beta4, the function always returns `true`, even if the device has been prompted for push notification permission (which is contrary to the [documentation](https://documentation.onesignal.com/v11.0/docs/mobile-sdk#checking-if-a-permissions-prompt-will-be-displayed)). 

`val canRequest: Boolean = OneSignal.Notifications.canRequestPermission`

### Steps to reproduce?

```Markdown
1. Install v5.0.0-beta4 SDK
2. Ensure this is a new installation of your application on a device with Android 13+
3. Call the following function: `OneSignal.Notifications.canRequestPermission`
4. You'll notice Step 3, return `true` and then proceed to request for Push Notifications Permission. Allow the application the required permission.
5. Execute Step 3 again, you'll notice the function still returns `true`, but based on the documentation this should return `false`
```

### What did you expect to happen?

When I make a call to the below code, after the device has already been prompted for push notifications permission the function should return `false`

`val canRequest: Boolean = OneSignal.Notifications.canRequestPermission`

### OneSignal Android SDK version

Release 5.0.0-beta4

### Android version

13

### Specific Android models

```Markdown
Android Studio Emulator on Android 13
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment] 2023-08-04 21:26
Hi @ngoni thanks for reaching out! We'll attempt to reproduce this and get back to you as soon as possible.

**Comment by jennantilla** [comment] 2023-08-22 19:36
@ngoni just an update that this has been fixed in our [latest major release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.0). 

Please let us know if you have any additional questions or concerns!

**Closed by jennantilla** 2023-08-22 19:36 UTC

**Comment by hls-app** [comment] 2024-07-18 02:27
@jennantilla looks like this came back. Using `onesignal_flutter: "^5.2.2"` and getting always true on Android 34 Pixel 7 Emulator. Don't have access to other Android phones at the moment.
