### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by robsonbbs** [OneSignal/OneSignal-Android-SDK#921] opened 2020-01-09 16:46 UTC
**Description:**

I found this ANR log on my production APP:

**Environment**
Now I am using SDK 3.12.2 via maven

**Steps to Reproduce Issue:**

I don't know how to reproduce this.

**Anything else:**

ANR stack trace:

> "main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x739666a0 self=0xb1c84400
  | sysTid=14159 nice=-10 cgrp=default sched=0/0 handle=0xb4977534
  | state=S schedstat=( 77667167229 85926873561 204624 ) utm=6378 stm=1387 core=0 HZ=100
  | stack=0xbe296000-0xbe298000 stackSize=8MB
  | held mutexes=
  at com.onesignal.LocationGMS.onFocusChange (LocationGMS.java:293)
waiting to lock <0x05fe8b4b> (a com.onesignal.LocationGMS$1) held by thread 71
  at com.onesignal.OneSignal.onAppFocus (OneSignal.java:1226)
  at com.onesignal.ActivityLifecycleHandler.handleFocus (ActivityLifecycleHandler.java:206)
  at com.onesignal.ActivityLifecycleHandler.onActivityResumed (ActivityLifecycleHandler.java:120)
  at com.onesignal.ActivityLifecycleListener.onActivityResumed (ActivityLifecycleListener.java:78)
  at android.app.Application.dispatchActivityResumed (Application.java:216)
  at android.app.Activity.onResume (Activity.java:1255)
  at androidx.fragment.app.FragmentActivity.onResume (FragmentActivity.java:514)
  at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1291)
  at android.app.Activity.performResume (Activity.java:6791)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3427)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3490)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1540)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6165)
  at java.lang.reflect.Method.invoke! (Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:888)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:778)

**Comment by robsonbbs** [comment] 2020-01-09 16:50
Duplicated of #898

**Comment by rgomezp** [comment] 2020-01-15 21:59
Duplicate of #719

**Closed by rgomezp** 2020-01-15 21:59 UTC
