### ISSUE TITLE
[Bug]: Crash ThreadUtilsKt$suspendifyOnThread$1.invoke java.lang.NullPointerException - null cannot be cast to non-null type kotlin.String

### ISSUE THREAD

**Issue by chokokatana** [OneSignal/OneSignal-Android-SDK#1897] opened 2023-11-03 08:55 UTC
### What happened?

Got new random crashes.

### Steps to reproduce?

```Markdown
Upgrade from 4.8.6 to 5.0.3.
```

### What did you expect to happen?

No crashes.

### OneSignal Android SDK version

5.0.3

### Android version

13

### Specific Android models

```Markdown
* Oppo Find X5 Pro Android 13
* Samsung Galaxy A14 5G Android 13
```

### Relevant log output

```Shell
Fatal Exception: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:60)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:59)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Threads.kt:30)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment] 2023-11-03 21:10
Closing as duplicate of #1871 
This is fixed in pr https://github.com/OneSignal/OneSignal-Android-SDK/pull/1886 and will be available in the next release

**Closed by emawby** 2023-11-03 21:10 UTC
