### ISSUE TITLE
[Bug]: kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation

### ISSUE THREAD

**Issue by Sardorbekcyber** [OneSignal/OneSignal-Android-SDK#2019] opened 2024-03-07 12:16 UTC
### What happened?

For my app I am getting error on OneSignal from Crashlytics

### Steps to reproduce?

```Markdown
Not sure how to reproduce this as I am getting it from alerts
```

### What did you expect to happen?

No crashes from OneSignal

### OneSignal Android SDK version

Release 5.1.1

### Android version

9

### Specific Android models

```Markdown
Samsung Galaxy Note 8
```

### Relevant log output

```Shell
Fatal Exception: kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[BlockingEventLoop@1cb3cac, Continuation at com.onesignal.core.internal.operations.impl.OperationRepo$processQueueForever$3.invokeSuspend(OperationRepo.kt:141)@546bf1]){Cancelled}@a3b93d6. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
       at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:146)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:117)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(:1)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$2.invoke(ThreadUtils.kt:91)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$2.invoke(ThreadUtils.kt:89)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment] 2024-03-07 22:53
@Sardorbekcyber Thanks for reporting. Do you get any other details in Crashlytics such as a "Caused by:" section?
* I researched this and found other crash reports with the `kotlinx.coroutines` library [normally contain "Caused by:"](https://github.com/Kotlin/kotlinx.coroutines/issues/2221#issuecomment-684522369).

What percentage users / devices effected and number of crashes?
* Is the crash only happening on that single device Samsung Galaxy Note 8 running Android 9?


Can you try updating to the latest OneSignal-Android-SDK (currently 5.1.6)?

Also OneSignal uses `kotlinx-coroutines` 1.6.4, it's possible they fixed this in a newer version. Can you try adding this to your `build.gradle` / `build.kts` to upgrade that library?
```
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4")
```

**Comment by Sardorbekcyber** [comment] 2024-03-11 08:35
Do you get any other details in Crashlytics such as a "Caused by:" section? - Yes below is what is caused by

Caused by java.lang.OutOfMemoryError

What percentage users / devices effected and number of crashes? - Only single user rught now

Can you try updating to the latest OneSignal-Android-SDK (currently 5.1.6)? - Yeap I will be updating both OneSignal and KotlinX Coroutines. But It turns out issue was not in libraries anyway but OutOfMemory Exception

**Comment by jkasten2** [comment] 2024-03-11 17:24
@Sardorbekcyber Thanks for the details. The `Caused by java.lang.OutOfMemoryError` section should also have it's own stack trace. Can you include that, as well any other parts of that stacktrace so we can get the full stack?

**Comment by jinliu9508** [comment] 2024-10-31 20:47
Closing this issue as there are no further updates. If anyone is still experiencing this issue, please try upgrading to the latest SDK and open a new issue if the problem persists after upgrading.

**Closed by jinliu9508** 2024-10-31 20:47 UTC
