### ISSUE TITLE
App does not open on notification click if killed

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [OneSignal/OneSignal-Android-SDK#781] opened 2019-06-17 12:26 UTC
**Description:**

Same problem reported in #779 but I'll add some results I've found when trying to fix it.

When my app is killed, if I click on a notification it doesn't launch the app. It just does nothing. This happens on a OnePlus 5T.

Important: to reproduce the issue I must set "Limit background processes" to "No background processes" in the developer settings and kill the app.

Note: I've tried with *and* without setting any ADDITIONAL DATA fields on the OneSignal dashboard and I don't see any difference.

**Environment**

SDK version: 3.10.7
SDK gradle plugin: 0.12.1
Note that I've had to explicitly add `com.google.firebase:firebase-messaging:18.0.0` to fix #754

**Steps to Reproduce Issue:**

1. Go to the developer settings and set "Limit background processes" to "No background processes
2. Kill the app
3. Send notification from OneSignal dashboard
4. Click the notification.

Result: app doesn't open.

**Anything else:**

I've been trying different things and I've ended up with this `NotificationExtenderService`:

```
private const val LET_ONESIGNAL_SHOW_NOTIFICATION: Boolean = false

class OneSignalNotificationExtenderService : NotificationExtenderService() {

    override fun onNotificationProcessing(result: OSNotificationReceivedResult): Boolean {
         if (LET_ONESIGNAL_SHOW_NOTIFICATION) {
            return false
        } else {
            showNotification(result)
            // Return true to stop the notification from displaying.
            return true
        }
    }

    private fun showNotification(result: OSNotificationReceivedResult) {
        val payload = JSONObject(result.payload.rawPayload)
        val channelPayload = payload.getString("chnl")
        val channelId = JSONObject(channelPayload).getString("id")
        Timber.d("OneSignal channelPayload $channelPayload channelId $channelId")

        val intent = Intent(this, MainActivity::class.java).apply {
            flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
        }
        val pendingIntent: PendingIntent = PendingIntent.getActivity(this, 0, intent, 0)

        val builder = NotificationCompat.Builder(this, channelId)
            .setSmallIcon(R.drawable.ic_stat_onesignal_default)
            .setContentTitle(result.payload.title)
            .setContentText(result.payload.body)
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
            // Set the intent that will fire when the user taps the notification
            .setContentIntent(pendingIntent)
            .setAutoCancel(true)

        with(NotificationManagerCompat.from(this)) {
            // notificationId is a unique int for each notification that you must define
            notify(22, builder.build())
        }
    }

}
```

When `LET_ONESIGNAL_SHOW_NOTIFICATION` is `false` I show the notification myself and the app works fine (ie. the app opens when I click the notification). However when `LET_ONESIGNAL_SHOW_NOTIFICATION`  is `true` the app doesn't work properly (ie. clicking on the notification does nothing).

I don't know how do you show the notification in the SDK but would be nice if you could take a look an make it work when the app is killed.

**Comment by mikechoch** [comment] 2019-06-21 21:29
I followed your steps to reproduce and I am not seeing this issue, I am using a Samsung S8+

**I did this exact process:**
1. "Limit background processes" to "No background processes" and t
2. Kill app
3. Send notif from dash
4. Receive and click notif
5. App opens 

I will try performing on other devices now and get back to you.

**Comment by cirogg** [comment] 2019-06-24 13:05
> I followed your steps to reproduce and I am not seeing this issue, I am using a Samsung S8+
> 
> **I did this exact process:**
> 
> 1. "Limit background processes" to "No background processes"
> 2. Kill app
> 3. Send notif from dash
> 4. Receive and click notif
> 5. App opens
> 
> I will try performing on other devices now and get back to you.

Hi mike. I have my code in an issue with the same problem that we have here. link: [https://github.com/OneSignal/OneSignal-Android-SDK/issues/779](url)

Maybe you can find what is wrong because for me is everything right.

**Comment by AlbertVilaCalvo** [comment] 2019-06-25 10:04
@mikechoch this happens to me with a OnePlus, which has severe background process limits. From https://dontkillmyapp.com/oneplus

> OnePlus introduced one of the most severe background limits on the market to date

Note that even with this particular characteristics, to manually trigger the issue I must set "Limit background processes" to "No background processes" in the developer settings. Killing the app is not enough. From my observation, the app has to be killed for some time to experience the issue. For example, when I wake up after 8 hours of sleep with the app closed, if I click on a notification the app doesn't open. But since I can't force this, I end up using the developer option.

**Comment by rgomezp** [comment] 2019-07-08 23:29
Duplicate of #779

**Closed by rgomezp** 2019-07-08 23:29 UTC
Labels: Question

**Comment by sanjeet007** [comment] 2021-07-22 13:38
Oh mam still no one answers

**Comment by j-ixcayau** [comment] 2021-12-10 18:13
I'm having the same issue for Android with Flutter, on iOS everything works fine
