### ISSUE TITLE
Attempt to invoke virtual method 'void com.onesignal.p1.q()' on a null object reference

### ISSUE THREAD

**Issue by ankitchaudhary** [OneSignal/OneSignal-Android-SDK#1413] opened 2021-08-16 09:28 UTC
**Description:**

 Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onesignal.p1.q()' on a null object reference
       at com.onesignal.OneSignal.init(OneSignal.java)
       at com.onesignal.OneSignal.setAppId(OneSignal.java)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java)
       at com.onesignal.OneSignal$5.complete(OneSignal.java)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java)
       at java.lang.Thread.run(Thread.java:762)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by emawby** [comment] 2021-08-16 16:21
@ankitchaudhary Thank you for reporting this issue. If possible could you please provide more context for this issue? Are you able to reproduce the issue and if not are you getting this stacktrace through an error reporting tool?

**Comment by VladMurz** [comment] 2021-08-20 09:17
I am having the same issue. I can't reproduce this crash while debugging the app. The stacktrace is obtained through an error reporting tool. One signal version: `4.4.1`, plugin:  `classpath gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.13.4'`, target SDK version: `30`

**Comment by jkasten2** [comment] 2021-09-28 18:30
@VladMurz Can you reproduce the issue on your device when you have obfuscation enabled? Or not at all and these are all reports from your users?
Could you provide your root `build.gradle and your `app/build.gradle` as well as the full obfuscation settings you are using?

Based on stack trace you provided it looks like it is calling a method that is void and takes no parameters so looks like would be one of these two lines for reference:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/68d6305143a7640f5be8e07a4a6bc7f1357046fa/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L838-L841

**Comment by nan-li** [comment] 2022-05-11 21:01
Hi @ankitchaudhary and @VladMurz,

I am following up on this issue. Before, jkasten2 had pointed out two places that could be the culprit.

Looking at this stack trace again, it looks like the same crash as reported in https://github.com/OneSignal/OneSignal-Android-SDK/issues/1374 and https://github.com/OneSignal/OneSignal-Android-SDK/issues/1514, which were getting a null pointer exception on `outcomeEventsController.sendSavedOutcomes()`. 

The fix for that crash has been released in [version 4.7.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.7.1). 

I will close this issue for now, please upgrade and comment if you are still experiencing crashes.

**Closed by nan-li** 2022-05-11 21:01 UTC
Labels: Needs More Information

**Comment by VladMurz** [comment] 2022-08-01 12:19
Hello @nan-li I have updated te library to version 4.7.1, but the issue is still reproducible. 

`implementation group: 'com.onesignal', name: 'OneSignal', version: '4.7.1'`

`apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'`

`classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.13.4'`

With no special proguard rules for OneSignal.
