### ISSUE TITLE
Users not resubscribed after deleting in dashboard

### ISSUE THREAD

**Issue by thavelka** [OneSignal/OneSignal-Android-SDK#877] opened 2019-10-24 19:02 UTC
**Description:**

I deleted a player from the dashboard, then force closed and reopened the app to ensure that the player would be resubscribed. The user did not get resubscribed and a 400 error was logged in logcat. The player does not appear in the dashboard and the device does not receive notifications.

Some things I've tried:
* Reinstalling the app does fix the issue and allow the device to be resubscribed.
* The "clear data" button in app settings does allow the device to be resubscribed.
* The "clear cache" button in app settings does not fix the issue.
* Restarting the device does not fix the issue.

EDIT: This appears to happen with our iOS app as well.

**Environment**

* Device: Nexus 6P with Android 8.1.0
* Project details:
  * MinSDK version 21
  * Target and Compile SDK version 28
  * Gradle version 5.1.1
  * Android Gradle plugin version 3.4.1
* OneSignal Dependencies:
  * OneSignal Gradle plugin version 0.12.6
  * OneSignal Android SDK version 3.11.4

**Steps to Reproduce Issue:**

1. Open android app and allow player to be subscribed
2. Set external id on user using `OneSignal.setExternalUserId`
3. Close app
4. Open OneSignal dashboard on web and delete player
5. Open android app again
6. Player is not resubscribed and error is logged in console.

**Anything else:**

Error in logcat shown when opening the app and when trying to set external id each time the app syncs user data with server:
```
W/OneSignal: OneSignalRestClient: POST RECEIVED JSON: {"errors":["Player not found. Request body did not contain a device_type field, so a new player could not be automatically created."]}
W/OneSignal: Failed last request. statusCode: 400
    response: null
```
Also this error sometimes:
```
W/OneSignal: OneSignalRestClient: PUT RECEIVED JSON: {"errors":["No user with this id found"]}
W/OneSignal: Failed last request. statusCode: 400
    response: null
```

**Comment by alexshikov** [comment] 2019-11-05 11:40
I have the same issue. Is that something random users may theoretically get into?

**Comment by jkasten2** [comment] 2019-11-06 05:50
@thavelka Thanks for reporting the issue. We are working on a fix to have the SDK create a new player if it is deleted from the OneSignal dashboard in the next release.

**Comment by zoro238** [comment] 2019-11-13 12:39
pls how solve?

**Comment by zoro238** [comment] 2019-11-14 05:04
> 
> 
> @thavelka Thanks for reporting the issue. We are working on a fix to have the SDK create a new player if it is deleted from the OneSignal dashboard in the next release.

how slove ?

**Comment by jkasten2** [comment] 2019-11-23 21:59
@thavelka @alexshikov @zoro238 
This is now fixed in the [3.12.3 release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.12.3) that went out Nov. 21.

**Closed by jkasten2** 2019-11-23 21:59 UTC
Labels: Bug: Medium Priority, Reproducible

**Comment by zoro238** [comment] 2019-11-28 22:27
> 
> 
> @thavelka @alexshikov @zoro238
> This is now fixed in the [3.12.3 release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.12.3) that went out Nov. 21.

ok i am tested very ok

**Comment by ggallotti** [comment] 2019-12-03 13:43
Same problem here.
@thavelka have you reported this issue for the iOS SDK ?

**Comment by danielerota** [comment] 2020-01-07 09:58
Same issue with Javascript sdk

**Comment by A-Tokyo** [comment] 2020-02-18 03:45
Same Problem, React Native

@jkasten2 Can we maybe fast track this? Can I help somehow?

**Comment by jkasten2** [comment] 2020-02-18 04:20
@A-Tokyo Make sure you have [react-native-onesignal@3.6.1](https://github.com/OneSignal/react-native-onesignal/releases/tag/3.6.1) or newer since this version included 3.12.4 of this native SDK with the fix noted here.

**Comment by A-Tokyo** [comment] 2020-02-18 12:38
@jkasten2 Double checked, 100% sure i am using https://github.com/OneSignal/react-native-onesignal/releases/tag/3.6.1

**Comment by jkasten2** [comment] 2020-02-19 05:15
@A-Tokyo Can you provide the exact steps in producing the issue along with a logcat with OneSignal.setLogLevel to VERBOSE? 
https://documentation.onesignal.com/docs/react-native-sdk#section-set-log-level

I recommend opening a new issues in the react-native-onesignal if the logcat does not help so your reply doesn't get lost in this closed issue.

**Comment by Lucisu** [comment] 2020-05-06 03:05
Hello! I'm having the same problem. 
When removing a user through the OneSignal dashboard, it is no longer possible to add the same method as before (using the sample code from the JS library). In console, error code 400 to request "PUT https://onesignal.com/api/v1/players/..." appears.

Device: Android 10; MI A3 Xiaomi
Browser: Chrome 81.0.40044.117

**Comment by Nihilem** [comment] 2020-05-09 14:17
Same problem with xamarin sdk

**Comment by dmitry** [comment] 2021-03-25 17:56
You can go to IndexedDB and delete `ONE_SIGNAL_SDK_DB`.

**Comment by brownAddict** [comment] 2021-03-31 17:36
flutter android sdk still has this problem. After uninstalling and installing, it resubscribed.

**Comment by lexin** [comment] 2024-06-19 08:57
It's still reproducible in 2024. We use iOS sdk.

**Comment by jkasten2** [comment] 2024-07-09 22:30
@lexin This repo is only for Android issues, and is very old. Please open a new ticket on the iOS repo instead:
https://github.com/OneSignal/OneSignal-iOS-SDK/issues

**Comment by SirukakSosta** [comment] 2024-09-18 09:44
Using Web push it seems to happen again.
In order to avoid these issues please follow the next flows.

1. Do not manual remove on production. Export subscriptions to have a backup.
2. For local development. Open chrome application and remove everything regarding onesignal. It seems it keep something in session or in local Db that prevent the resubsciption.
