### ISSUE TITLE
[3.10.2] Issue with FirebaseApp not initialized

### ISSUE THREAD

**Issue by xcaEi** [OneSignal/OneSignal-Android-SDK#681] opened 2018-12-07 08:03 UTC
**Description:**

I launched a new app recently and haven't had a problem until last night for one specific user who encountered the issue about 10 times yesterday and today. 

As I don't use Firebase in my application, I think this might be the Firebase App created by OneSignal. However as it has only happened to one specific user, I think the issue might be with linked to his device.

**Environment**
One Signal SDK : 3.10.2 
Play Services : 11.0.4
Android Support lib :  27.1.1

**User Device** : Teclast P10 (p10_m3f5_g in Google Play Console) on Android 7.1.2

**Steps to Reproduce Issue:**

I am guessing just launching the application but I have no information. 

**Anything else:**

java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.jsl_prod.presse. Make sure to call FirebaseApp.initializeApp(Context) first.
at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
at com.google.firebase.iid.FirebaseInstanceIdService.zza(Unknown Source) 
at com.google.firebase.iid.FirebaseInstanceIdService.handleIntent(Unknown Source) 
	at com.google.firebase.iid.zzc.run(Unknown Source) 	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 	
at java.lang.Thread.run(Thread.java:761)

**Comment by jkasten2** [comment] 2018-12-07 19:36
@xcaEi Thanks for the report, this seems to be the same as issue #552, it should have been fixed in the 3.9.3 release however.

It is possible there could be some edge case here. Since it is just one device it could be some issue with it. I'll leave this issue open for a bit incase others are seeing this issue, or if you see more occurrences or can reproduce this issue.

**Comment by jkasten2** [comment] 2019-01-09 00:17
@xcaEi We haven't seen any other reports of this issue so it seems the issue is just isolated to the single device. Let us know if you are seeing it with other device models and we can reopen this issue and check it out again. Thanks.

**Comment by cloudtenlabs** [comment] 2019-12-14 02:51
I have launched the app with onesignal3.10.2 but this issue is occurring repeatedly for the users who are using Samsung galaxy

**Comment by shefich** [comment] 2020-02-08 21:08
Hello,

I have the same issue, but now with the last SDK (3.12.6), more different device models have this issue:

Fatal Exception: java.lang.Error: FATAL EXCEPTION [firebase-iid-executor]
Unity version     : 2018.4.16f1
Device model      : HUAWEI DUA-L22
Device fingerprint: HONOR/DUA-L22RU/HWDUA-M:8.1.0/HONORDUA-L22/1.0.0.140(C10):user/release-keys

Caused by java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.company.name. Make sure to call FirebaseApp.initializeApp(Context) first.
       at com.google.firebase.FirebaseApp.getInstance + 240(com.google.firebase:firebase-common@@16.0.2:240)
       at com.google.firebase.iid.FirebaseInstanceId.getInstance + 1(:1)
       at com.google.firebase.iid.zzaw.zzg + 52(:52)
       at com.google.firebase.iid.FirebaseInstanceId.zzi + 60(:60)
       at com.google.firebase.iid.FirebaseInstanceId.zza + 147(:147)
       at com.google.firebase.iid.zzn.run + 10(:10)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1162(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 636(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run + 780(Thread.java:780)

UnityMain
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next + 366(MessageQueue.java:366)
       at android.os.Looper.loop + 144(Looper.java:144)
       at com.unity3d.player.UnityPlayer$e.run + 32(:32)


And here's list of devices:
samsung     17%
HUAWEI      15%
Prestigio     11%
HTC             8%
Other…        49%

**Comment by shefich** [comment] 2020-02-20 08:50
Hi @jkasten2 are you going to reopen the issue?

**Comment by itslenny** [comment] 2020-03-01 05:08
@shefich I created a new issue to make sure it gets attention. This is causing us serious business impact in production so I hope they / we figure it out soon.

**Comment by alexandreangeli** [comment] 2020-03-06 20:22
I'm having the same issue, except it's using OneSignal-Cordova-SDK.
<img width="972" alt="image" src="https://user-images.githubusercontent.com/42987856/76119778-e0f0ca80-5fce-11ea-9ee8-e12543444316.png">

**Comment by pankaj89** [comment] 2020-04-14 16:29
Hello, i am also facing the same issue on Pixel with OS 10.
I am using this
implementation 'com.onesignal:OneSignal:3.12.4'

Heres the log
```
E/OneSignal: Unknown error getting FCM Token
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.test.myapplication. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.2:240)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source:1)
        at com.google.firebase.iid.zzaw.<init>(Unknown Source:16)
        at com.google.firebase.iid.zzaw.<init>(Unknown Source:1)
        at com.google.firebase.iid.FirebaseInstanceId.<init>(Unknown Source:15)
        at com.google.firebase.iid.FirebaseInstanceId.<init>(Unknown Source:7)
        at com.google.firebase.iid.zzao.create(Unknown Source:3)
        at com.google.firebase.components.zzj.zza(com.google.firebase:firebase-common@@16.0.2:43)
        at com.google.firebase.components.zzk.get(Unknown Source:4)
        at com.google.firebase.components.zzj.get(com.google.firebase:firebase-common@@16.0.2:54)
        at com.google.firebase.components.zza.get(com.google.firebase:firebase-common@@16.0.2:26)
        at com.google.firebase.components.zzf.get(com.google.firebase:firebase-common@@16.0.2:34)
        at com.google.firebase.components.zzf.zza(com.google.firebase:firebase-common@@16.0.2:82)
        at com.google.firebase.FirebaseApp.zze(com.google.firebase:firebase-common@@16.0.2:761)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.2:359)
        at com.onesignal.PushRegistratorFCM.initFirebaseApp(PushRegistratorFCM.java:98)
        at com.onesignal.PushRegistratorFCM.getToken(PushRegistratorFCM.java:83)
        at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97)
        at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
        at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by rgomezp** [comment] 2020-04-29 21:04
Howdy everyone,
Please upgrade to the latest OneSignal SDK. Cheers

**Comment by Amiinexp** [comment] 2020-05-02 02:56
> I'm having the same issue, except it's using OneSignal-Cordova-SDK.
> <img alt="image" width="972" src="https://user-images.githubusercontent.com/42987856/76119778-e0f0ca80-5fce-11ea-9ee8-e12543444316.png">

I have the same issue, i'm using the latest Onesignal version, my app only crash in samsung & some huawei devices.

**Comment by Amiinexp** [comment] 2020-05-02 22:05
![Screen Shot 2020-05-02 at 5 08 29 PM](https://user-images.githubusercontent.com/23348701/80893312-c3836880-8cc0-11ea-85ea-99c977611e9c.png)

Here is a screenshot from Google console crash report, i can't reproduce the issue locally.

**Comment by rgomezp** [comment] 2020-05-04 18:53
Howdy!
We think that upgrading your OneSignal [Gradle Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues) will solve this issue. Can you please give it a shot?

**Comment by jkasten2** [comment] 2020-05-22 22:35
## Issue
Thanks for all the stacktraces. It seems all the recent crashes have this specific `firebase-common` version in them.
`com.google.firebase:firebase-common@@16.0.2`

I wasn't able to find any notes in Google's documentation about a bug like this but I would recommend updating to a newer version of firebase as Google may have fixed this.
https://firebase.google.com/support/release-notes/android

## Possible Fixes

### Option 1 (Recommend, if you meet the noted requirements)
If you have OneSignal 3.13.0+, Jetifier, and AndroidX in your project I recommend updating to the latest `firebase-messaging:20.1.7` library as it will in turn date you to the latest `firebase-common` version too.

```gradle
implementation 'com.google.firebase:firebase-messaging:20.1.7'
```

### Option 2
If you are using OneSignal 3.12.2+ version then you safely upgrade to `firebase-common:17.1.0`
```gradle
implementation 'com.google.firebase:firebase-common:17.1.0'
```

**Comment by jkasten2** [comment] 2020-07-07 20:56
Closing due to inactivity

**Closed by jkasten2** 2020-07-07 20:56 UTC
Labels: Compatibility Issue
