### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by nicktz9** [OneSignal/OneSignal-Android-SDK#850] opened 2019-10-03 09:50 UTC
I follow the documentation to setup one signal SDK(https://documentation.onesignal.com/docs/android-sdk-setup), but I got the issue below.
```
+--- com.onesignal:OneSignal:3.11.4
|    +--- com.google.firebase:firebase-messaging:[10.2.1, 12.1.0) -> 18.0.0
|    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 17.0.0 (*)
|    |    +--- com.google.android.gms:play-services-tasks:16.0.1 -> 17.0.0 (*)
|    |    +--- com.google.firebase:firebase-common:17.0.0 -> 19.0.0 (*)
|    |    +--- com.google.firebase:firebase-iid:[18.0.0] FAILED
|    |    \--- com.google.firebase:firebase-measurement-connector:17.0.1 -> 18.0.0 (*)
|    +--- com.google.android.gms:play-services-location:[10.2.1, 12.1.0) -> 15.0.1
|    |    +--- com.google.android.gms:play-services-base:[15.0.1,16.0.0) -> 17.0.0 (*)
|    |    +--- com.google.android.gms:play-services-basement:[15.0.1,16.0.0) FAILED
|    |    +--- com.google.android.gms:play-services-places-placereport:[15.0.1,16.0.0) -> 15.0.1
|    |    |    \--- com.google.android.gms:play-services-basement:[15.0.1,16.0.0) FAILED
|    |    \--- com.google.android.gms:play-services-tasks:[15.0.1,16.0.0) FAILED
|    +--- com.google.android.gms:play-services-base:[10.2.1, 12.1.0) -> 17.0.0 (*)
|    +--- androidx.legacy:legacy-support-v4:1.0.0 (*)
|    +--- androidx.browser:browser:1.0.0 -> 1.2.0-alpha08 (*)
|    \--- androidx.cardview:cardview:1.0.0 (*)
```

**Comment by dobrowins** [comment] 2019-10-08 12:20
Same here. It sometimes breaks build and then it's not. Failures happen due to Internal Server Error.

**Comment by rgomezp** [comment] 2019-10-09 22:21
Are you using the OneSignal Gradle plugin?

https://github.com/OneSignal/OneSignal-Gradle-Plugin

**Comment by kirilamenski** [comment] 2019-10-10 10:16
@nicktz9 
Perhaps this may be related https://github.com/OneSignal/OneSignal-Android-SDK/issues/858

**Comment by nicktz9** [comment] 2019-10-14 06:49
@rgomezp Yes, I already used the OneSignal Gradle plugin in my project but it still doesn't work.
@kirilamenski thanks, it works when I exclude the modules below. is there any potential issues?
```
  implementation('com.onesignal:OneSignal:3.11.2'){
        exclude group: 'com.google.android.gms', module: 'play-services-location'
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.firebase', module: 'firebase-iid'
        exclude group: 'com.google.firebase', module:'firebase-messaging'
    }
```

**Comment by rgomezp** [comment] 2019-10-15 01:23
Duplicate of #858

**Closed by rgomezp** 2019-10-15 01:23 UTC
Labels: Help Wanted
