### ISSUE TITLE
ANR Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11000010 pkg=com.bloomer.alaWad3k cmp=com.bloomer.alaWad3k/com.onesignal.FCMBroadcastReceiver (has extras) }

### ISSUE THREAD

**Issue by mahmoudElfeel67** [OneSignal/OneSignal-Android-SDK#1436] opened 2021-09-14 21:40 UTC
**Description:**
(We have massive ANR coming from this error in google console)

**Environment**
1. What version of the Android SDK are you using?  4.5.1
2. How did you add the SDK to your project (eg. maven) Maven

**Steps to Reproduce Issue:**

  1. Add the OneSignal SDK to your project 4.5.1
  2. Place your App ID in the application's gradle file  a4a5c56d-e19b-4b2a-a0af-af653115977d
  3. Attempt to receive a push notification

**Anything else:**

(crash stacktraces, as well as any other information here)
Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11000010 pkg=com.bloomer.alaWad3k cmp=com.bloomer.alaWad3k/com.onesignal.FCMBroadcastReceiver (has extras) }

**Comment by mahmoudElfeel67** [comment] 2021-11-30 20:00
@jkasten2  i have not seen the issue its reported in google play console A LOT and there is not stack trace

Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11000010 pkg=com.bloomer.alaWad3k cmp=com.bloomer.alaWad3k/com.onesignal.FCMBroadcastReceiver (has extras) }

**Comment by jkasten2** [comment] 2021-11-30 21:33
@mahmoudElfeel67 I believe there is an option somewhere in the Google Play console to download the full stacktrace for all threads as part of the ANR report. I don't know where this is located specifically on there site, however others have been able to provide them. Example: https://github.com/OneSignal/OneSignal-Android-SDK/issues/1487#issuecomment-978138002

**Comment by mahmoudElfeel67** [comment] 2021-11-30 21:36
@jkasten2  yes i know but for this one in particular it has not stack trace 
it has this comment in  the stack trace view "Stack trace not available"

**Comment by jkasten2** [comment] 2021-11-30 21:50
@mahmoudElfeel67 Without a stack trace it isn't possible to confirm this is a OneSignal issue (as the ANR compmont name only indicates how the process was started, not the root necessarily the root issue). Also the stack traces provides exactly where the app was at when it hit the 5 second android main thread limit.

Are you able to reproduce the issue on your devices? If so please provide a stack trace from your device.
If not I would recommend contacting Google to see if there is any way they can get the stack trace for you for your specific ANR.

**Comment by mahmoudElfeel67** [comment] 2021-12-05 19:19
@jkasten2 we cant get the anr trace from google 
but what we know is its from one signal 
and other users reported issues from onesignal related to anr as i see

there is also something weird it happens at random times we estimate it happens with receiving notifications
![Screen Shot 2021-12-05 at 9 16 09 PM](https://user-images.githubusercontent.com/51560958/144760357-ed4f8721-00ff-431a-85fc-e5d5296c2c65.png)


this is not the only anr we are getting from one signal and we are above the anr threshold because of that 
![Screen Shot 2021-12-05 at 9 15 33 PM](https://user-images.githubusercontent.com/51560958/144760374-f0bbcaf2-0158-45a4-8077-0c98f4b233f9.png)

there has to be a quick investigation to this as google punishes apps for anr and these anr dont only come from one app they come from 2 of our apps

**Comment by jkasten2** [comment] 2021-12-05 20:50
@mahmoudElfeel67 Thanks for the details, I think the next steps are to try to profile the performance of the app durning these startup events since we can't get a stack trace.

Can you try following Google's guide on ANRs?
   - https://developer.android.com/topic/performance/vitals/anr

They don't bring this up in their docs but one key thing to these ANRs you are seeing is what is being run from your `Application.onCreate`. If you can share you code from there we can help look into this as well.

We will also re-evaluate our SDK to ensure it is performant doing these events.

**Comment by nan-li** [comment] 2022-03-01 22:43
Hi @mahmoudElfeel67,

Do you have any updates on this issue? Were you able to try the [above comment](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1436#issuecomment-986297953) steps or if you're able to get a stack trace? 

Without a stack trace or steps to reproduce, there isn't enough information for us to investigate the issue well.

**Comment by nan-li** [comment] 2022-06-16 22:48
Without a stack trace or steps to reproduce, there isn't enough information for us to investigate this, or to figure out if it is OneSignal-related. The Broadcast of Intent ANR shows how the app's process is started but not the root cause of what is blocking the main thread.

See [this comment](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1542#issuecomment-1157958839) for an example of a similar ANR and the root cause is something else in the main thread.

Closing this issue. If more information/stack traces become available, we can re-open and investigate then.

**Closed by nan-li** 2022-06-16 22:48 UTC

**Comment by VeNOM4171** [comment] 2022-09-07 00:04
I have same issue. It is Flutter app. I have attached logcat. How can I solve this?
Flutter - 3.0.2
Dart - 2.17.3
Java JDK - 11.0.11

![image](https://user-images.githubusercontent.com/49753535/188760229-995ab3d1-c65b-44eb-b5d4-1dd8e8793791.png)
![image](https://user-images.githubusercontent.com/49753535/188760312-3204a52a-c7e9-47b8-a444-6312e9f31628.png)

[logcat.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/9501591/logcat.txt)

**Comment by nan-li** [comment] 2022-09-13 17:41
Hi @VeNOM4171,
Your ANR doesn't look like it is related to the OneSignal SDK.
