### ISSUE TITLE
`OneSignal.idsAvailable` callback has null registrationId while `OneSignal.getPermissionSubscriptionState().getSubscriptionStatus().getPushToken()` is not null.

### ISSUE THREAD

**Issue by runningcode** [OneSignal/OneSignal-Android-SDK#558] opened 2018-06-01 11:13 UTC
We're seeing an issue in production where after upgrading our client apps to OneSignal 3.9.1 and including FCM in our project, the `OneSignal.idsAvailable` callback sends a null `registrationId` (related to https://github.com/OneSignal/OneSignal-Android-SDK/issues/348).

We've added some investigative logging to track down this issue. We are seeing that at the same time that the `OneSignal.idsAvailable` callback is fired, `OneSignal.getPermissionSubscriptionState().getSubscriptionStatus().toString()` returns a json object with a userId and pushToken like so:

`{"userId":"<redacted>","pushToken":"<redacted>","userSubscriptionSetting":true,"subscribed":true}`

We have asked users to reinstall the app and they are still getting a null registrationId. We cannot reproduce this issue, but we have seen it happen to many clients.

**Comment by jkasten2** [comment] 2018-06-04 23:02
If `getPushToken()` has a value `idsAvailable()` may not always have a value. `idsAvailable` returns `null` if you called `OneSignal.setSubscription(false)` OR if the user disabled notifications for your app. The later was only changed in 3.5.0 when `addSubscriptionObserver` and `getPermissionSubscriptionState` was added.

**Comment by runningcode** [comment] 2018-06-05 09:20
If `OneSignal.setSubscription(false)` were set, wouldn't that mean that `subscribed` would be false in the json? Or if the user disabled notifications wouldn't that mean that `userSubscriptionSetting` would be false in the json?
Both those values are true as you can see from the redacted json I provided.

If both `userSubscription=true` and `subscribed=true` what is the case in which `registrationId` in the `idsAvailable` callback would return null but `OneSignal.getPermissionSubscriptionState().getSubscriptionStatus().pushToken()` would return a value?
What is the logic change that would cause this `registrationId` to be null in this case in the 3.9.1 version of OneSignal but not in the 3.8.4 version of OneSignal?

**Comment by jkasten2** [comment] 2018-06-07 21:34
@runningcode After digging into this I did find a case where `idsAvailable` isn't firing when it should. If the device registers with OneSignal without a `registrationId` then `idsAvailable` will fire once. Then once we get a push token from the GCM or FCM library and it is successfully sent to OneSignal `idsAvailable` should fire a 2nd time with `registrationId` set. However we discovered 2nd call is not happening in the latest 3.9.1 SDK after some testing.

The OneSignal SDK will try to wait for GCM or FCM to give your app a `pushToken` / `registrationId` before registering the device for a user / playerId. However OneSignal has a fallback if GCM or FCM does not responded in 30 seconds it will still register for an id. Normally this fallback won't happen so `idsAvailable` will normally just fire once and with both ids set. This case should only happen if the device is having networking issues.

Above is a PR to fix this issue. We have added a test for this case to prevent any future regression bugs. This will be included in the next SDK release

**Comment by runningcode** [comment] 2018-06-12 21:51
Thanks for the quick fix and a detailed explanation.
Has idsAvailable always been expected to fire twice?

**Comment by jkasten2** [comment] 2018-06-16 06:13
@runningcode `getPushToken()` shouldn't be returning a non-null value while `registrationId` is. I'll take another pass at looking at the source and trying to reproduce the issue you described.

**Comment by MacDegger** [comment] 2018-07-30 13:17
Just to mention that we also got hit with this issue (after an update to OneSignal?) Anyway, since we didn't really use the pushToken/registrationid and were only looking for the userid, we replaced the call with OneSignal.getPermissionSubscriptionState().getSubscriptionStatus().getUserID(), which we could use instead. 

We went from 3.8.4 to 3.9.3 btw and were using the lambda version OneSignal.idsAvailable((userId, registrationId) -> {}); which we replaced with the normal method call as seen above ...

**Comment by rgomezp** [comment] 2019-07-19 01:44
Closing since `idsAvailable` has been deprecated

**Closed by rgomezp** 2019-07-19 01:44 UTC
Labels: Bug: Medium Priority
