### ISSUE TITLE
Build Failed release after 3.12.2

### ISSUE THREAD

**Issue by sckn** [OneSignal/OneSignal-Android-SDK#882] opened 2019-10-29 20:34 UTC
This problem started to happen after version 3.12.2.
How can I find a solution?
or 
3.12.2 How do I fix it to the previous version?
Like a debian package pining.

**Description:**
ERROR: Failed to resolve: com.google.firebase:firebase-core:17.3.99
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: com.google.android.gms:play-services:17.3.99
Install Repository and sync project
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: com.google.firebase:firebase-messaging:17.3.99
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: com.google.android.gms:play-services-location:17.3.99
Install Repository and sync project
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: com.google.android.gms:play-services-ads-identifier:17.3.99
Install Repository and sync project
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: com.google.android.gms:play-services-base:17.3.99
Install Repository and sync project
Show in Project Structure dialog
Affected Modules: app

**Comment by sebastiant** [comment] 2019-10-31 16:12
possible duplicate: https://github.com/OneSignal/OneSignal-Android-SDK/issues/875

**Comment by rgomezp** [comment] 2019-11-07 22:18
DUPLICATE OF #875

**Closed by rgomezp** 2019-11-07 22:18 UTC
