### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by janbolat** [OneSignal/OneSignal-Android-SDK#902] opened 2019-12-04 03:32 UTC
Hi guys,
unfortunately, update to v3.11.4 has a lot of ANRs, as usual :(

```
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x765fbc38 self=0x74a1c14c00
  | sysTid=12282 nice=0 cgrp=default sched=0/0 handle=0x7528558560
  | state=S schedstat=( 640269027 89448077 577 ) utm=42 stm=21 core=2 HZ=100
  | stack=0x7fd55a4000-0x7fd55a6000 stackSize=8MB
  | held mutexes=
  at com.onesignal.LocationGMS.onFocusChange (LocationGMS.java:1)
- waiting to lock <0x01fdbeea> (a com.onesignal.LocationGMS$1) held by thread 37
  at com.onesignal.OneSignal.onAppFocus (OneSignal.java:2)
  at com.onesignal.ActivityLifecycleHandler.handleFocus (ActivityLifecycleHandler.java:5)
  at com.onesignal.ActivityLifecycleHandler.onActivityResumed (ActivityLifecycleHandler.java:3)
  at com.onesignal.ActivityLifecycleListener.onActivityResumed (ActivityLifecycleListener.java:1)
  at android.app.Application.dispatchActivityResumed (Application.java:264)
  at android.app.Activity.onResume (Activity.java:1403)
  at androidx.fragment.app.j.onResume (FragmentActivity.java:1)
  at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1416)
  at android.app.Activity.performResume (Activity.java:7609)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4013)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4053)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:51)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:145)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1955)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7063)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```

```
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x74e0c890 self=0x7129814c00
  | sysTid=10427 nice=-10 cgrp=default sched=0/0 handle=0x71afa40550
  | state=S schedstat=( 2199547073 677671943 3288 ) utm=157 stm=62 core=5 HZ=100
  | stack=0x7fe5bb9000-0x7fe5bbb000 stackSize=8MB
  | held mutexes=
  at com.onesignal.LocationGMS.onFocusChange (LocationGMS.java:1)
- waiting to lock <0x09356a16> (a com.onesignal.LocationGMS$1) held by thread 33
  at com.onesignal.OneSignal.onAppFocus (OneSignal.java:2)
  at com.onesignal.ActivityLifecycleHandler.handleFocus (ActivityLifecycleHandler.java:5)
  at com.onesignal.ActivityLifecycleHandler.onActivityResumed (ActivityLifecycleHandler.java:3)
  at com.onesignal.ActivityLifecycleListener.onActivityResumed (ActivityLifecycleListener.java:1)
  at android.app.Application.dispatchActivityResumed (Application.java:243)
  at android.app.Activity.onResume (Activity.java:1403)
  at androidx.fragment.app.j.onResume (FragmentActivity.java:1)
  at com.raimbekov.android.sajde.MainActivity.onResume (MainActivity.kt:2)
  at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1413)
  at android.app.Activity.performResume (Activity.java:7489)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4079)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4124)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:51)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:151)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:76)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1983)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:232)
  at android.app.ActivityThread.main (ActivityThread.java:7228)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:576)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:878)
```

**Comment by rgomezp** [comment] 2019-12-06 00:18
Duplicate of #898

**Closed by rgomezp** 2019-12-06 00:18 UTC
