### ISSUE TITLE
java.lang.IllegalArgumentException in com.onesignal.OneSignalSyncServiceUtils.hasBootPermission

### ISSUE THREAD

**Issue by rameshvoltella** [OneSignal/OneSignal-Android-SDK#814] opened 2019-07-29 05:41 UTC
Hi
We are getting java.lang.IllegalArgumentException with **com.onesignal.OneSignalSyncServiceUtils.hasBootPermission**
The following is the crash log i am getting in the google console.

> java.lang.RuntimeException: 
>  
>   at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3662)
>  
>   at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3702)
>  
>   at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2925)
>  
>   at android.app.ActivityThread.-wrap13 (ActivityThread.java)
>  
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1623)
>  
>   at android.os.Handler.dispatchMessage (Handler.java:110)
>  
>   at android.os.Looper.loop (Looper.java:203)
>  
>   at android.app.ActivityThread.main (ActivityThread.java:6528)
>  
>   at java.lang.reflect.Method.invoke (Method.java)
>  
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1084)
>  
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:945)
> Caused by: java.lang.IllegalArgumentException: 
>  
>   at android.os.Parcel.readException (Parcel.java:1696)
>  
>   at android.os.Parcel.readException (Parcel.java:1645)
>  
>   at android.app.job.IJobScheduler$Stub$Proxy.schedule (IJobScheduler.java:158)
>  
>   at android.app.JobSchedulerImpl.schedule (JobSchedulerImpl.java:42)
>  
>   at com.onesignal.OneSignalSyncServiceUtils.hasBootPermission (OneSignalSyncServiceUtils.java)
>   or                     .scheduleSyncServiceAsJob (OneSignalSyncServiceUtils.java)
>   or                     .syncOnFocusTime (OneSignalSyncServiceUtils.java)
>  
>   at com.onesignal.OneSignalSyncServiceUtils.internalSyncOnFocusTime (OneSignalSyncServiceUtils.java)
>   or                     .scheduleSyncTask (OneSignalSyncServiceUtils.java)
>   or                     .syncServicePendingIntent (OneSignalSyncServiceUtils.java)
>  
>   at com.onesignal.OneSignalSyncServiceUtils.access$000 (OneSignalSyncServiceUtils.java)
>   or                     .access$002 (OneSignalSyncServiceUtils.java)
>   or                     .cancelSyncTask (OneSignalSyncServiceUtils.java)
>   or                     .doBackgroundSync (OneSignalSyncServiceUtils.java)
>   or                     .scheduleLocationUpdateTask (OneSignalSyncServiceUtils.java)
>  
>   at com.onesignal.LocationGMS.access$100 (LocationGMS.java)
>   or                     .access$302 (LocationGMS.java)
>   or                     .fireComplete (LocationGMS.java)
>   or                     .getLocation (LocationGMS.java)
>   or                     .scheduleUpdate (LocationGMS.java)
>   or                     .setLastLocationTime (LocationGMS.java)
>  
>   at com.onesignal.OneSignalSyncServiceUtils.access$000 (OneSignalSyncServiceUtils.java)
>   or                     .access$002 (OneSignalSyncServiceUtils.java)
>   or                     .cancelSyncTask (OneSignalSyncServiceUtils.java)
>   or                     .doBackgroundSync (OneSignalSyncServiceUtils.java)
>   or                     .scheduleLocationUpdateTask (OneSignalSyncServiceUtils.java)
>  
>   at com.onesignal.OneSignal.onAppFocus (OneSignal.java)
>  
>   at com.onesignal.ActivityLifecycleHandler.handleFocus (ActivityLifecycleHandler.java)
>   or                     .onActivityCreated (ActivityLifecycleHandler.java)
>   or                     .removeActivityAvailableListener (ActivityLifecycleHandler.java)
>  
>   at com.onesignal.ActivityLifecycleHandler.onActivityResumed (ActivityLifecycleHandler.java)
>  
>   at com.onesignal.ActivityLifecycleListener.onActivityResumed (ActivityLifecycleListener.java)
>  
>   at android.app.Application.dispatchActivityResumed (Application.java:216)
>  
>   at android.app.Activity.onResume (Activity.java:1289)
>  
>   at android.support.v4.app.FragmentActivity.onResume (FragmentActivity.java)
>  
>   at in.oliveboard.prep.ui.base.BaseActivity.onResume (BaseActivity.java)
>  
>   at in.oliveboard.prep.ui.HomeActivity.onResume (HomeActivity.java)
>  
>   at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1293)
>  
>   at android.app.Activity.performResume (Activity.java:6936)
>  
>   at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3633)
>  
>   at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3702)
>  
>   at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2925)
>  
>   at android.app.ActivityThread.-wrap13 (ActivityThread.java)
>  
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1623)
>  
>   at android.os.Handler.dispatchMessage (Handler.java:110)
>  
>   at android.os.Looper.loop (Looper.java:203)
>  
>   at android.app.ActivityThread.main (ActivityThread.java:6528)
>  
>   at java.lang.reflect.Method.invoke (Method.java)
>  
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1084)
>  
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:945)

This is happening to lava device  will give a detail as below.
Device name-Lava Z91
Os-7.1
Crash percentage-100% in lava device
Daiily crash rate -20- 40

**Comment by rgomezp** [comment] 2019-07-30 20:50
Duplicate of #753

**Closed by rgomezp** 2019-07-30 20:50 UTC
