### ISSUE TITLE
[Bug]: OneSignal subscription list shows "Permission is not granted" even the permission is already granted

### ISSUE THREAD

**Issue by softsan** [OneSignal/OneSignal-Android-SDK#2106] opened 2024-05-31 13:36 UTC
### What happened?

For few of my users in production, can't get subscribed to Onesignal. It shows the record in subscription list but it shows as "Permission is not granted" I double / triple checked with the users and they all have given permission for Notification. They also did cache and data clear, logout, uninstall and fresh install several times but it doesn't make any difference. I am using the very latest version of OneSignal SDK. Here are some screenshots:

<img width="1025" alt="subscription_list" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/7391319/48557f5a-6751-47d8-a6e4-69b594d00f96">

When i open that subscription, there is no "Externalid" and i am pretty sure I use that in my code:
<img width="468" alt="details" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/7391319/da91f901-6be9-4a21-8ba2-2b07b4c1e6b5">

### Steps to reproduce?

```Markdown
In my MainApplication.kt I init OneSignal like this:
OneSignal.initWithContext(applicationContext, oneSignalAppId)

this is how i asked permission:
CoroutineScope(Dispatchers.IO).launch {
                OneSignal.Notifications.requestPermission(true)
            }

And after login, i use this:
 OneSignal.login(userIdx)

and register the tags like this:
 OneSignal.User.addTag(key, value)

and on logout from my app i clear all the tags and also sign out from OneSignal
fun unregisterTag(key: String) {
        OneSignal.User.removeTag(key)
    }

fun removeExternalUserId() {
        OneSignal.logout()
    }

Also i created in-app Push prompt for those users and they received that and they always click on "Allow" button but it never get subscribed or if subscribed it shows as "Permission is not granted"
```

### What did you expect to happen?

It should subscribed to Onesignal and should receive push notifications.

### OneSignal Android SDK version

5.1.13

### Android version

13, 12, 11

### Specific Android models

```Markdown
Android 14 Samsung/ pixel device
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment] 2024-06-04 19:31
Hello @softsan thanks for reaching out! Are you able to reproduce this on any devices you have? If so, [capturing a debug log](https://documentation.onesignal.com/docs/capturing-a-debug-log#get-the-logs) would be most helpful to see what's going on.

Thank you!

**Comment by softsan** [comment] 2024-06-11 20:16
@jennantilla Further on this, we have several other users who are seeing either **"Permission not granted"** or **"Not subscribed"** on OneSignal dashboard. We double checked that they logout from app, cleared their cache and data, uninstall and fresh install the app. But it still shows the the same on OneSignal dashboard.  

![os_ss](https://github.com/OneSignal/OneSignal-Android-SDK/assets/7391319/1ee0cd39-f02a-4743-b8a5-3005bdd4cdee)

**Comment by socialError** [comment] 2024-06-14 12:13
@jennantilla 
Hello we have the same issue and we can reproduce it 100%.

Version: 5.1.14

**How to reproduce?**
1. clean install the app
2. use `Onesignal.login` to login user which already exists in onesignal console (that userId was previously logged in the app)
3. right after that request permission using `OneSignal.getNotifications().requestPermission` and accept permission

Based on logs when you accept permission `OperationRepo.enqueue(operation: {"name":"update-subscription` is enqueued and after that should be executed by `SubscriptionOperationExecutor` and sent to console. 

But problem is that if you manage to make step 3 (accepting permission) before login is executed via `LoginUserOperationExecutor` than `SubscriptionOperationExecutor` is not created and executed and subscription is in console shown as `Permission Not Granted` and stuck in that state. (It seems that restarting the app or changing onesignal tags doesn't help. Only fix is to disable permission and enable it manually again).

**When it works correctly?**
- if you call `Onesignal.login` and wait few seconds until `LoginUserOperationExecutor` is executed and then accept permission, then it works correctly and `SubscriptionOperationExecutor` is created and user is shown as subscribed in console
- if you request and accept permission and then  after `SubscriptionOperationExecutor` is executed  call `Onesignal.login` , then it works correctly and user is shown as subscribed in console

**So there seems to be small window if you accept permission after login before login is actually executed that causes this issue that subscription is shown as Permission not granted. We upgraded onesignal from 4.x to 5x and this causes huge issue for us so please take a look at it**

Here is the full log you can examine based on steps to reproduce:
https://www.dropbox.com/scl/fi/0zd5j9oszm0s67be6tivh/onesignal_issue.tft.rtf?rlkey=hxs6eeahdek9ykqzqddonqksv&dl=0

**Comment by jkasten2** [comment] 2024-06-21 17:51
@socialError thanks for breaking down the issue and documenting exactly when the issue does and doesn't happen.

The root of the issue is when a `LoginUserOperation` is being combined with a `UpdateSubscriptionOperation`. `LoginUserOperationExecutor` processes these together and makes a single REST API call as follows:
```
HttpClient: Request
Sent = POST
https://api.onesignal.com/apps/{{APP_ID}}/users - Body: {"identity":{"external_id":"SOME_EXISTING_ID"},"subscriptions":
[{"id":"11111111-2222-3333-444444444444","token":"FCM_PUSH_TOKEN","enabled":true,"notification_types":1}],"properties":
{"timezone_id":"Europe\/Bratislava","language":"en"},"refresh_device_metadata":true
}
```

The OneSignal REST API should be able to accept the subscription update, however as you noted there is a bug where if the externalId already exists the update on the subscription doesn't happen.

This is something the OneSignal backend is looking into, and we will update you here once it is fixed.

**Comment by jkasten2** [comment] 2024-07-09 22:49
@socialError @softsan this backend issue is now fixed!

To any avoid possibilities of a client side event being skipped (mostly prompting for notification permission outside of the OneSignal SDK) I also recommend you use the [OneSignal-Android-SDK 5.1.15](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.15) or newer.

**Closed by jkasten2** 2024-07-09 22:49 UTC

**Comment by Buinich** [comment] 2025-11-18 09:46
The same problem appeared on 5+ projects. When give consent for the first time the status is Permission Not Granted. If revoke consent and give it a second time, the issue is fixed

**Comment by TamilCodeRays** [comment] 2025-11-18 09:56
In my scenario, the user initially receives notifications, but after some time their status suddenly changes to ‘Never Subscribed’. Since this happens randomly and after a delay, I’m not able to reproduce the issue consistently.
