### ISSUE TITLE
Notifications omitted in OSRemoteNotificationReceivedHandler and from disabled channels are restored and shown as silent notifications.

### ISSUE THREAD

**Issue by krzysztof-drobek** [OneSignal/OneSignal-Android-SDK#1265] opened 2021-01-26 17:29 UTC
**Description:**
Notifications omitted in OSRemoteNotificationReceivedHandler and from disabled channels are restored and shown as silent notifications.

**Environment**
OneSignal SDK: 4.1.0
Android version: 11.0

**Steps to Reproduce Issue:**
Omitted notifications:
1. Implement OSRemoteNotificationReceivedHandler 
2. Omit notification with notificationReceivedEvent?.complete(null) method
3. Send push notification
4. Notification is not shown (correct behaviour)
5. Change omit logic to show all notifications
6. Kill the app 
7. Start the app
8. Previously omitted notifications are restored and shown

Channels:
1. Disable notification channel from system app settings
2. Kill the app
3. Send push notification
4. Start the app
5. Notifications from disabled channels are shown

**Expectations**
Omitted notifications are not restored upon app restart
Notifications from disabled channels are not restored upon app restart

**Comment by jfishman1** [comment] 2021-01-30 00:25
Hi there

For this step:

Omit notification with notificationReceivedEvent?.complete(null) method
The notification should still be in the notification center, even if you don't show it while the app is open.

What you are showing is expected behavior, if you do not want to have the message show upon re-opening the app, you can set a TTL 

Notifications past the TTL will not show again.

​Is there a specific use case you don't want them to restore at all?

**Comment by krzysztof-drobek** [comment] 2021-01-30 14:46
> The notification should still be in the notification center, even if you don't show it while the app is open.
Then what for is this method if not for omitting notifications? 

> What you are showing is expected behavior, if you do not want to have the message show upon re-opening the app, you can set a TTL
TTL is not meant to be used like that. 

**I don't want to restore notification if:**
-  for whatever business logic I was not interested in showing this notification to user at the time. 
For example if user is in the chat window, I don't want to show him notification at all (even silent one). Once user leaves chat window he should receive **new** notifications. This is not possible with notificationReceivedEvent?.complete(null) method because omitted notification will come back after restarting the app.

- user disabled channel, received notification for it, he enabled it back 
Notifications received when channel was disabled should not be restored once channel is enabled back, user should be able to receive only new notifications.

Is there any method in this SDK that will ignore notification completely? I don't want to show it now or never.

**Comment by jkasten2** [comment] 2021-03-11 03:54
@krzysztof-drobek Thanks for the details. I believe there are 3 different issues being described here. Let me know if I am summarying correctly.

## Issue 1
Notification being restored after being omitted with `notificationReceivedEvent?.complete(null)`.
> Omitted notifications:
> 1. Implement OSRemoteNotificationReceivedHandler 
> 2. Omit notification with notificationReceivedEvent?.complete(null) method
> 3. Send push notification
> 4. Notification is not shown (correct behaviour)
> 5. Change omit logic to show all notifications
> 6. Kill the app 
> 7. Start the app
> 8. Previously omitted notifications are restored and shown

### Status
It seems @Jeasmine could not reproduce this and would need more information. Could you provide the imformation requested from https://github.com/OneSignal/OneSignal-Android-SDK/issues/1265#issuecomment-796385467 ?

## Issue 2
Notifications being restored for a disabled Notification channel after restarting the app.
> 1. Disable notification channel from system app settings
> 2. Kill the app
> 3. Send push notification
> 4. Start the app
> 5. Notifications from disabled channels are shown

### Status
I don't think we tried to reproduce this one yet. It seems like this could be a possible bug with this SDK.

## Issue 3
User disabled notifications with system settings and turned them back on later. Right now all notifications received during disabled time are restored.

### Status
I don't think we tried to reproduce this one yet either, similar to issue 2 but the SDK will need to check a different setting.

**Comment by krzysztof-drobek** [comment] 2021-03-11 10:56
I can't reproduce the first issue as well. It must have been conected with the other two.
The second and the third issue seems to be the same thing.

**Comment by Jeasmine** [comment] 2021-03-11 15:43
Sorry If it was not clear. Channel and application notification disabling was tested too, and could not reproduce the bug. 

In-app message handling is separate from notification, so there should not be a conflict there.

**Comment by krzysztof-drobek** [comment] 2021-03-11 16:56
The demo app has foreground notifications disabled with `OneSignal.setNotificationWillShowInForegroundHandler` which prevents restored notifications from being shown on app start, please remove it and redo the test. 

I've run your demo app without `OneSignal.setNotificationWillShowInForegroundHandler` in `MainApplication` class and then did following:

1. Started the app so user is subscribed.
2. Disabled notification channel in system settings
3. Sent notification message to disabled channel
4. Enabled notification channel
5. Killed the app
6. Started the app
7. OneSignal SDK restored notification which was delivered when channel was disabled

https://user-images.githubusercontent.com/40163235/110823495-72ee7b80-8292-11eb-868f-503cd8195d2a.mp4

**Comment by Jeasmine** [comment] 2021-03-11 18:46
@krzysztof-drobek Thanks for the video. That is very helpful! I will try again to reproduce it again.

**Comment by Jeasmine** [comment] 2021-03-11 19:00
I was able to reproduce with those steps; I see the problem. We will be working on fixing this for the next release. Thanks again!

**Comment by Jeasmine** [comment] 2021-06-30 22:42
The fix has been included under https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.3.0

**Closed by Jeasmine** 2021-06-30 22:42 UTC
Labels: Bug: Medium Priority, WIP
