### ISSUE TITLE
Device subscribe problem with promptLocation

### ISSUE THREAD

**Issue by AhmedKaram2** [OneSignal/OneSignal-Android-SDK#477] opened 2018-03-20 08:23 UTC
I start using one signal after publishing the first version of my app,
the problem that devices which new install the app subscribe successfully but the devices which update the app not subscribe so what the problem

**Comment by jkasten2** [comment] 2018-03-20 08:40
@AhmedKaram2 We will need some more detail in order to look into this.
1. By not subscribed is the device showing up on the OneSignal dashboard as not subscribed or not showing at all?
2. Did you open the app after updating?
3. Are you able to reproduce the issue on your test devices?
4. If so can you check for any errors or warnings in the logcat?

**Comment by AhmedKaram2** [comment] 2018-03-20 08:53
Thank you for your replay,

The device not showing at all 
yes and when a follow my users I see that all update the app but only 5 users subscribed
yes, when I delete my test device from the dashboard and try to subscribe again by open the app and send tag it not appear but when removing the app and install it again subscribed successfully

**Comment by AhmedKaram2** [comment] 2018-03-20 08:56
03-20 12:55:09.277 30400-30447/com.mohre.ips I/OneSignal: Location Change Detected
03-20 12:55:10.276 30400-30474/com.mohre.ips I/OneSignal: updating prefs: OneSignal, ONESIGNAL_USERSTATE_SYNCVALYES_CURRENT_STATE
03-20 12:55:10.277 30400-30571/com.mohre.ips I/OneSignal: updating prefs: OneSignal, ONESIGNAL_USERSTATE_DEPENDVALYES_CURRENT_STATE
03-20 12:55:14.287 30400-30447/com.mohre.ips I/OneSignal: Location Change Detected

**Comment by jkasten2** [comment] 2018-03-20 08:58
@AhmedKaram2 These entries are ok. Can you attach the full logcat as a txt file?

**Comment by AhmedKaram2** [comment] 2018-03-20 09:05
[logCat.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1828565/logCat.txt)

**Comment by jkasten2** [comment] 2018-03-20 09:08
The device is registering with OneSignal but it didn't get a push token from Google. Can you send the rest of the log before the snippet you attached? The reason for the issue should be above what you attached.

**Comment by AhmedKaram2** [comment] 2018-03-20 09:12
this all my logcat sorry about disturb :)
[logCat.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1828599/logCat.txt)

**Comment by jkasten2** [comment] 2018-03-20 09:23
@AhmedKaram2 Thanks, it looks like the device is getting a push token from Google fine so this doesn't seem to be the issue.

Are you initializing OneSignal from your Activity class or your Application class? Are you doing so on the main thread or a background thread?

**Comment by AhmedKaram2** [comment] 2018-03-20 09:33
This is the initilization of the oneSignal in Application class.
<img width="540" alt="capture" src="https://user-images.githubusercontent.com/8946140/37646383-f93b5efa-2c42-11e8-8efd-7de41ed514c2.PNG">

Then this the part of sending the tag of the user to subscribe
<img width="524" alt="captur" src="https://user-images.githubusercontent.com/8946140/37646468-372753fe-2c43-11e8-9141-ce0607cf7e1f.PNG">

**Comment by AhmedKaram2** [comment] 2018-03-20 09:35
Maybe the problem with the code?

**Comment by AhmedKaram2** [comment] 2018-03-20 11:19
I notice something maybe it help

when I go to settings and clear app cash data it works fine

**Comment by jkasten2** [comment] 2018-03-20 21:53
@AhmedKaram2 Thanks for the details and code. Clearing the app data from settings is basically the same as fully uninstalling then reinstalling the app however.

Your initialization looks fine, so I don't believe this is an issue. However can you make sure you aren't calling `OneSignal.startInit(...).init()` from any where else in your app?

Since it looks like you are able to reproduce the issue on your devices I'll prepare a custom debug build so we can get some more details to narrow done the problem. I'll reply here when it is available.

**Comment by AhmedKaram2** [comment] 2018-03-21 04:00
Ok, Thank you 👍

**Comment by jkasten2** [comment] 2018-03-21 04:44
Can you switch to the following snapshot in your `app/build.gradle`?

```gradle
// Add snapshots repo if you don't have it already
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}

dependencies {
   compile 'com.onesignal:OneSignal:4.0.0-20180321.043221-9'
}
```

Please do the same steps that you did to reproduce the issue and attach the new `logcat.txt` so we can review it. Thanks!

**Comment by AhmedKaram2** [comment] 2018-03-21 04:55
I remove Notification open handler and use the older version and publish update it works now I don't know why and also why I make like this but it works if you need me to make this steps as test inform me

thank you

**Comment by jkasten2** [comment] 2018-03-21 05:31
@AhmedKaram2 What OneSignal version ended up working for you?

Can you repeat the steps of installing the old version of your app before OneSignal, then making a build of your app with the test version above? If possible we would like to find the root cause of the issue.

**Comment by jkasten2** [comment] 2018-03-22 06:21
@AhmedKaram2 I have found and fix the root of this issue in PR #484. It is due to a race condition in the SDK with `OneSignal.promptLocation`. I **highly recommend** updating to 3.8.3 as soon as we release it as this might have been an issue for a number of releases.

We also have a build of this PR available. Can you can try out so you can confirm this is fixed for you as well before this release?

`app/build.gradle`
```gradle
// Add snapshots repo if you don't have it already
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}

dependencies {
   compile 'com.onesignal:OneSignal:4.0.0-20180322.061214-10'
}
```

Thanks!

**Comment by jkasten2** [comment] 2018-03-22 23:29
@AhmedKaram2 [OneSignal SDK 3.8.3](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.8.3) is now released with this fix!

**Closed by jkasten2** 2018-03-22 23:29 UTC
Labels: bug

**Comment by AhmedKaram2** [comment] 2018-03-25 09:31
Thank you for your efforts :)

**Comment by asghaier76** [comment] 2018-04-02 03:27
I think the same is happening with the ionic plugin. has it also been fixed

**Comment by jkasten2** [comment] 2018-04-02 04:44
@asghaier76 yes, the OneSignal Cordova version 2.3.3 has this update. https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/2.3.3/plugin.xml#L30

Please open a new issue in the Cordova repo with your OneSignal code and a list of plugins your app is using by calling `ionic cordova plugin ls`
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues

**Comment by AnkitS221** [comment] 2019-07-25 12:32
g

**Comment by AnkitS221** [comment] 2019-07-25 12:38
Hi @jkasten2 ,
I am having some troubles with subscribing to some devices. At first the problem was the date was not current through the logcats which i fixed,now i have distributed my app already.
In one of the devices i had to factory reset the settings which also worked.
But now since it being distributed I am unable to track those devices and what problems they are having for not getting subscribed.
The Device in which i had to factory reset had issues in Logcat like unable to fetch android parameters.
So what can be the problems which will lead to Onesignal not being subscribed and how to keep track of them

**Comment by jkasten2** [comment] 2019-07-26 07:58
@AnkitS221 I am not sure I understand the problem, however it doesn't seem directly related to this ticket. Can you open a new issue and provide exact steps on reproducing the issue? Also let us know which devices you have tested.
