### ISSUE TITLE
Duplicate class androidx.work.OneTimeWorkRequestKt and androidx.work.PeriodicWorkRequestKt

### ISSUE THREAD

**Issue by LaTrita97** [OneSignal/OneSignal-Android-SDK#1915] opened 2023-11-16 09:29 UTC
### What happened?

I've installed the version `5.0.4` of the plugin and when I try to run the app on an Android device I get this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class androidx.work.OneTimeWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)
     Duplicate class androidx.work.PeriodicWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Exception: Gradle task assembleDebug failed with exit code 1
```

I've followed all the steps in the initialization process for Android by setting `33` as `compileSdkVersion` value in the `android/app/build.gradle`.

What can I do to fix this problem?

### Steps to reproduce?

```Markdown
1. Install the plugin onesignal_flutter: ^5.0.4
2. Launch the app
```

### What did you expect to happen?

That I was able to run the app

### OneSignal Android SDK version

5.0.4

### Android version

11

### Specific Android models

```Markdown
Samsung Galaxy A40
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment] 2023-11-16 19:45
Hi @LaTrita97 thanks for reaching out! It sounds like this is only happening with the Flutter SDK, correct? Were you using a previous version of the Flutter plugin (e.g., 5.0.3) where you also experienced this?

It looks like this is related to the work-runtime dependency. In our native Android SDK we did recently [update the preferred version](https://github.com/OneSignal/OneSignal-Android-SDK/pull/1890) to incorporate the latest version, 2.8.1. It's possible there is a dependency conflict where another package in your project may be pulling in androidx.work:work-runtime, and they have conflicting versions.

You could look into resolving these dependencies with something like [ResolutionStrategy](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html) so you can control which version the dependency resolves to.

Let us know if that helps!

**Comment by rubenferreira97** [comment] 2023-11-25 03:23
@jennantilla I am the author of the initial issue #1889 that reported this. I can confirm that the PR only solved half of the problem and I can still hit this same issue. After some deep diving in the code I think I have found the culprit: 

https://github.com/OneSignal/OneSignal-Android-SDK/blob/ff841f9c1fa595ebb6bf7cd6d2b09024153ba7c5/OneSignalSDK/onesignal/notifications/build.gradle#L68

This need to be updated or changed. I would maybe do something like this:
```
def work_version = "2.8.1"

implementation "androidx.work:work-runtime-ktx:$work_version"
api('androidx.work:work-runtime') {
    version {
        require '[2.1.0, 2.8.99]'
        prefer '$work_version'
    }
}
```
or
```
def work_version = "2.8.1"

// don't know if this shoud be an api
api('androidx.work:work-runtime-ktx') {
    version {
        require '[2.1.0, 2.8.99]'
        prefer '$work_version'
    }
}

api('androidx.work:work-runtime') {
    version {
        require '[2.1.0, 2.8.99]'
        prefer '$work_version'
    }
}
```

**Comment by rubenferreira97** [comment] 2024-01-04 18:04
@jennantilla Sorry to bother, but two releases (5.0.5 and 5.1.0) have already been launched and this problem still occurs.

Here is the code that should be changed (OneSignal 5.1.0):
https://github.com/OneSignal/OneSignal-Android-SDK/blob/52987ab505816e3f42fe837f195a53ef817f94e7/OneSignalSDK/onesignal/notifications/build.gradle#L68

**Comment by jennantilla** [comment] 2024-01-11 20:47
@rubenferreira97 thank for the reminder, apologies that this was lost in the holiday shuffle. I'll get this out ASAP.

**Closed** 2024-01-17 17:37 UTC

**Comment by avargaskun** [comment] 2024-01-18 01:32
@jennantilla - can we get this fix included in the https://github.com/OneSignal/OneSignal-Cordova-SDK plugin as well? v5.0.4 of the plugin (latest) reference an older version of the Android SDK that does not include this fix.

**Comment by nano71** [comment] 2024-06-25 11:04
You can use `configurations.all` and `solutionStrategy` to force all dependencies to use the same version of the `androidx.work` library.
```gradle
android {
    ...
}

dependencies {
    ...
}

configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'androidx.work') {
            details.useVersion '2.8.1'
        }
    }
}
```
