### ISSUE TITLE
Scheduling restart of crashed service com.onesignal.SyncService

### ISSUE THREAD

**Issue by nilabh** [OneSignal/OneSignal-Android-SDK#138] opened 2016-11-04 06:00 UTC
Service crashes when i remove app from background and then it stops receiving notification.
It only receives notification when app is running.
logcat:
```java
11-03 18:09:41.306 1851-4688/? W/ActivityManager: Scheduling restart of crashed service com.mobile.simplilearn/com.onesignal.SyncService in 11000ms 
11-03 18:09:41.314 1851-4688/? I/ActivityManager: Force stopping service ServiceRecord{6c3e7e5 u0 com.mobile.simplilearn/com.onesignal.SyncService}
```
gradle:
```gradle
 compile 'com.onesignal:OneSignal:3.4.1'
```
manifest:
```xml
 <service
            android:name=".OneSignalNotificationExtenderBareBonesService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.onesignal.NotificationExtender" />
            </intent-filter>
        </service>

        <meta-data
            android:name="com.onesignal.NotificationOpened.DEFAULT"
            android:value="DISABLE" />
```

**Comment by nilabh** [comment] 2016-11-04 06:36
With further debugging i found out that if i pressed home and killed the app after onesignal had sent all requests service restarted properly.
It crashed when i removed the app from background immediately.

**Comment by jkasten2** [comment] 2016-11-04 06:36
@nilabh Thanks for the report. I am able to reproduce the `Scheduling restart of crashed service` logcat entry but on our test devices Nexus 6 (6.0.1), LG G2 (5.0.2), and Galaxy Nexus (4.2.2) I don't see `Force stopping ` and notifications are still received after this.

Can you also include the Android version and device model you are seeing the entries above and the no notifications issue after that?

I'll look into creating a fix for the first part where Android is reporting this as a crash since I can reproduce this part.

**Comment by nilabh** [comment] 2016-11-04 06:40
@jkasten2 Thanks for the update.I'm using Moto g4 Plus(6.0.1)
I've posted my recent findings in the comment above.

**Comment by jkasten2** [comment] 2016-11-04 06:48
@nilabh Thanks for the device info. Could you expand on `killed the app after onesignal had sent all requests`? Do you mean after OneSignal as completed it's network calls based off the OneSignal's logcat logs then swiping the app away in the Recent Apps list?

**Comment by nilabh** [comment] 2016-11-04 07:03
@jkasten2 Yea. You got it right -  "OneSignal as completed it's network calls based off the OneSignal's logcat logs then swiping the app away in the Recent Apps list"

**Comment by jkasten2** [comment] 2016-11-04 07:24
@nilabh I have created a possible fix, can try to reproduce the no notification issue with it on that same device?

Download
https://www.dropbox.com/s/019ltohvlyyyei3/onesignal-release.aar?dl=0

Instructions on using a local .aar SDK build.
https://gist.github.com/jkasten2/4683711807373dabaf5d5833b9574bb1

**Comment by nilabh** [comment] 2016-11-04 07:51
@jkasten2 Thanks.
Will try this out and update.

**Comment by jkasten2** [comment] 2016-11-17 00:13
@nilabh We are looking into including this in our next release. Could let us know if you had an chance to try this?

**Comment by jkasten2** [comment] 2016-12-06 09:37
Merged branch into master, final changes in commit 7854e7f4d062473c370be33599f3b2014ef414ed.
Confirmed this fixes the following logcat entry.
```
Scheduling restart of crashed service com.mobile.simplilearn/com.onesignal.SyncService in 11000ms
```

@nilabh Did this fix the `Force stopping service ServiceRecord` error and the notification not showing issue? Changes will be included in the 3.4.2 release anyway since part we confirmed part of the issue has been fixed. Confirmation from your specific device would be helpful.

**Comment by phajduk** [comment] 2016-12-07 12:14
@jkasten2 I can confirm that your commit fixed problem with `Force stopping service`. However problem with already released fix is that together with `SyncService`, after those 10 seconds whole application process will be also spawned. 
It's an issue because it's common practice to initialize third parties in Application `onCreate` and in this case all that stuff will be launched.

**Comment by jkasten2** [comment] 2017-04-11 22:38
@phajduk I have changed the `SyncService` to only restart the service if there are pending changes that haven't been send to OneSignal's server's yet in commit cf7b242bf500c64dceb02ced8cd1df566f7b16a6. This will be included in the next 3.4.4 release.

Do note that every time a notification is received your `Application` `onCreate` will start as well which is unavoidable. Additionally any other `BroadcastReceiver` or `Service` will fire this as well so I recommend making sure your code in it isn't to resource heavily.

**Closed by jkasten2** 2017-04-11 22:38 UTC
Labels: bug

**Comment by sandstranger** [comment] 2017-12-22 06:48
This error not fixed !

**Comment by kinnrot** [comment] 2018-08-27 12:36
happened to me also version 3.9.2

**Comment by jkasten2** [comment] 2018-08-28 04:45
@ghost @kinnrot the `SyncService` has changed dramatically since 3.4.4 and is now only use for Pre-5.0 Android devices. `SyncJobService` is now used for most devices.

Please create a new issue and provide as much detail as you can including full stack traces and if you can reproduce the issue on your devices.
