### ISSUE TITLE
Android O : Notification not display target 26, after enabling a NotificationExtenderService

### ISSUE THREAD

**Issue by ivory972** [OneSignal/OneSignal-Android-SDK#346] opened 2017-10-24 16:11 UTC
Hi, 

When I receive a notification on an Android 8 version, I got this error in the log : 
```
mypackage : V/FA: Inactivity, disconnecting from the service

mypackage : E/EnhancedIntentService: binding to the service failed

mypackage : W/EnhancedIntentService: Service took too long to process intent: com.google.android.c2dm.intent.RECEIVE App may get closed.
```

- I extend "NotificationExtenderService" in order to display my own notification so I return "true" for the "onNotificationProcessing()" method.
```
@Override
  protected boolean onNotificationProcessing(OSNotificationReceivedResult notification)
  {
     createNotification(getApplicationContext());
     return true;
  }
```
 - createNotification() : create and display the notification.

When the issue happened : 
- The app is in the background,
- I received the notification the first time, 
- The other times, I got the previous error,
- The OneSignal dashboard, indicates as the notification is successfully received, however is not, 

```
  compileSdkVersion 26
  buildToolsVersion "26.0.2"
  targetSdkVersion 26
```

 Can anybody tell me what it's happening, and how I can solve it please ?

Thanks

**Comment by Alamgir** [comment] 2017-10-24 20:12
@ivory972 in the current version of OneSignal, background processing of the NotificationExtenderService is not available for Android-O as it currently doesn't use a JobScheduler to fire the extender. 

This should be present in the next release as we have a fix ready to go.

**Comment by jkasten2** [comment] 2017-10-30 20:41
@ivory972 This fix is now released in the 3.6.5 update. Please see the [release notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.6.5) for the required changes.

**Comment by mck182** [comment] 2018-03-27 19:21
I'm using `compile 'com.onesignal:OneSignal:3.8.3@aar'`
but I still see the same error on Android 8:

```
03-27 15:04:21.064 W/EnhancedIntentService: Service took too long to process intent: com.google.android.c2dm.intent.RECEIVE App may get closed.
```

I'm targetting Sdk 27:
```
        compileSdkVersion 27
        minSdkVersion 16
        targetSdkVersion 27
```

Could there potentially be a regression in this?

**Comment by jkasten2** [comment] 2018-03-27 19:30
@mck182 We haven't seen any other reports of this. There can be multiple receivers of `com.google.android.c2dm.intent.RECEIVE` Intent in your app. I recommend checking the Merged Mainfest to see if there are others for another plugin / SDK or your own in your app.

![image](https://user-images.githubusercontent.com/645861/37990250-968c95da-31ba-11e8-8e06-4b3f3e57b949.png)

**Comment by mck182** [comment] 2018-03-27 19:47
Looking at the generated intermediate `AndroidManifest.xml`
I can see there are two receivers - one for OneSignal and the
other one for Firebase:

```
<receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />

                <category android:name="com.fivehundredpx.viewer" />
            </intent-filter>
        </receiver>
```

But the second one must come from some Google library as this
app doesn't actually use Firebase explicitly.

**Comment by jkasten2** [comment] 2018-03-27 20:17
@mck182 You can click on the Firebase receiver in the Merged Manifest veiew and it will show you the exact dependency that added it on the bottom right. Either way though it shouldn't cause this issue.

Are you able to reproduce the issue? If so can you share the exact setting you use on the notification or if you used the REST API can you share the JSON payload?

**Comment by mck182** [comment] 2018-03-27 20:47
The Manifest merging log doesn't really help, it just
shows 
```
Merging Log
Added from the firebase-iid:11.8.0 manifest, line 39
```
...but that's not my dep, must have come from something
else and I can't seem to find out from what.

I can reproduce it. I have some custom grouping logic
in the handler and the first notification always works,
second notification is supposed to be added to the
group of the previous notification but that's where it
stops working. Any following notification will also show
that error. The payload is pretty standard with some
custom data (uses REST API):
```
{
  "notificationID": "...",
  "body": "...the body...",
  "additionalData": {
    "payloadTimestamp": 1522183247,
    "channel": "aChannel",
    "publishedTimestamp": "2018-03-27T20:40:46.705195Z",
     ...few other key-value pairs...
  },
  "lockScreenVisibility": 1,
  "fromProjectNumber": "my project number",
  "priority": 0,
  "rawPayload": "...the raw payload..."
}
```

I'm starting to think that maybe some of my custom
processing code may be at fault here, I'll keep digging.

**Comment by mck182** [comment] 2018-03-27 21:28
Ok so from what I can tell, this may not be OneSignal's SDK
issue after all. The other Firebase receiver is being added by
```
apply plugin: 'com.google.gms.google-services'
```
in the build.gradle file. Removing this removes the receiver and
I no longer see the error.

I'll keep an eye on it and report back if I find anything more useful.

**Comment by jkasten2** [comment] 2018-03-27 22:15
Ah right, the merged manifest doesn't show the tree. Yes, the `com.google.gms.google-services` will add some decencies too. You can run the following from the terminal to get a full dependency tree incase you need it in the future.
` ./gradlew app:dependencies`

Your doing this notification grouping in your `NotificationExtenderService` correct? Can you time how long your code is running? I tried searching for `EnhancedIntentService` and the message in logcat but can't even find this in the [Android source code](https://github.com/aosp-mirror/platform_frameworks_base) so not sure on wha the actual limit is. Curious what you find in your testing.

**Comment by jkasten2** [comment] 2018-04-01 23:49
Closing this issue due to inactivity, however still feel free to report your findings as it might help others. Thanks!

**Comment by mck182** [comment] 2018-04-02 15:03
Right; I should have mentioned that I only get a few hours
a week to work on this, sorry about that. I've managed to
time the execution of the function that I'm calling wihtin
`NotificationExtenderService`, it's reasonably fast - 20ms
on average.

I'm somewhat sure that the issue is due to the `google-services`
plugin which creates the second receiver and I believe that
one times out. If I remove it, the problem is gone, if I add it
back the problem reappears (however the OneSignal service
still times at about 20ms on average). Also the error message
appears in the logcat after about 5 seconds, so the limit seems
reasonable (though I'm not sure if that's the actual limit).

The actual problem is that even when it's the other receiver,
the entire app may get killed, so it may affect the OneSignal
service as well. But I'm not sure if there's anything for you to
do (so I think this can remain closed).

I'll post any other findings if I figure something out.

**Comment by jkasten2** [comment] 2018-04-02 17:05
Can you reproduce this issue in a new Android project? If so please share it and we can take a look.

Let us know the device models you see this issue on and if it is Android 8.0 or 8.1. I also recommend testing work the Android emulator to see if the issue occurs there too

**Comment by mck182** [comment] 2018-04-02 17:38
I'll give it a try, I just can't give you a reliable guess for when
(really sorry about that, my work time for this is very limited).
I'm seeing this on Nexus 6P and Android 8.0. I haven't really
tested on an emulator, but I'll try some multi combinations of
devices and Android versions.

**Comment by jkasten2** [comment] 2018-04-19 06:02
Closing issue due to inactivity, we can reopen later if you can provide an example project and / or more details.

**Closed by jkasten2** 2018-04-19 06:02 UTC
Labels: Awaiting Details, Bug
