### ISSUE TITLE
[Bug]: OneSignal.initWithContext() crashes on minified builds (5.0.0)

### ISSUE THREAD

**Issue by matejsemancik** [OneSignal/OneSignal-Android-SDK#1811] opened 2023-08-23 09:26 UTC
### What happened?

The latest (5.0.0) version of SDK crashes during initialization using `OneSignal.initWithContext(Context, String)` method
when executed on application build minified by R8.

The attached crash log is extracted from my application's Crashlytics. (Android Gradle Plugin 8.1.0, Kotlin 1.8.22)
The same crash happens on OneSignalDemo example app. (Android Gradle Plugin 7.0.4, Kotlin 1.4.32)

This might be related to https://github.com/OneSignal/OneSignal-Android-SDK/issues/1810

I temporarily worked around this issue by excluding entire OneSignal SDK from my proguard rules, but I see that as not very ideal solution.

### Steps to reproduce?

```Markdown
1. Checkout the latest release `5.0.0` tag
2. Run the `gmsRelease` variant of sample `OneSignalDemo` app with R8 enabled -- `minifyEnabled true`:


buildTypes {
    release {
        minifyEnabled true
        signingConfig signingConfigs["debug"]
        proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
    ...

3. Observe crash during SDK initialization
```

### What did you expect to happen?

I expected SDK to initialize without any issues and for the app to not crash during startup on obfuscated release build of application.

### OneSignal Android SDK version

5.0.0

### Android version

13

### Relevant log output

```Shell
Caused by: java.lang.Exception: Service interface jb.a could not be instantiated
    com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:70)
    com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:416)
    com.onesignal.OneSignal.initWithContext(OneSignal.java:126)
    dev.matsem.myapppackage.android.App.initializeOneSignal(App.kt:40)
    dev.matsem.myapppackage.android.App.onCreate(App.kt:17)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment] 2023-08-23 21:33
@matejsemancik Thank you for reaching out! We're looking into this and will get back to you as soon as possible.

**Comment by jdonlan** [comment] 2023-08-28 11:49
I can verify this same behavior in our application after updating to 5.0.0. The library works fine in a development environment without minification but fails on release builds due to minification.

**Comment by ShinyParadise** [comment] 2023-08-28 12:29
If someone tries to fix this problem, here's more readable output of the same error. I got it by keeping all classes of `com.onesignal.**` package (excluded it in proguard file manually)
```
java.lang.Exception: Service class com.onesignal.core.internal.config.ConfigModelStore could not be instantiated
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.Exception: Service class com.onesignal.core.internal.config.ConfigModelStore could not be instantiated
	at com.onesignal.common.services.ServiceProvider.f(Unknown Source:96)
	at com.onesignal.internal.OneSignalImp.c(Unknown Source:142)
	at com.makesure.ui.MakeSureApp.onCreate(Unknown Source:29)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loop(Looper.java:223) 
	at android.app.ActivityThread.main(ActivityThread.java:7656) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by michael-winkler** [comment] 2023-08-29 07:25
I tried here https://github.com/OneSignal/OneSignal-Android-SDK/issues/1810#issuecomment-1696909884 to convert the old rules

**Comment by Petr-Kubista** [comment] 2023-09-08 07:49
Still broken on 5.0.1

**Comment by emawby** [comment] 2023-09-11 21:05
Closing as a Duplicate of #1810

**Closed by emawby** 2023-09-11 21:05 UTC
Labels: Duplicate
