### ISSUE TITLE
NotificationCompatBuilder  inaccessible to  com.onesignal.GenerateNotification

### ISSUE THREAD

**Issue by yaseen-homage** [OneSignal/OneSignal-Android-SDK#367] opened 2017-11-14 06:25 UTC
After updating to support library 27.0.0
 I'm getting Exception when i try to customize Notification icons 

```
Extended notification displayed but custom processing did not finish.
                                              java.lang.IllegalAccessError: Field 'android.support.v4.app.NotificationCompat$Builder.mNotification' is inaccessible to class 'com.onesignal.GenerateNotification'
```

`public class NotificationExtender extends NotificationExtenderService {

    @Override
    protected boolean onNotificationProcessing(final OSNotificationReceivedResult notification) {
        //Override Settings
        final OverrideSettings overrideSettings = new OverrideSettings();
        overrideSettings.extender = new NotificationCompat.Extender() {
            @Override
            public NotificationCompat.Builder extend(NotificationCompat.Builder builder) {
                Bitmap bitmap = BitmapFactory.decodeResource(NotificationExtender.this.getResources(),
                        R.drawable.ic_notification_large_icon);
                builder.setLargeIcon(bitmap);

                Log.d(NotificationExtender.class.getName(), notification.payload.additionalData.toString());
                JSONObject data = notification.payload.additionalData;
                String notificationType = data.optString("notification_type", "");

                return builder.setColor(ContextCompat.getColor(NotificationExtender.this, R.color.app_green));
            }
        };

        OSNotificationDisplayedResult displayedResult = displayNotification(overrideSettings);
        //return true to stop notifications
        return false;
    }
}`

**Comment by nglro** [comment] 2017-11-15 15:37
Just got crashlytics flooded with errors after sending a notification.

`E/OneSignal: onNotificationProcessing throw an exception. Extended notification displayed but custom processing did not finish.
java.lang.IllegalAccessError: Field 'android.support.v4.app.NotificationCompat$Builder.mNotification' is inaccessible to class 'com.onesignal.GenerateNotification' (declaration of 'com.onesignal.GenerateNotification' appears in /data/app/testbuild/base.apk)`

Using:
OneSignal 3.6.5
Support Lib 27.0.0

**Comment by jkasten2** [comment] 2017-11-15 23:14
@yaseen-homage @nglro This is due this SDK not being compatible with the Android support library revision 27 yet. You will need to use revision 26 until we can update the SDK.

Closing this issue as it is a duplicate of issue #352. You can follow this issue for update.

**Closed by jkasten2** 2017-11-15 23:14 UTC
