### ISSUE TITLE
[Bug]: OptOut then OptIn doesn't work, user can no longer receive notifications

### ISSUE THREAD

**Issue by fanwgwg** [OneSignal/OneSignal-Android-SDK#1837] opened 2023-09-14 10:36 UTC
### What happened?

Using 5.0.1 release.

When a user is already subscribed, calling `OneSignal.getUser().getPushSubscription().optOut()` does opt the user out as reflected on the dashboard. However, immediately calling `OneSignal.getUser().getPushSubscription().optIn()` doesn't change the opt-in status, user is still opt-out on the dashboard and cannot receive notifications.

There is a similar issue on the flutter sdk https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/729.

### Steps to reproduce?

```Markdown
Described above
```

### What did you expect to happen?

User should be subscribed after calling optIn

### OneSignal Android SDK version

5.0.1

### Android version

13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment] 2023-09-14 17:20
@fanwgwg Hello could you get logs for this by turning on verbose logging? I am not able to reproduce this behavior

**Comment by emawby** [comment] 2023-09-14 17:43
In the logs I am seeing that after optIn we do update the subscription but the enabled value is still false. In my test app the value is true. Just to confirm before calling optOut is your subscription enabled (user is able to get push)? I am wondering if there is something else about the subscription (maybe the push permission?) that is causing it to stay false

**Comment by emawby** [comment] 2023-09-14 17:55
The enabled value is calculated based off a few factors one of which is optOut/In being called. The device needs to have a valid push token, push permissions enabled, and optIn true. Since in the log optIn was set to true and the device has a token then the SDK must not recognize that push permissions are enabled. I will try requesting permissions outside of the SDK and see if that is the issue!

**Comment by emawby** [comment] 2023-09-19 18:03
@fanwgwg Got it I will try that

**Comment by Munzey** [comment] 2023-10-09 17:27
experiencing the same with `5.0.2` - app permissions are definitely on.

On a fresh install, after calling `initWithContext` on app create and I login through our login flow and call `OneSignal.login(myLoginUserId)` I can push notifications fine.

If I try `optOut()` a user on my logout flow, and then try login again and call `optIn()`, the subscription status never seems to update, and the user cannot receive pushes.
l only tried adding these after finding that when calling `OneSignal.logout()` and `OneSignal.login(myUserId)` in my respective flows wasn't working.

The only way I can get it to trigger again for the same user is to uninstall the app and reinstall, going through the initial flow again.

I'm not sure if there is some internal permission state being held thats incorrect, but it seems like the opted out status might be getting copied over when we login again?

if so I wonder would exposing https://github.com/OneSignal/OneSignal-Android-SDK/issues/1854 help as I could call this before calling to `optIn` again.

Whatever the issue, this is a blocker for our company integration (HubSpot).

**Comment by eliran1989** [comment] 2023-11-29 08:13
I have the same issue. I develop in react native. also i use OneSignal.User.pushSubscription.getOptedIn() to get the current status and it always return false also after i trigger OneSignal.User.pushSubscription.optIn();

there is any resolve?

**Comment by eliran1989** [comment] 2023-11-29 08:20
I seems to me that it take time to status to update on server

**Comment by jennantilla** [comment] 2024-01-17 17:39
Hello everyone! Just an update that this was fixed in [5.1.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.1) of our SDK. Please update to this version and let us know if you are having any additional issues. Thanks!

**Closed by jennantilla** 2024-01-17 17:39 UTC
