### ISSUE TITLE
App crash when display notification 

### ISSUE THREAD

**Issue by zack-barakat** [OneSignal/OneSignal-Android-SDK#255] opened 2017-06-20 09:38 UTC
Hi 
I've received several crash reports in my app, it probably crashes when try to display notification.
It happens on these devices:

| Device   |  Model     |  OS |
| --- | --- | --- |
|i-mobile  | i-mobile i-STYLE_810 | 5.0
| APLUS  |   A88new   |    5.1 |
| alps     |     MC-X9    |    5.1 |
| T18      |     T18         |     5.1 |

```Java
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package com.gobike.consumer: Couldn't create icon: StatusBarIcon(pkg=com.gobike.consumeruser=0 id=0x7f0200f9 level=0 visible=true num=0 )
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1638)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5631)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

let me know if you need more details.

**Comment by jkasten2** [comment] 2017-06-26 20:41
@zack-barakat From the error it looks like the small notification icon was not set correctly. If you delete your custom small icon does it resolve the issue? Can you try recreating your icon? If this does not help please attach your icon set to this issue.

**Comment by leonardoxh** [comment] 2017-07-24 18:02
I also faced this issue today

**Comment by jkasten2** [comment] 2017-07-24 18:25
@leonardoxh Could you provide more details to help us pin point the issue? Please include the stack trace so we can compare as well as the Android version and device models you seen this issue on. Let us know if you can reproduce the issue as well.

**Comment by leonardoxh** [comment] 2017-07-25 17:43
Hi,

One crash at moment, but have no idea about this... Crash at link http://crashes.to/s/23a6a07c7d8

**Comment by jkasten2** [comment] 2017-10-04 05:42
Closing this issue to merge it with issue https://github.com/OneSignal/OneSignal-Android-SDK/issues/263 since this is the same crash

**Closed by jkasten2** 2017-10-04 05:42 UTC
