### ISSUE TITLE
Google Play Services Library Error

### ISSUE THREAD

**Issue by tiagobpompeo** [OneSignal/OneSignal-Android-SDK#1011] opened 2020-05-08 17:38 UTC
**Description:**
Hello, in our application uses this library, to use Push to send on Android. It turns out that even with the updated libraries in our environment, we are receiving no notifications. When this happens, we access the OneSignal console to check for any error logs and discover the following message reported in the "subscribed" field, a "Google Play Services Library Error" message, occurs frequently, at some point until it has it stops occurring but unsteadily occurs again. Understanding the problems related to google's "Play Services".

**Environment**

1. What version of the Xamarin SDK are you using?
3.8.1
2. How did you add the SDK to your project (eg. nuget)
Nuget.org

**Steps to Reproduce Issue:**

Step by step to reproduce or error

1 - Install a Library in the Xamarin.Android project and make the settings 2 - Build an app and see the return on the One Signal Console 3 - Check the error in the "Audience" fields under "All users" and then in the "Subscribed" field, Google Play Services Library Error message 4 - Try Push , device dont receive

Any occurrence of another application?

Any suggestions to correct or reported error
**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment] 2020-05-08 21:33
Duplicate of https://github.com/OneSignal/OneSignal-Xamarin-SDK/issues/197

**Closed by jkasten2** 2020-05-08 21:33 UTC
Labels: Duplicate
