### ISSUE TITLE
Fatal Exception: android.app.RemoteServiceException Bad notification posted

### ISSUE THREAD

**Issue by j2emanue** [OneSignal/OneSignal-Android-SDK#415] opened 2018-01-22 02:51 UTC
3 users got the following error when sending notification : 

```java
Fatal Exception: android.app.RemoteServiceException
Bad notification posted from package com.mobile.myapp: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.mobile.myapp user=UserHandle{0} id=1017824114 tag=null key=0|com.mobile.myapp|1017824114|null|10204: Notification(pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x18 color=0x00000000 vis=PUBLIC semFlags=0x0 semPriority=0))
```

it occurred on this thread:

```java
ONESIGNAL_EXECUTOR_1519
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2128)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1091)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1084)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

and here is the stack trace:

```java
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package com.mobile.myapp: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.mobile.myapp user=UserHandle{0} id=1017824114 tag=null key=0|com.mobile.myapp|1017824114|null|10204: Notification(pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x18 color=0x00000000 vis=PUBLIC semFlags=0x0 semPriority=0))
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

here is my gradle dependency:
`implementation 'com.onesignal:OneSignal:[3.7.1, 3.99.99]'`

and android support library version: 27.0.2

For one of the users the error occurred on a non-rooted device with following specs:

SM-G950F device.  OS: 7.0

**Comment by sbrkx** [comment] 2018-01-26 09:02
I have the same issue:

`android.app.RemoteServiceException: 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1870)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6809)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)`

Latest SDK, 3.7.1 Android Support 27.0.2 and only Android 8 devices.
OnePlus OnePlus3T (OnePlus3T)

**Comment by saurabhtanu** [comment] 2018-02-24 12:39
Exactly the same problem,

android.app.RemoteServiceException:
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1870)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6809)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)

All crashes on OnePlus One devices and Android version 8.0 and above, any fix or automatic update coming up to fix this?

**Comment by jkasten2** [comment] 2018-03-05 07:32
@j2emanue This is a duplicate of issue #263, so going to merge it with that one. The `ONESIGNAL_EXECUTOR_1519` thread isn't related, it is in a waiting state.

@sbrkx @saurabhtanu The stack traces you reported aren't related to the first issue.
I also don't see OneSignal in the stack trace at all. Can you open a new issue and provide more detail when this happening in your app? Also any other details you can. Thanks

**Closed by jkasten2** 2018-03-05 07:32 UTC

**Comment by AhmadullahSaikat** [comment] 2018-10-03 17:45
Please replace `<android.support.v7.widget.AppCompatTextView` with `<TextView` from custom notification layout. Because `android.support.v7.widget.AppCompatTextView` or `android.support.v7.widget.AppCompatImageView` only works at runtime.

**Comment by jkasten2** [comment] 2018-10-03 18:58
@AhmadullahSaikat The SDK does use `android.support.v7`, we use the `TextView` directly instead of going through a support library. Same for the image view. Please point the the exact line of code in our SDK if I am mistaken in a new issue. We would like to keep each issue thread on a single topic. Also note that the OneSignal custom notification layout is only used if you set a background image for your notifications.

**Comment by alamincmt** [comment] 2019-09-05 06:39
android.app.RemoteServiceException:
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1870)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6809)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)

**android.app.RemoteServiceException:** This issue only occurs while you have started service as foregroundService but you didn't call startForeground with a foreground notification within 5 seconds. 

Look at this - [https://developer.android.com/guide/components/services#StartingAService]
