### ISSUE TITLE
[Bug]: Crash on 5.0.0 - "Unrecognized operation: login-user-from-subscription"

### ISSUE THREAD

**Issue by tajchert** [OneSignal/OneSignal-Android-SDK#1814] opened 2023-08-24 20:33 UTC
### What happened?

I see crash on few devices (Android 11 and 10 for sure).
This is on calling `OneSignal.initWithContext()`

### Steps to reproduce?

```Markdown
-
```

### What did you expect to happen?

-

### OneSignal Android SDK version

5.0.0

### Android version

11, 10

### Specific Android models

```Markdown
* Galaxy A31
* Galaxy A7 (2018)
* Galaxy S9+
* Moto G(9) Plus
* Nokia 9
```

### Relevant log output

```Shell
Stacktrace:

Caused by java.lang.reflect.InvocationTargetException:
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:90)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:83)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceProvider.getService$core_release(ServiceProvider.kt:40)
       at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:197)
       at com.onesignal.OneSignal.initWithContext(OneSignal.kt:126)
       at pl.tajchert.canary.CanaryApp.onCreate(CanaryApp.kt:66)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7593)
       at android.app.ActivityThread.access$1500(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Caused by java.lang.Exception: Unrecognized operation: login-user-from-subscription
       at com.onesignal.core.internal.operations.impl.OperationModelStore.create(OperationModelStore.kt:58)
       at com.onesignal.core.internal.operations.impl.OperationModelStore.create(OperationModelStore.kt:27)
       at com.onesignal.common.modeling.ModelStore.load(ModelStore.kt:129)
       at com.onesignal.core.internal.operations.impl.OperationModelStore.<init>(OperationModelStore.kt:30)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:90)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:83)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceProvider.getService$core_release(ServiceProvider.kt:40)
       at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:197)
       at com.onesignal.OneSignal.initWithContext(OneSignal.kt:126)
       at pl.tajchert.canary.CanaryApp.onCreate(CanaryApp.kt:66)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7593)
       at android.app.ActivityThread.access$1500(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

<!-- probot = {"onesignal-probot":{"response_time_in_business_days":1}} -->

**Comment by jennantilla** [comment] 2023-08-25 19:35
Hi @tajchert thanks for reaching out! We'll investigate this. Just to confirm, this does not happen with every device you've tested, only some? Are you migrating from a previous version of our SDK or is this a fresh install of 5.0.0?

**Comment by tajchert** [comment] 2023-08-25 23:34
Hi,
I was not able to reproduce this locally.
Yes, this happens only in case of very few users of my app (<1%).
In my previous app release I used Onesignal 4.8.3 SDK. 

I don't know if in case of those users it was upgrade or clean install sadly.

**Comment by atanasovdejan** [comment] 2023-08-27 10:41
I am having the same issue on my side after upgrading to version 5. 

I can see that it's happening on Android 12 and 13 too.

**Comment by vknow360** [comment] 2023-08-27 12:42
I am having same issue as well. Checked on Android 13.
Here is logcat:
````
08-27 17:41:40.205  9446  9446 W System.err:  java.lang.reflect.InvocationTargetException
08-27 17:41:40.205  9446  9446 W System.err: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-27 17:41:40.205  9446  9446 W System.err: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
08-27 17:41:40.205  9446  9446 W System.err: 	at com.onesignal.common.services.ServiceRegistrationReflection.resolve(Unknown Source:217)
08-27 17:41:40.205  9446  9446 W System.err: 	at com.onesignal.common.services.ServiceProvider.getServiceOrNull(Unknown Source:50)
08-27 17:41:40.205  9446  9446 W System.err: 	at com.onesignal.common.services.ServiceProvider.getService(Unknown Source:5)
08-27 17:41:40.205  9446  9446 W System.err: 	at com.onesignal.common.services.ServiceRegistrationReflection.resolve(Unknown Source:187)
08-27 17:41:40.205  9446  9446 W System.err: 	at com.onesignal.common.services.ServiceProvider.getServiceOrNull(Unknown Source:50)
08-27 17:41:40.205  9446  9446 W System.err: 	at com.onesignal.common.services.ServiceProvider.getService(Unknown Source:5)
08-27 17:41:40.205  9446  9446 W System.err: 	at com.onesignal.internal.OneSignalImp.initWithContext(Unknown Source:78)
08-27 17:41:40.205  9446  9446 W System.err: 	at com.onesignal.OneSignal.initWithContext(Unknown Source:16)
08-27 17:41:40.205  9446  9446 W System.err: 	at com.sunny.push.OneSignalPush.Init(Unknown Source:11)
08-27 17:41:40.205  9446  9446 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-27 17:41:40.205  9446  9446 W System.err: 	at gnu.expr.PrimProcedure.apply(Unknown Source:182)
08-27 17:41:40.205  9446  9446 W System.err: 	at gnu.mapping.CallContext.runUntilDone(Unknown Source:8)
08-27 17:41:40.205  9446  9446 W System.err: 	at gnu.mapping.CallContext.runUntilValue(Unknown Source:10)
08-27 17:41:40.205  9446  9446 W System.err: 	at gnu.mapping.MethodProc.applyN(Unknown Source:11)
08-27 17:41:40.205  9446  9446 W System.err: 	at gnu.kawa.reflect.Invoke.applyN(Unknown Source:237)
08-27 17:41:40.205  9446  9446 W System.err: 	at gnu.kawa.functions.ApplyToArgs.applyN(Unknown Source:17)
08-27 17:41:40.205  9446  9446 W System.err: 	at gnu.kawa.functions.Apply.applyN(Unknown Source:7)
08-27 17:41:40.205  9446  9446 W System.err: 	at gnu.mapping.ProcedureN.apply2(Unknown Source:9)
08-27 17:41:40.205  9446  9446 W System.err: 	at com.google.youngandroid.runtime.callComponentMethod(Unknown Source:57)
08-27 17:41:40.205  9446  9446 W System.err: 	at com.appzard.vknow360.Push.Screen1.Button1$Click(Unknown Source:15)
08-27 17:41:40.205  9446  9446 W System.err: 	at com.appzard.vknow360.Push.Screen1$frame.apply0(Unknown Source:10)
08-27 17:41:40.206  9446  9446 W System.err: 	at gnu.expr.ModuleBody.applyN(Unknown Source:72)
08-27 17:41:40.206  9446  9446 W System.err: 	at gnu.expr.ModuleMethod.applyN(Unknown Source:2)
08-27 17:41:40.206  9446  9446 W System.err: 	at gnu.kawa.functions.ApplyToArgs.applyN(Unknown Source:17)
08-27 17:41:40.206  9446  9446 W System.err: 	at gnu.kawa.functions.Apply.applyN(Unknown Source:7)
08-27 17:41:40.206  9446  9446 W System.err: 	at gnu.mapping.ProcedureN.apply2(Unknown Source:9)
08-27 17:41:40.206  9446  9446 W System.err: 	at com.appzard.vknow360.Push.Screen1.dispatchEvent(Unknown Source:28)
08-27 17:41:40.206  9446  9446 W System.err: 	at com.google.appinventor.components.runtime.EventDispatcher.dispatchEvent(Unknown Source:10)
08-27 17:41:40.206  9446  9446 W System.err: 	at com.google.appinventor.components.runtime.Button.Click(Unknown Source:5)
08-27 17:41:40.206  9446  9446 W System.err: 	at com.google.appinventor.components.runtime.Button.click(Unknown Source:0)
08-27 17:41:40.206  9446  9446 W System.err: 	at com.google.appinventor.components.runtime.ButtonBase.onClick(Unknown Source:0)
08-27 17:41:40.206  9446  9446 W System.err: 	at android.view.View.performClick(View.java:7590)
08-27 17:41:40.206  9446  9446 W System.err: 	at android.view.View.performClickInternal(View.java:7567)
08-27 17:41:40.206  9446  9446 W System.err: 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
08-27 17:41:40.206  9446  9446 W System.err: 	at android.view.View$PerformClick.run(View.java:29724)
08-27 17:41:40.206  9446  9446 W System.err: 	at android.os.Handler.handleCallback(Handler.java:942)
08-27 17:41:40.206  9446  9446 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-27 17:41:40.206  9446  9446 W System.err: 	at android.os.Looper.loopOnce(Looper.java:223)
08-27 17:41:40.206  9446  9446 W System.err: 	at android.os.Looper.loop(Looper.java:324)
08-27 17:41:40.206  9446  9446 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8378)
08-27 17:41:40.206  9446  9446 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-27 17:41:40.206  9446  9446 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
08-27 17:41:40.206  9446  9446 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)
08-27 17:41:40.206  9446  9446 W System.err: Caused by: java.lang.ExceptionInInitializerError
08-27 17:41:40.206  9446  9446 W System.err: 	at kotlinx.coroutines.channels.ChannelKt.Channel(Unknown Source:63)
08-27 17:41:40.206  9446  9446 W System.err: 	at kotlinx.coroutines.channels.ChannelKt.Channel$default(Unknown Source:16)
08-27 17:41:40.206  9446  9446 W System.err: 	at com.onesignal.common.threading.Waiter.<init>(Unknown Source:6)
08-27 17:41:40.206  9446  9446 W System.err: 	at com.onesignal.core.internal.preferences.impl.PreferencesService.<init>(Unknown Source:4)
08-27 17:41:40.206  9446  9446 W System.err: 	... 45 more
08-27 17:41:40.206  9446  9446 W System.err: Caused by: java.lang.ClassCastException
08-27 17:41:40.206  9446  9446 W System.err: 	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:365)
08-27 17:41:40.206  9446  9446 W System.err: 	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(AtomicReferenceFieldUpdater.java:116)
08-27 17:41:40.206  9446  9446 W System.err: 	at kotlinx.coroutines.channels.AbstractSendChannel.<clinit>(Unknown Source:6)
08-27 17:41:40.206  9446  9446 W System.err: 	... 49 more

````

**Comment by ahmtbrk** [comment] 2023-09-03 10:48
Not publishing the proguard rules of version 5.0 is a big novice. Not good for such a big company. Release proguard rules for 5.x versions urgently.

**Comment by devmuaz** [comment] 2023-09-07 22:15
I getting the same issue reported by Firebase Crashlytics!
Got more than 90K crashes in about 2 hours only!

**Comment by xanscale** [comment] 2023-09-09 13:30
any news?

**Comment by vfilho** [comment] 2023-09-11 19:40
I'm having the same issue.  Help, please.

**Comment by tajchert** [comment] 2023-09-11 21:58
I ended up removing OneSignal, but I might realize it might not be so easy for others to do it right away.

**Comment by xanscale** [comment] 2023-09-14 09:21
Is it used somewhere?

https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/user/internal/operations/impl/executors/LoginUserFromSubscriptionOperationExecutor.kt

**Comment by Petr-Kubista** [comment] 2023-09-18 08:56
What's the status on this? It is holding back a big release for us and going back to earlier OneSignal version is not really an option, as it is not compatible with other latest versions of firebase packages and gradle.

**Comment by israellot** [comment] 2023-09-21 15:11
Nothing yet?

**Comment by emawby** [comment] 2023-09-21 16:39
The proguard issues should be resolved in version 5.0.1. If anyone is still seeing crashes only for release (minify) builds please tag me and post the stack trace

**Comment by vfilho** [comment] 2023-09-21 16:43
We don't have the minify enabled for release builds, but we are still seeing this crash.

**Comment by emawby** [comment] 2023-09-21 17:06
I apologize this seems like a separate issue, I have identified the issue and it will be resolved in the next release. Thank you for your patience.

**Comment by israellot** [comment] 2023-09-21 17:20
ETA @emawby ?

**Comment by vfilho** [comment] 2023-09-21 17:30
Any possible workaround until we wait for the next release @emawby ?

**Comment by Rudieri34** [comment] 2023-09-21 23:24
Same Issue Here

**Comment by chriscborg** [comment] 2023-09-25 09:49
What's the ETA on this release please? We're getting thousands of crashes because of this and we can't rollback the version number at this stage.

**Comment by devmuaz** [comment] 2023-09-25 09:52
I think they've fixed it and released a new version [v5.0.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.1).
I haven't tried it yet, in our case we've rolled back to the other version for now!

**Comment by chriscborg** [comment] 2023-09-25 10:19
I tried installing v5.0.1 but I'm still getting the same crashes...

**Comment by devmuaz** [comment] 2023-09-25 10:28
@chriscborg Yeah, kinda figured!
If the issue still persists, try rolling back to `v4.x.x` and handle notifications permission manually on devices running `Android 13 (API level 33)` and higher.

I'm pretty much sure they're trying to fix this ASAP but to make sure everything is stable for you right now, try to rollback as much as you can until a stable version gets released!

**Comment by jkasten2** [comment] 2023-09-29 20:50
This specific Unrecognized operation: login-user-from-subscription issue has been resolved in [OneSignal-Android-SDK 5.0.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.2)

If you are still seeing this exact issue let us know and we can reopen this issue.

**Closed by jkasten2** 2023-09-29 20:50 UTC

**Comment by Neferetheka** [comment] 2023-10-05 12:35
I confirm the issue is still there in V5.0.2

**Comment by emawby** [comment] 2023-10-10 19:05
@Neferetheka Can you provide more details on the error. There have been multiple crashes on startup with different stack traces so if you could post it that would be very helpful.

**Comment by ucf0709** [comment] 2023-11-13 11:12
W/System.err: java.lang.reflect.InvocationTargetException
W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
W/System.err:     at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:89)
W/System.err:     at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
W/System.err:     at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
W/System.err:     at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:82)
W/System.err:     at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
W/System.err:     at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
W/System.err:     at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:82)
W/System.err:     at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
W/System.err:     at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
W/System.err:     at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:474)
W/System.err:     at com.onesignal.OneSignal.initWithContext(OneSignal.kt:135)

Still hapening on v5.0.4
