### ISSUE TITLE
NullPointerException in RestoreJobService

### ISSUE THREAD

**Issue by ayushsingla991** [OneSignal/OneSignal-Android-SDK#591] opened 2018-07-16 13:08 UTC
**Description:**

I am getting crash reports on firebase.

**Environment**

Onesignal Version: 3.9.1
Android SDK Version: 27
Build Tools Version: 27.0.3

Android Version On which crash is detected: 6.0.1
Device: Nexus 4

**Steps to Reproduce Issue:**

Can't reproduce. It came in Firebase Crashlytics. Tried everything with onesignal but I am unable to get the crash.

**Anything else:**

```
Fatal Exception: java.lang.RuntimeException
An error occurred while executing doInBackground()
```

```
Caused by java.lang.NullPointerException

android.os.BaseBundle.<init> (BaseBundle.java:127)
android.os.Bundle.<init> (Bundle.java:102)
com.onesignal.RestoreJobService.onHandleWork (RestoreJobService.java:41)
com.onesignal.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:386)
com.onesignal.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:377)
android.os.AsyncTask$2.call (AsyncTask.java:295)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
```

![Image of Firebase Screenshot](https://image.ibb.co/ksysry/Screenshot001.png)

**Comment by jkasten2** [comment] 2018-07-16 23:35
@ayushsingla991 Thanks for the report, we will review the code from the stack to see if we can find any potential issues.

Can you share how many users are being effected by this crash?

**Comment by ayushsingla991** [comment] 2018-07-17 06:47
@jkasten2  The app is recently updated with OneSignal yesterday. So, Users affected by the crash are 2 and the occurrence of the crash is 4.

**Comment by dostalleos** [comment] 2018-08-10 16:53
I have same crash reports in Crashlytics. Onesignal version 3.9.1, OS version 6.0.1, Nexus 4 not rooted. 4 users and 9 crashes in 10 hours.

**Comment by jkasten2** [comment] 2018-09-25 23:34
Thanks for reporting everyone, we have only seem reports of Android 6.0.1 here so it would seem this is only an issue in this version. I have created a PR with an added `null` change to work around this Android bug. It will be included in the next release.

**Closed** 2018-09-26 02:55 UTC
Labels: Bug

**Comment by sandijs-lattelecom** [comment] 2018-11-22 12:16
This is still an issue with Android SDK 28, OneSignal 3.10.3
Nexus 4, Android 6.0.1

Happens on app cold startup, potentially after some crash with previous activities being going on.

#39
RestoreJobService.java line 41
com.onesignal.RestoreJobService.onHandleWork

Caused by java.lang.NullPointerException: Attempt to read from field 'android.os.Parcel android.os.BaseBundle.mParcelledData' on a null object reference
       at android.os.BaseBundle.<init>(BaseBundle.java:127)
       at android.os.Bundle.<init>(Bundle.java:102)
       at com.onesignal.RestoreJobService.onHandleWork(RestoreJobService.java:41)
       at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:386)
       at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:377)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by toxisco** [comment] 2018-11-22 19:08
I can confim that bug/issue is still running. with Android SDK 28, OneSignal 3.9.3.
SM-A510F (7.0)

RestoreJobService.java line 41
com.onesignal.RestoreJobService.onHandleWork
Caused by java.lang.NullPointerException: Attempt to read from field 'android.os.Parcel android.os.BaseBundle.mParcelledData' on a null object reference
       at android.os.BaseBundle.<init>(BaseBundle.java:121)
       at android.os.Bundle.<init>(Bundle.java:102)
       at com.onesignal.RestoreJobService.onHandleWork(RestoreJobService.java:41)
       at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:386)
       at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:377)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:820)

**Comment by sandijs-lattelecom** [comment] 2018-11-23 06:13
I saw that OneSignal is using Firebase 12.x.x, and out there it is something like 16.x.x - maybe it is time to upgrade Firebase libraries?

**Comment by jkasten2** [comment] 2018-11-26 18:39
@sandijs-lattelecom Can you confirm the stack trace is definitely from a version of your app that contains the [OneSignal SDK 3.10.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.10.2) or newer?

Based on your stack trace `RestoreJobService.java:41` this points to a comment so it seems that stacktrace is from an older version.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.10.3/OneSignalSDK/onesignal/src/main/java/com/onesignal/RestoreJobService.java#L41

@toxisco Updating to 3.10.3 should fix this issue for you.

**Comment by sandijs-lattelecom** [comment] 2018-11-27 05:55
implementation('com.onesignal:OneSignal:3.10.3') {
        exclude group: 'com.google.android.gms'
        exclude group: 'com.google.firebase'
    }
    implementation('com.google.firebase:firebase-core:16.0.4') {
        exclude group: 'com.android.support'
        exclude group: 'com.google.android.gms'
    }

**Comment by sandijs-lattelecom** [comment] 2018-11-27 05:57
Yes, it could be 3.10.2 :(

**Comment by toxisco** [comment] 2018-11-30 12:15
jkasten2 I can confirm, it's fixed. Thank you!
